camptocamp/c2cgeoportal

- .travis.yml
- c2cgeoportal/models.py
- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/tests/functional/test_mobile_desktop.py
- c2cgeoportal/tests/functional/test_themes.py
- c2cgeoportal/views/entry.py
- setup.cfg
And fix it, also fix #1166 , Geoportail-Luxembourg/geoportailv3#129
> Test theme webservice

- c2cgeoportal/forms.py
- c2cgeoportal/scaffolds/create/versions.cfg
- setup.py
> Admin fix for restrication area

- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- doc/integrator/create_application.rst
- doc/integrator/index.rst
- doc/integrator/make.rst
- doc/integrator/print.rst
> Add the changes in the changelog for the project make

- c2cgeoportal/scaffolds/create/versions.cfg
> Fix lovely.buildouthttp version

- c2cgeoportal/scaffolds/update/+package+/static/mobile/app/controller/Query.js
> Ensure that result features have attributes, don't show if they don't

- .travis.yml
- Makefile
- c2cgeoportal/scaffolds/create/apache/wsgi.conf.mako
- c2cgeoportal/scaffolds/create/print/config.yaml.mako_tmpl
- c2cgeoportal/scaffolds/create/vars_+package+.yaml
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_packages.yaml
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- doc/build.sh
- doc/integrator/deploy.rst
- doc/integrator/shortener.rst
- travis/build-new-project.sh
- travis/build.mk
- travis/empty-make-new-project.sh
- travis/empty-make.sh
- travis/test-new-project.sh
> Fix some Make issues, test project creation, fix it

- c2cgeoportal/tests/functional/__init__.py
- c2cgeoportal/tests/functional/test_layers.py
- c2cgeoportal/views/layers.py
- vars.yaml
Validate the geometries on update and create using the PostGIS functions `ST_IsSimple` and `ST_IsValid`.
> Validate geometries on update/create

- c2cgeoportal/tests/functional/test_layers.py
To make Coveralls and @sbrunner happy. :)
> Add additional geometry validation test

- travis/pip.sh
> Remove unappropriated comment

- c2cgeoportal/views/entry.py
fix https://github.com/camptocamp/c2cgeoportal/pull/1198#issuecomment-71990517
> Fix, str and int concatenation

- c2cgeoportal/lib/caching.py
- c2cgeoportal/tests/functional/test_mapserverproxy.py
- c2cgeoportal/views/entry.py
- c2cgeoportal/views/fulltextsearch.py
- c2cgeoportal/views/layers.py
- c2cgeoportal/views/mapserverproxy.py
- c2cgeoportal/views/printproxy.py
- doc/integrator/caching.rst
- doc/integrator/index.rst
> Add configurable caching

- c2cgeoportal/scripts/c2ctool.py
> Fix Apache error on Windows

- c2cgeoportal/__init__.py
- c2cgeoportal/scaffolds/create/apache/frontend.conf.in
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/views/mapserverproxy.py
- doc/integrator/security.rst
> Enable the CORS headers / Be able to desable the OGC proxy

- doc/developer/build_release.rst
- travis/deploy.sh
> Create the release on Travis CI to avoid release build issues

- c2cgeoportal/__init__.py
- c2cgeoportal/views/pdfreport.py
- doc/integrator/pdfreport.rst
> Pdfreport improvements

- doc/integrator/raster.rst
cf. https://github.com/camptocamp/c2cgeoportal/issues/1244
> delete translation paragraph in the raster doc

- c2cgeoportal/scaffolds/update/CONST_requirements.txt
To get this pullrequest: https://github.com/Pylons/pyramid/pull/1587
Will fix: #1247
> Update Pyramid to fix admin interface issue

- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/views/entry.py
on pages that changed with the language
remove the lang attibute on pages that don't change with the language
> Add the header Vary:Accept-Language

- c2cgeoportal/scaffolds/create/deploy/hooks/post-restore-code
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- doc/integrator/create_application.rst
> De able to deploy the project based on make

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Fix sencha touch dev page and dependencies

- setup.py
> Fix version conflict on some environment

- c2cgeoportal/scaffolds/create/+package+.mk_tmpl
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scripts/c2ctool.py
- doc/integrator/index.rst
- doc/integrator/install_application.rst
- doc/integrator/make.rst
- doc/integrator/upgrade_application.rst
- travis/build-new-project.sh
> Some changes arround c2ctool

- c2cgeoportal/lib/cacheversion.py
Related to https://github.com/Pylons/pyramid/pull/1583/files#diff-9115900085d44ecb3b0c7d66f6e8e8c7L177
> Fix issue when using cache buster

- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
> Allow ip for IPv6

- c2cgeoportal/forms.py
- c2cgeoportal/scaffolds/create/+package+/forms.py_tmpl
The admin interface isn't configured on new projects
> Fix theme editing don't work

- c2cgeoportal/__init__.py
- c2cgeoportal/lib/caching.py
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- c2cgeoportal/tests/functional/test_dbreflection.py
- c2cgeoportal/tests/functional/test_echo.py
- c2cgeoportal/tests/functional/test_fulltextsearch.py
- c2cgeoportal/tests/functional/test_groups_finder.py
- c2cgeoportal/tests/functional/test_layers.py
- c2cgeoportal/tests/functional/test_looptheme.py
- c2cgeoportal/tests/functional/test_mapserverproxy.py
- c2cgeoportal/tests/functional/test_ogcproxy.py
- c2cgeoportal/tests/functional/test_request_property.py
- c2cgeoportal/tests/functional/test_shortener.py
- c2cgeoportal/views/mapserverproxy.py
- c2cgeoportal/views/printproxy.py
- c2cgeoportal/views/proxy.py
- doc/integrator/make.rst
Use an attr for all functional tests
Refractor the proxies
First step to use MapFish Print V3, the pull request on GeoExt and on GGXP will follow the next weeks.
> Add Mapfish Print V3 support

- c2cgeoportal/__init__.py
- c2cgeoportal/scaffolds/create/vars_+package+.yaml_tmpl
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- c2cgeoportal/views/checker.py
> Add theme and language checker

- c2cgeoportal/__init__.py
- c2cgeoportal/lib/__init__.py
- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/tests/test_get_url.py
> Use asset override to get URLs

- c2cgeoportal/__init__.py
- doc/integrator/security.rst
> Fix ogcproxy_enable settigs and update the documentation

- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- c2cgeoportal/tests/functional/__init__.py
- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/tests/functional/test_functionalities.py
- c2cgeoportal/tests/functional/test_looptheme.py
- c2cgeoportal/tests/functional/test_mapserverproxy.py
- c2cgeoportal/tests/functional/test_mapserverproxy_group.py
- c2cgeoportal/tests/functional/test_mobile_desktop.py
- c2cgeoportal/tests/functional/test_themes.py
- c2cgeoportal/views/entry.py
- c2cgeoportal/views/mapserverproxy.py
> Group mapserver proxy settings

- c2cgeoportal/locale/de/LC_MESSAGES/c2cgeoportal.po
- c2cgeoportal/locale/en/LC_MESSAGES/c2cgeoportal.po
- c2cgeoportal/locale/fr/LC_MESSAGES/c2cgeoportal.po
- c2cgeoportal/models.py
> Add i18n for LayergroupTreeitem

- c2cgeoportal/lib/authentication.py
- c2cgeoportal/scaffolds/create/development.ini.in_tmpl
- c2cgeoportal/scaffolds/create/production.ini.in_tmpl
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/scaffolds/update/CONST_buildout.cfg_tmpl
- c2cgeoportal/tests/functional/test_request_property.py
I have cherry-picked commit e13c049624bac3a8243db7407ad22c43c9ac44b8 and adapted it to the structure of branch 1.5.
> Port auth cookie expiration config from branch master

- doc/administrator/mapfile.rst
- doc/developer/debugging.rst
Add Missing/Misplaced steps...
> Add doc to generate indexed rasters

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- travis/build.mk
See: https://github.com/mapfish/mapfish-print/issues/221#issuecomment-86845418
> Restart Tomcat on each deploy

- c2cgeoportal/locale/de/LC_MESSAGES/c2cgeoportal.po
- c2cgeoportal/locale/en/LC_MESSAGES/c2cgeoportal.po
- c2cgeoportal/locale/fr/LC_MESSAGES/c2cgeoportal.po
- c2cgeoportal/views/profile.py
> Internationalise distance in profile

- doc/integrator/install_application.rst
- doc/integrator/mobile.rst
> Docs improvements

- .gitignore
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
See commit messages for details
> Some backports form SITN

- doc/integrator/requirements.rst
This PR rewrites the documentation for Windows.
There are still things to add like downloading wheels, which pip cannot install because of binaries and dll, but this will be part of another PR (which I hope to propose soon...)
Please review
> First steps to improve the documentation for Windows

- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/scripts/c2ctool.py
- doc/integrator/upgrade_application.rst
See commits messages for details
> Upgrade notes

- doc/integrator/requirements.rst
Sorry, I did not know about that when I submitted #1341...
> Doc to avoid permission problems in Cygwin

- c2cgeoportal/__init__.py
- c2cgeoportal/scaffolds/create/vars_+package+.yaml_tmpl
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- c2cgeoportal/views/checker.py
> Add checker for print v3

- c2cgeoportal/scaffolds/create/build.json
> Set closure compiler language in to ECMASCRIPT5_STRICT

- c2cgeoportal/scaffolds/create/package.json
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
Geoportail-Luxembourg/geoportailv3#362
Geoportail-Luxembourg/geoportailv3#340
> Backport from Luxembourg

- .gitignore
- c2cgeoportal/__init__.py
- c2cgeoportal/views/echo.py
- c2cgeoportal/views/exportcsv.py
- c2cgeoportal/views/printproxy.py
Related to https://github.com/Geoportail-Luxembourg/geoportailv3/issues/478
> Add print cancel, specify reqest method everywhere

- c2cgeoportal/__init__.py
All those can be called in POST during the login...
> Fix routes for login

- c2cgeoportal/__init__.py
> Fix request method for "loginchange" route

- c2cgeoportal/scripts/c2ctool.py
Title says it all.
There is only one open question left (`.build/requirements.timestamp`, see https://github.com/camptocamp/c2cgeoportal/issues/1377) and some "Windows" specific doc to add...
> Make c2ctool Windows compatible

- doc/integrator/upgrade_application.rst
> Fix the documentation after the sphinx-prompt release 1.0.0

- doc/integrator/upgrade_application.rst
This describes what I had to do on Windows to be able to upgrade the app using `c2tool.py`
> Add some doc for upgrading on Windows

- c2cgeoportal/static/adminapp/css/admin.css
Set a fix size because we many times have a wrong size :-(
> Fix breadcrumb size

- .travis.yml
- c2cgeoportal/scaffolds/create/+package+/subscribers.py_tmpl
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
It make encoding issue if the first return some accents.
> Don't translate a translated string

- c2cgeoportal/views/proxy.py
@kalbermattenm does it will fix your issue #1394 ?
> Remove header from hop-by-hop transport

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Don't generate templates in static/lib

- doc/integrator/print.rst
> Add some documentation about MapFishPrint v3

- c2cgeoportal/scaffolds/update/CONST_dev-requirements.txt
- c2cgeoportal/scaffolds/update/CONST_requirements.txt
- c2cgeoportal/scaffolds/update/CONST_requirements_windows.txt
Actually after a cleanall / build we have the latest stable version
instance of the development version.
> Fix installed pyramid version

- doc/integrator/upgrade_application.rst
Title says it all, sorry for not having seen when I did submit the PR...
> Correct & specify some doc for Windows

- doc/integrator/deploy.rst
- doc/integrator/install_application.rst
> Use the new sigdev user in the shared environemnt

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- doc/integrator/create_application.rst
Related to: https://github.com/camptocamp/rudaz_geomapfish/pull/1
Replace: https://github.com/camptocamp/c2cgeoportal/pull/1372
> Update docs for multi-instance setup

- c2cgeoportal/scripts/c2ctool.py
> Fix the update on the rc1

- c2cgeoportal/__init__.py
fix https://github.com/Geoportail-Luxembourg/geoportailv3/pull/547#discussion_r32918692
> Add OPTIONS method do be able to do CORS call

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
fix https://github.com/Geoportail-Luxembourg/geoportailv3/issues/566
> Error message on no sencha app

- .travis.yml
The branch 1.6 is not automatically fetch ...
> Try to fix travis tests on 1.6 branch

- c2cgeoportal/__init__.py
so the login can use other authentication system
> remove POST limitation in route login

- doc/integrator/install_application.rst
- doc/integrator/upgrade_application.rst
> Remove the no more needed documentation

- c2cgeoportal/scaffolds/create/build.json_tmpl
> Don't hardcode the path to js files but use {{package}}

- c2cgeoportal/scaffolds/create/package.json
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
Back-port of https://github.com/Geoportail-Luxembourg/geoportailv3/pull/641
> Be able to add project specific libs

- c2cgeoportal/scaffolds/create/package.json_tmpl
> Update jshint to v2.8.0

- c2cgeoportal/scaffolds/create/build.json_tmpl
- c2cgeoportal/scaffolds/create/package.json_tmpl
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Update angular to v1.4.3

- c2cgeoportal/scaffolds/create/package.json_tmpl
> Update angular-gettext to v2.1.0

- c2cgeoportal/scaffolds/create/templatecache.js.mako
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
Same as #1439 but for with the changelog entry for version 2.0.0 (close #1439)
> Add templatecache.js.mako

- doc/integrator/index.rst
- doc/integrator/preparative_work.rst
cf. old Pull request https://github.com/camptocamp/c2cgeoportal/pull/1453
This is the new one based on 1.6
> HowTo PuTTY, WinSCP and add SSH keys

- c2cgeoportal/scaffolds/create/+dot+travis.yml
> Fix database name

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
The related documentation will be added in the master branch
> Be able to lunch the upgrade throw make to never failed

- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scripts/c2ctool.py
- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/views/entry.py
- doc/developer/build_release.rst
- doc/integrator/upgrade_application.rst
> Some issue found during an upgrade

- doc/integrator/upgrade_application.rst
> Fix typos and confusing sentence in upgrading doc

- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
Else one may think updating only the root section of the first file (app.js) is enough.
> Fix confusing sentence about root sections in jsbuild/app.cfg.mako

- c2cgeoportal/views/entry.py
fix #1496
See result at: http://preprodnew.cartoriviera.ch/sbrunner/mobile
> Fix the default mobile theme

- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
Fix comment on 8b2bae0604f2a726428ee06dd9b2ddbb5def41e3
> Add log precision

- c2cgeoportal/models.py
- c2cgeoportal/scaffolds/create/vars_+package+.yaml_tmpl
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_alembic/main/script.py.mako
- c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/53ba1a68d5fe_add_theme_to_fulltextsearch.py
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- c2cgeoportal/scripts/theme2fts.py
- c2cgeoportal/scripts/themev1tov2.py
- c2cgeoportal/tests/functional/__init__.py
- c2cgeoportal/tests/functional/test_fulltextsearch.py
- c2cgeoportal/views/fulltextsearch.py
- doc/integrator/fulltext_search.rst
- setup.py
Add some columns in the Full-Text Search table
Add a script to fill the Full-Text Search table with the theme
Update the Full-Text Search view to take care on the new columns
Also see others cmmits
> Add the theme in the Full-Text Search

- doc/integrator/create_application.rst
Commit message start with a capital
> The version is actually in the CONST_requirements file

- c2cgeoportal/scaffolds/create/vars_+package+.yaml_tmpl
> Disable checker for ngeo language files in 1.6

- doc/update_online.sh
Distribute don't works any-more ...
> Use setuptools in the documentation virtual environment

- .travis.yml
- c2cgeoportal/scaffolds/create/+package+/templates/api/xapi.js_tmpl
- c2cgeoportal/views/checker.py
- c2cgeoportal/views/entry.py
- travis/build-new-project.sh
- travis/build.mk
- travis/test-new-project.sh
- travis/vars.yaml
> Test the new project ….

- c2cgeoportal/locale/de/LC_MESSAGES/c2cgeoportal.po
- c2cgeoportal/locale/es/LC_MESSAGES/c2cgeoportal.po
- c2cgeoportal/locale/fr/LC_MESSAGES/c2cgeoportal.po
> Update from Transifex

- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
By the way what are the "required changes" mentioned at point 2 of 1.6.3?
> Fix typo and incorrect filename in CHANGELOG

- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
use correct folder for js auto discovery with ngeo, 
auto eval of closure_library_path variable
> correct and complet CONST_vars

- c2cgeoportal/views/entry.py
See http://docs.pylonsproject.org/projects/pyramid//en/latest/api/i18n.html#pyramid.i18n.get_locale_name
> Stop using deprecated pyramid.i18n.get_locale_name

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_packages.yaml
> Be able to disable deploy package check

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Add the full-text search to the config vars

- c2cgeoportal/scaffolds/create/build.json_tmpl
> Add gmfx extern in build.json

- c2cgeoportal/scaffolds/create/+package+/templates/viewer.js_tmpl
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
Related to https://github.com/camptocamp/cgxp/pull/1011
> Print config to use the right DPI from the print to mapserver

- doc/integrator/upgrade_application.rst
added documentation how to migrate geometry column to Postgis 2 new Typmod, needed when using edition
> Postgis 2 migration documentation for editable tables

- c2cgeoportal/scaffolds/update/CONST_versions.txt
Temporary until this pull request will be merge:
https://github.com/FormAlchemy/formalchemy/pull/67
> Be able to create a select field with webhelper2

- doc/integrator/upgrade_application.rst
same as previous PR, but this time after restoring the db (sorry, I forgot to do it in my previous PR)
> dont use schema name in renamed values

- c2cgeoportal/scaffolds/create/+package+/templates/viewer.js_tmpl
Actually we have an error because we set the outputTarget to a tbar :-(
> Fix print placement

- doc/administrator/administrate.rst
> Clearer doc for the config: URL

- doc/integrator/backend_qgis.rst
For: https://github.com/camptocamp/cgxp/pull/1011
> Update the QGIS documentation

- c2cgeoportal/lib/lingua_extractor.py
- c2cgeoportal/scaffolds/update/tools/extract-messages.js
> Adapte output of the extract-messages tool

- c2cgeoportal/scaffolds/create/+dot+gitignore_tmpl
- c2cgeoportal/scaffolds/create/deploy/hooks/pre-restore-database.mako
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
* Move the script from post-restore-database to pre-restore-database
* Get the Apache stop from the default script
* Cleanup
> Copy the user database before remove it

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scripts/c2ctool.py
Add missing UPGRADE_ARGS
Add arguments --index-url and --c2cgeoportal-url to be able to upgrade to version 2.0
> Prepare to upgrade to 2.0

- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
> Fix wrong deploy hook name in 1.6.4 changelog

- c2cgeoportal/scripts/c2ctool.py
> Typo: lunch -> launch

- doc/integrator/deploy.rst
> Add note to access to GitHub using sigdev

- doc/integrator/upgrade_application.rst
- correct automatic <geometry_column> name use in constraint
- add comment about VIEWS + helper sql
> Corrected and completed the postgis2 migration doc

- .travis.yml
- travis/after_deploy.sh
- travis/deploy.sh
- travis/doindex.py
On each commit on master and x.y branches a new wheel will be added on a GitHub release.
> Deploy on GitHub releases

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Add xml to print v2 included types

- c2cgeoportal/scaffolds/__init__.py
> Fix Python utf8 error on scaffolds

- c2cgeoportal/models.py
> Be able to delete a layer

- c2cgeoportal/forms.py
> Display a combo for the role on the user edit

- c2cgeoportal/scaffolds/update/CONST_versions.txt
- setup.py
> Update jqgrid to fix the admin interface

- c2cgeoportal/scaffolds/update/CONST_versions.txt
To get https://github.com/FormAlchemy/fa.jquery/pull/27
fix #1538 again ...
> Update fa.jquery to order on relation

- c2cgeoportal/models.py
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- c2cgeoportal/tests/functional/__init__.py
- c2cgeoportal/tests/functional/c2cgeoportal_test.map.mako
- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/tests/functional/test_functionalities.py
- c2cgeoportal/tests/functional/test_looptheme.py
- c2cgeoportal/tests/functional/test_mapserverproxy.py
- c2cgeoportal/tests/functional/test_mapserverproxy_group.py
- c2cgeoportal/views/entry.py
- c2cgeoportal/views/mapserverproxy.py
> Add auth that support GeoServer

- .travis.yml
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/scaffolds/update/CONST_requirements.txt
- c2cgeoportal/scaffolds/update/CONST_requirements_windows.txt
- c2cgeoportal/scaffolds/update/CONST_versions.txt
- c2cgeoportal/scripts/c2ctool.py
- doc/developer/build_release.rst
- doc/integrator/upgrade_application.rst
Already done by make
Template files can be useful to debug the build and the application
Add upgrade from 1.5 to 2.0 note
> Some upgrade improvement

- doc/integrator/checker.rst
- doc/integrator/create_application.rst
- doc/integrator/customize_ui.rst
- doc/integrator/internationalization.rst
- doc/integrator/shortener.rst
- doc/integrator/tilegeneration.rst
> removed $ from -variable replacement in yaml files

- c2cgeoportal/lib/dbreflection.py
- c2cgeoportal/models.py
- c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/32527659d57b_move_exclude_properties_from_layerv1_to_.py
- doc/administrator/administrate.rst
Move exclude_properties from Layerv1 to Layer
> Be able to exclude enumerated attribute

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Typo in the apache/tiles.conf rule

- .travis.yml
- c2cgeoportal/scaffolds/update/CONST_alembic/main/env.py
- c2cgeoportal/scaffolds/update/CONST_alembic/main/script.py.mako
- c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/1418cb05921b_merge_1_6_and_master_branches.py
- c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/164ac0819a61_add_image_format_to_wmts_layer.py
- c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/166ff2dcc48d_create_database.py
- c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/1d5d4abfebd1_add_restricted_theme.py
- c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/20137477bd02_update_icons_url.py
- c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/32527659d57b_move_exclude_properties_from_layerv1_to_.py
- c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/415746eb9f6_changes_for_v2.py
- c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/5109242131ce_add_column_time_widget.py
- c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/53ba1a68d5fe_add_theme_to_fulltextsearch.py
- c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/54645a535ad6_add_ordering_in_relation.py
- c2cgeoportal/scaffolds/update/CONST_alembic/static/env.py
- c2cgeoportal/scaffolds/update/CONST_alembic/static/script.py.mako
- c2cgeoportal/scaffolds/update/CONST_alembic/static/versions/1da396a88908_move_user_table_to_static_schema.py
- c2cgeoportal/scaffolds/update/CONST_alembic/static/versions/3f89a7d71a5e_alter_column_url_to_remove_limitation.py
- c2cgeoportal/scaffolds/update/CONST_alembic/static/versions/5472fbc19f39_add_temp_password_column.py
- travis/squote
> Better merge between alembic branches

- c2cgeoportal/scaffolds/create/build.json_tmpl
https://github.com/Geoportail-Luxembourg/geoportailv3/issues/865
> Add export_local_property_definitions compile option

- c2cgeoportal/scaffolds/create/build.json_tmpl
https://github.com/Geoportail-Luxembourg/geoportailv3/pull/877
> Do not use checkStructDictInheritance

- .travis.yml
- c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/2b8ed8c1df94_set_layergroup_treeitem_is_as_a_primary_.py
> Add missing primary key on layergroup_treeitem

- c2cgeoportal/locale/en/LC_MESSAGES/c2cgeoportal.po
- c2cgeoportal/static/adminapp/js/Admin/checkbox.js
> The findList with url shouldn't found the metadata_url

- .travis.yml
- c2cgeoportal/scripts/c2ctool.py
- doc/developer/build_release.rst
- travis/deploy.sh
Named development release or release candidate on minor release.
> Be able to create intermediate release

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_dev-requirements.txt
This is a backport of https://github.com/Geoportail-Luxembourg/geoportailv3/pull/929.
> Prepare use of htmlmin in templatecache.mako.js

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Rebuild the templates when the instance id change

- c2cgeoportal/__init__.py
- c2cgeoportal/lib/caching.py
- c2cgeoportal/scaffolds/create/vars_+package+.yaml_tmpl
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/tests/functional/test_mapserverproxy.py
- c2cgeoportal/tests/test_caching.py
- c2cgeoportal/views/entry.py
- c2cgeoportal/views/fulltextsearch.py
- c2cgeoportal/views/layers.py
- c2cgeoportal/views/profile.py
- c2cgeoportal/views/raster.py
- doc/integrator/caching.rst
- doc/integrator/security.rst
> Add CORS headers

- c2cgeoportal/static/adminapp/js/Admin/checkbox.js
> Fix fields rename in admin interface

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Fix js compression

- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
because I didn't really understand the real consequence of the existing comment before being confronted to this problem, I think a little clarification is needed.
> clarify TILECLOUD_CHAIN disabling documentation

- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/views/entry.py
- doc/developer/webservices.rst
> Add autentication web service documentation

- Makefile
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_dev-requirements.txt
- c2cgeoportal/scaffolds/update/CONST_versions.txt
- dev-requirements.txt
- doc/integrator/install_application.rst
- setup.py
- travis/deploy.sh
Move alembic, JSTools, lingua as dev depencency
> Fix the install application process

- c2cgeoportal/scaffolds/update/CONST_packages.yaml
To be sure that we use the new package version
> Update the deploy package version

- c2cgeoportal/lib/authentication.py
> Add optional reissue_time config value

- doc/integrator/customize_ui.rst
> Add missing export in the makefile

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- travis/deploy.sh
Install wheel only on deploy
fix #1832
> Use PIP version 6.x

- doc/developer/server_side.rst
Get from https://github.com/mapfish/mapfish-print/issues/312
> Add print performance note

- c2cgeoportal/models.py
- c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/22e6dfb556de_add_description_tree_.py
- c2cgeoportal/tests/functional/test_themes.py
> Add description field in the elements of the tree

- c2cgeoportal/forms.py
- c2cgeoportal/locale/en/LC_MESSAGES/c2cgeoportal.po
- c2cgeoportal/locale/fr/LC_MESSAGES/c2cgeoportal.po
> Fix edit multi add layer

- c2cgeoportal/__init__.py
- c2cgeoportal/views/entry.py
- doc/integrator/authentication.rst
for example to allow storing json comming from a LDAP authentication.
> Remember the full user data on login

- .travis.yml
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- travis/empty-vars.mk
- travis/run-on.sh
> Test missing vars

- doc/integrator/authentication.rst
Using the code from the docs for doing LDAP, we had a stackoverflow
that was somehow recovered silently, leading to bad perfs. Here is the
stacktrace:
File "/gr_mapfish3/__init__.py", line 48, in custom_get_user_from_request
identity = authenticated_userid(request)
File "/.build/venv/lib/python2.7/site-packages/pyramid/security.py", line 77, in authenticated_userid
return request.authenticated_userid
File "/.build/venv/lib/python2.7/site-packages/pyramid/security.py", line 342, in authenticated_userid
return policy.authenticated_userid(self)
File "/.build/venv/lib/python2.7/site-packages/pyramid_multiauth/__init__.py", line 79, in authenticated_userid
userid = policy.authenticated_userid(request)
File "/.build/venv/lib/python2.7/site-packages/pyramid/authentication.py", line 90, in …
> Remove inifinite recusion when doing LDAP custom auth

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Disable redirect

- .travis.yml
- c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/22e6dfb556de_add_description_tree_.py
- c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/29f2a32859ec_merge_1_6_and_master_branches.py
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- doc/developer/build_release.rst
- travis/empty-vars.mk
Make commands visible in the doc
Remove branch label
> Merge the alembic branches

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Use curl instance of wget, remove touch

- c2cgeoportal/__init__.py
If you need it do it in the project!
> Disable GET login

- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/views/entry.py
Fix returning errors in loginresetpassword
> Fix the login view

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Do the Apache graceful after generating the tiles.conf

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scripts/c2ctool.py
Prepare the upgrade to the version 2
> Don't rebase on an unexisting branch

- c2cgeoportal/__init__.py
- c2cgeoportal/scaffolds/create/vars_+package+.yaml_tmpl
- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/views/entry.py
- doc/developer/webservices.rst
See separate commits :-)
TODO:
> Some little fix in the login views

- c2cgeoportal/scaffolds/create/print/print-apps/+package+/config.yaml.mako
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
the regexp doesnt work as expected without the .*$
> fix regexp for local tile access

- c2cgeoportal/__init__.py
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- c2cgeoportal/views/checker.py
for https://github.com/camptocamp/c2cgeoportal/issues/1848
this checker only check if there is any js error on page load.
> added phantomjs general js checker

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
Took the opportunity for switch to the version that matches the print version
we are using.
> Made the JasperReports version configurable.

- c2cgeoportal/__init__.py
- c2cgeoportal/tests/functional/__init__.py
- c2cgeoportal/tests/functional/test_request_property.py
- c2cgeoportal/tests/test_init.py
This not good for security but without this the admin interface don't works ...
> Disable the referer check for the admin interface

- travis/deploy.sh
and  don't create releases automatically
> Fix the deploy on documentation change

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
For example:
http://sourceforge.net/projects/jasperreports/files/jasperreports/JasperReports%206.1.1/jasperreports-fonts-6.1.1.jar/download
> Some sourceforge URLs have redirects.

- .gitignore
- Makefile
- c2cgeoportal/scaffolds/create/+dot+gitignore_tmpl
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- c2cgeoportal/scaffolds/update/CONST_versions.txt
- c2cgeoportal/scripts/import_ngeo_apps.py
- setup.py
> Upgrade fix

- c2cgeoportal/scaffolds/create/build.mako.json_tmpl
linked to #1707 
related to https://github.com/camptocamp/ngeo/pull/528
> Add missing gmf-themes externals

- c2cgeoportal/scaffolds/create/+package+/static-ngeo/less/mobile.less_tmpl
related to https://github.com/camptocamp/ngeo/pull/498/files -> [#1937]
> Fix the less file

- c2cgeoportal/scripts/import_ngeo_apps.py
> Remove unwanted package

- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
> Be able to build wthout node (NGEO = FALSE)

- README.rst
- doc/developer/webservices.rst
> Update the Full-Text Search webservice documentation

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Be able to manually fix setuptool and pip version

- c2cgeoportal/scaffolds/create/+package+/templates/edit.html_tmpl
- c2cgeoportal/scaffolds/create/+package+/templates/index.html_tmpl
- c2cgeoportal/scaffolds/create/+package+/templates/routing.html_tmpl
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
> Add the oldPassword field

- c2cgeoportal/forms.py
- c2cgeoportal/lib/lingua_extractor.py
- c2cgeoportal/models.py
- c2cgeoportal/tests/functional/test_themes.py
- c2cgeoportal/views/entry.py
> Fix add UI metadata

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_requirements.txt
- c2cgeoportal/scaffolds/update/CONST_requirements_windows.txt
- c2cgeoportal/scaffolds/update/CONST_versions.txt
- doc/integrator/install_application.rst
- setup.py
- `find` command must be configurable.
- Updated wheel version and added pyproj.
- Advised command interface.
- Moved some lib to non-windows requirement list only.
- Added TEST_PACKAGES condition.
> Updated setup and related documentation to build project on Windows.

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
Fix https://github.com/camptocamp/ngeo/issues/433
And required by #1764
>  Use the latest version of npm

- c2cgeoportal/__init__.py
- c2cgeoportal/scripts/import_ngeo_apps.py
> Fix layout import

- c2cgeoportal/views/checker.py
> Fix no error on 'Failed to do the printing'

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Put the right jasper report version

- c2cgeoportal/scaffolds/create/+package+/static-ngeo/less/mobile.less_tmpl
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- doc/developer/build_release.rst
- travis/doc.sh
[https://github.com/camptocamp/c2cgeoportal/issues/1937]
> Fix the release documentation / Add missing file

- doc/administrator/administrate.rst
- doc/developer/client_side.rst
- doc/integrator/customize_ui.rst
- doc/integrator/editing.rst
- doc/integrator/fulltext_search.rst
- doc/integrator/print.rst
> Fix links on cgxp documentations

- c2cgeoportal/scaffolds/create/print/WEB-INF/classes/logback.xml.mako
A typical case of false but true.
> Print logs too verbose in production mode

- c2cgeoportal/__init__.py
- c2cgeoportal/scaffolds/create/+dot+gitignore_tmpl
- c2cgeoportal/scaffolds/create/mapserver/+dot+dockerignore
- c2cgeoportal/scaffolds/create/mapserver/Dockerfile
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- c2cgeoportal/scaffolds/update/mapserver/replace_db.sh.mako
- c2cgeoportal/tests/test_init.py
- doc/integrator/docker.rst
Added the possibility to configure the DB runtime in the mapserver Docker
container.
> Add a hook possibility just after the setup

- c2cgeoportal/__init__.py
- c2cgeoportal/lib/cacheversion.py
- c2cgeoportal/tests/test_cachebuster.py
- c2cgeoportal/views/checker.py
- c2cgeoportal/views/entry.py
> Don't cache the ngeo index page

- c2cgeoportal/scaffolds/create/vars_+package+.yaml_tmpl
- doc/integrator/reset_password.rst
in the reset password message body in the .yaml scaffold and in the related documentation.
> Use correct remplacement variable 

- Makefile
- c2cgeoportal/scaffolds/create/+package+/static-ngeo/js/+package+module.js_tmpl
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Backport modifications done on ngeo

- .gitignore
- Makefile
- c2cgeoportal/__init__.py
- c2cgeoportal/scaffolds/create/+dot+gitignore_tmpl
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_packages.yaml
- c2cgeoportal/scripts/gen_version.py
- c2cgeoportal/tests/test_version.py
- c2cgeoportal/views/version.py
- setup.py
That allows to get the version that is actually running. Returns
something like that:
```json
{
"my_webapp": {
"git_hash": "09941add0f77e99fdcacf85fab65a2f61db585ee",
"version": "1.0",
"git_tag": "None"
},
"c2cgeoportal": {
"git_hash": "b359b4aab3dcbe2414e790ec6671272bd7b5dc43",
"version": "2.0.0",
"git_tag": "0.0.9eb138c1268e18fc3c22bc43bb75888a01d829ae-34"
}
}
```
> Add a /version.json URL

- Makefile
- c2cgeoportal/__init__.py
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- c2cgeoportal/stats.py
- c2cgeoportal/templates/stats.html
- c2cgeoportal/tests/test_stats.py
- doc/integrator/index.rst
- doc/integrator/statistics.rst
This feature is disabled by default. To enable it, read the integrator's guide.
> Add performance statistics.

- c2cgeoportal/scripts/import_ngeo_apps.py
And made the generated package.json more standardized (sorting the keys).
> Freeze the ngeo version in the apps.

- c2cgeoportal/scaffolds/update/+package+/static/mobile/app/controller/Main.js
With theme and layers in the permalink
> No error on application without theme

- c2cgeoportal/scripts/import_ngeo_apps.py
- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/views/entry.py
fix https://github.com/camptocamp/ngeo/issues/422
> Add full-text search groups extract

- c2cgeoportal/lib/lingua_extractor.py
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- setup.py
> Extract the raster layer in the i18n strings

- c2cgeoportal/scripts/import_ngeo_apps.py
- doc/developer/build_release.rst
> Be able to build release with ngeo

- .travis.yml
- vars.yaml
> Use hostname instead of facter

- c2cgeoportal/scaffolds/create/print/print-apps/+package+/config.yaml.mako
Print layout name are different between print configuration and
vars_+package+.yaml.
> Print layout name are not correct

- c2cgeoportal/views/shortener.py
Fix: https://github.com/camptocamp/c2cgeoportal/commit/58a984be67958a90101f8d23db0c36cf41a002db#commitcomment-16441509
> Fix the error message

- c2cgeoportal/scaffolds/create/vars_+package+.yaml_tmpl
In previous PR I corrected the template name for anonymous user but
seems I forget to change the default one for checker.
> Change template name for checker

- c2cgeoportal/scaffolds/create/print/print-apps/+package+/A4_Portrait.jrxml
Use of new DATE() method instead of TODAY() which is not a native Java
method and throw errors in some configuration.
> TODAY() is not a native Java method

- c2cgeoportal/scaffolds/create/mapserver/c2cgeoportal.map.mako
> Add tolerance for the WMS GetFeaturesInfo

- c2cgeoportal/scaffolds/update/CONST_packages.yaml
> Verify that unzip is present

- c2cgeoportal/forms.py
> Add prefix for layers in the admin interface

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
allways -> always
I just hope that I understood the whole context of this sentence...
> Typo in Makefile template

- .travis.yml
- Makefile
- c2cgeoportal/scaffolds/update/CONST_versions.txt
- setup.py
- travis/empty-make-new-project.sh
- travis/empty-make.sh
See also: https://github.com/Pylons/weberror/issues/13
@kalbermattenm this should fix your issue :-)
[#1937]
> Fix an incompatibility issue between WebError and pyramid_debugtoolbar

- c2cgeoportal/scripts/themev1tov2.py
related to: 64df44d2686f029bdf7d323db07200ffba11d667
> Fix the themev2tov1 script

- c2cgeoportal/scaffolds/update/CONST_dev-requirements.txt
To solve bug with windows ssl cert validation.
> Using git version for transifex-client

- c2cgeoportal/lib/lingua_extractor.py
- c2cgeoportal/lib/print_.py
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Gets the localisation strings from the print config

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- doc/integrator/install_application.rst
> Adapt makefile for Windows

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
Related to https://github.com/camptocamp/ngeo/commit/78414480
Fix: https://github.com/camptocamp/ngeo/issues/838
> Add missing autoprefix less argument

- .travis.yml
> Fix the Transifex deployment

- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
> Fix the debug mode

- c2cgeoportal/lib/caching.py
- c2cgeoportal/tests/test_caching.py
> Vary the cache by Origin for CORS responses

- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/tests/test_entry.py
- c2cgeoportal/views/entry.py
> Add success: true for extjs

- c2cgeoportal/scaffolds/create/+package+/templates/index.html_tmpl
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/views/entry.py
> Fix the mobile redirect for ngeo

- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/scripts/l10nv1tov2.py
- doc/integrator/internationalization.rst
- setup.py
> Add localization migration script

- c2cgeoportal/scaffolds/create/+package+/templates/routing.js_tmpl
> Fix the routing engine

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- doc/integrator/make.rst
- doc/integrator/tilegeneration.rst
Should fix #2081
Requires https://github.com/sbrunner/tilecloud-chain/pull/250
> Generate the WMTSCapabilities in c2cgeoportal

- c2cgeoportal/scaffolds/update/CONST_versions_requirements.txt
- setup.py
Requires: https://github.com/elemoine/papyrus/pull/53
> Update geojson and papyrus

- doc/integrator/windows_tools.rst
> Activate the agent forwarding

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Some fix found durring an upgrade

- doc/developer/build_release.rst
- doc/update_online.sh
Create it only on the 1.6 branch because the 2.0 and next versions will
be on GitHub :-)
> Fix the documentation generation

- c2cgeoportal/scripts/c2ctool.py
> Make apache2ctl graceful configurable

- c2cgeoportal/models.py
Fix https://github.com/camptocamp/c2cgeoportal/issues/2016
> Fix layers re-ordering when adding or removing layer to a group.

- c2cgeoportal/scripts/c2ctool.py
- doc/integrator/upgrade_application.rst.mako
> Test that the requird template vars will be present

- doc/integrator/upgrade_application.rst.mako
Title says it all
Please review (and eventually merge...)
> Note for Windows because export does not exist

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Set the transifex URL in http for Windows

- c2cgeoportal/lib/caching.py
- c2cgeoportal/scripts/c2ctool.py
- c2cgeoportal/tests/test_caching.py
> Fix the vary assignment

- doc/integrator/upgrade_application.rst.mako
Sorry... This is a left over from https://github.com/camptocamp/c2cgeoportal/pull/2191, my fault...
Please review...
> Typo in documentation

- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
fix https://github.com/camptocamp/ngeo/issues/1158
> QueryLayers as string as all other layers attributes

- c2cgeoportal/scripts/import_ngeo_apps.py
Fix: https://github.com/camptocamp/ngeo/issues/1153
> Add the new angular-sanitize JavaScript

- c2cgeoportal/scripts/l10nv1tov2.py
Should fix https://github.com/camptocamp/cartoriviera_geomapfish/issues/9
> Use node to read the JS to be stronger

- c2cgeoportal/scripts/import_ngeo_apps.py
- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/views/entry.py
fix: https://github.com/camptocamp/ngeo/issues/1154
> Make the search group unique and not null

- doc/integrator/upgrade_application.rst
> Put a real srid

- c2cgeoportal/scaffolds/update/CONST_dev-requirements.txt
- dev-requirements.txt
To get https://github.com/sbrunner/c2c.template/pull/30
> Minor c2c.template update

- c2cgeoportal/scaffolds/create/print/print-apps/+package+/config.yaml.mako
like
found unknown escape character '.'
> Fix print yaml error

- c2cgeoportal/tests/functional/test_themes.py
- c2cgeoportal/views/entry.py
Issues found by @tsauerwein that I missed in my review ...
> 2263 fixes

- c2cgeoportal/scaffolds/create/deploy/hooks/pre-restore-database.mako
fix https://github.com/camptocamp/c2cgeoportal/issues/2270
> Check if database exists before executing psql commands.

- doc/developer/webservices.rst
see: https://github.com/camptocamp/c2cgeoportal/pull/2237/files#r65681454
> Fix WMS Layer documentation

- c2cgeoportal/scaffolds/create/+package+/templates/index.html_tmpl
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
> Get the query string in the mobile URL redirect

- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/tests/functional/test_looptheme.py
- c2cgeoportal/tests/functional/test_mapserverproxy.py
- c2cgeoportal/tests/functional/test_mobile_desktop.py
- c2cgeoportal/tests/functional/test_themes.py
- c2cgeoportal/tests/functional/test_themes_mixed.py
- c2cgeoportal/views/entry.py
Related to: https://github.com/camptocamp/ngeo/issues/1248
Fix: #2277
@pgiraud @olivierSemet is it ok for you?
> Always add the mixed attribute

- requirements.txt
Make the doc generation failed ...
> Use non editable pyramid_closure

- .travis.yml
- travis/doc.sh
skip_cleanup don't seam to work :-(
> Fix the doc deploy

- doc/developer/debugging.rst
> Update the print log file

- c2cgeoportal/views/fulltextsearch.py
For example, searching "wald (genf)" was leading to an SQL error.
> Fix error 500 in fulltextsearch in case of special chars

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Fix  gjslint and jshint makefile rules

- .travis.yml
Documentation comparison or publication.
> Execute the documentation only on the main repository.

- c2cgeoportal/lib/wmstparsing.py
- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/tests/functional/test_themes_time.py
- c2cgeoportal/views/entry.py
Add time informations test
fix: #2278
> Put the time information on each layer in mixed group

- c2cgeoportal/tests/functional/test_layers.py
- c2cgeoportal/views/layers.py
Did you know that adding unit tests can actually help you finding bugs ?
> Add tests for the feature create/update logging

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scripts/c2ctool.py
and optionally all other changes done in the create template.
Faster upgrade if the changelog is empty
fix #2276
> Add upgrade steps to get the changes done in the ngeo application

- c2cgeoportal/scripts/import_ngeo_apps.py
Use 2 spaces indent and add a final new line
> Better package.json formating

- c2cgeoportal/scaffolds/create/+dot+jshintrc
- c2cgeoportal/scaffolds/update/+dot+eslintrc_tmpl
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Replace jshint and gjslint with eslint

- doc/administrator/administrate.rst.mako
- doc/integrator/ngeo.rst
- vars.yaml
> Update the documentation related to the layers

- .travis.yml
- doc/integrator/upgrade_application.rst.mako
- travis/doc.sh
> Typo, Fix doc

- c2cgeoportal/scaffolds/create/+dot+travis.yml
https://docs.travis-ci.com/user/database-setup/#PostgreSQL
> Simplify database creating in .travis.yml

- Makefile
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- doc/integrator/create_application.rst
- doc/integrator/make.rst
Add doc about using make vars in yaml vars
> Use export instanceof ENVIRONMENT_VARS

- c2cgeoportal/scripts/import_ngeo_apps.py
fix https://github.com/camptocamp/ngeo/issues/1409
> Integrate background-layer-button image.

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- doc/integrator/install_application.rst
#2357 but in the origin remote (instead of the mine): avoids travis build issues
> Create a makefile variable for the modwsgi user

- c2cgeoportal/lib/caching.py
- c2cgeoportal/scaffolds/update/CONST_versions_requirements.txt
- setup.py
> Upgrade dogpile.cache

- c2cgeoportal/views/shortener.py
> Add allowed hosts configuration

- c2cgeoportal/__init__.py
- c2cgeoportal/lib/__init__.py
- c2cgeoportal/scaffolds/create/vars_+package+.yaml_tmpl
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
Thant's don't works with the debug toolbar
Update the documentation
> Don't add the MultiDomainStaticURLInfo when it's not needed

- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/scripts/c2ctool.py
Replaced by CONST_create_template
> On Upgrade don't create the create scaffold in /tmp

- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/tests/functional/test_themes_layermultinameerror.py
- c2cgeoportal/tests/functional/test_themes_metadata.py
- c2cgeoportal/tests/functional/test_themes_mixed.py
- c2cgeoportal/tests/functional/test_themes_nameerror.py
- c2cgeoportal/tests/functional/test_themes_time.py
- c2cgeoportal/views/entry.py
- setup.cfg
fix #2361, https://github.com/camptocamp/ngeo/issues/1504
> Add more themes errors

- c2cgeoportal/scaffolds/create/vars_+package+.yaml_tmpl
- c2cgeoportal/views/shortener.py
- doc/developer/webservices.rst
> Be able to have a user message in the short URL email

- c2cgeoportal/scaffolds/update/CONST_versions.txt
> Fix dogpile.cache to right version

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scripts/theme2fts.py
- Use <package> instead of demo
- Use client instead of server
- Generate the requires mo files
fix: https://github.com/camptocamp/ngeo/issues/1506
> Fix the i18n in the theme 2 fts import script

- doc/administrator/administrate.rst.mako
> Update the documentationabout the layer v1 and v2

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Remove the --sort-by-file argument, it will make unnecessary changes

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Use sourceforge.mirrorservice.org instead of sourceforge.net

- c2cgeoportal/scripts/l10nv1tov2.py
> Add escape before the quote in the messsage

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scripts/c2ctool.py
> Don't use the version argument after the step one.

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_versions_requirements.txt
> Add new DOCKER environment variable

- c2cgeoportal/scaffolds/create/print/print-apps/+package+/results.jrxml
> Add the feature type name in the print results

- doc/integrator/caching.rst
> Use the "New" configuration files

- c2cgeoportal/lib/filter_capabilities.py
Fix error like
⇝ UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 16: ordinal not in range(128)
> Fix utf8 error on GetCapabilities

- c2cgeoportal/lib/__init__.py
- doc/administrator/administrate.rst.mako
- doc/administrator/editing.rst
- doc/developer/server_side.rst
- doc/developer/webservices.rst
- doc/integrator/cgxp.rst.mako
- doc/integrator/cluster.rst
- doc/integrator/docker.rst
- doc/integrator/fulltext_search.rst.mako
- doc/integrator/mobile.rst
- doc/integrator/ngeo.rst
- doc/integrator/print.rst.mako
- doc/integrator/upgrade_application.rst.mako
> Add OGC server, Metadata and functionalities documentation

- c2cgeoportal/lib/lingua_extractor.py
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Get the column of the editable layers

- c2cgeoportal/__init__.py
- c2cgeoportal/scaffolds/create/apache/wsgi.conf.mako
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
> Don't hard code the default interface name

- c2cgeoportal/scaffolds/create/vars_+package+.yaml_tmpl
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
The value will now be used ba the desktop and mobile interfaces
> Rename mobile_default_theme functionality to default_theme

- c2cgeoportal/scaffolds/create/+package+/static-ngeo/js/+package+module.js_tmpl
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scripts/import_ngeo_apps.py
> Fix the template cache for components based structure

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scripts/theme2fts.py
- Correctly get config
- Run on all interfaces
- Add in the Make file to have the dependencies
Should fix #2444
> Fix the theme to full-text search

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scripts/import_ngeo_apps.py
Should fix https://github.com/camptocamp/ngeo/issues/1718
> Add floatThead, be more generic

- c2cgeoportal/lib/dbreflection.py
- c2cgeoportal/lib/lingua_extractor.py
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scripts/import_ngeo_apps.py
- c2cgeoportal/tests/functional/test_dbreflection.py
- c2cgeoportal/views/layers.py
> Directly get the editing column from the database

- c2cgeoportal/tests/functional/c2cgeoportal_test.map.mako
- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/tests/functional/test_themes_scale.py
- c2cgeoportal/tests/test_entry.py
- c2cgeoportal/views/entry.py
> Fix resolutions hints

- c2cgeoportal/views/entry.py
- travis/no-make-error.sh
> Fix the capabilities content type for QGIS and WMS 1.3

- c2cgeoportal/__init__.py
- c2cgeoportal/forms.py
- c2cgeoportal/lib/lingua_extractor.py
- c2cgeoportal/models.py
- c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/b60f2a505f42_remame_uimetadata_to_metadata.py
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- c2cgeoportal/scripts/themev1tov2.py
- c2cgeoportal/tests/functional/test_layers.py
- c2cgeoportal/tests/functional/test_themes.py
- c2cgeoportal/tests/functional/test_themes_metadata.py
- c2cgeoportal/tests/functional/test_themes_mixed.py
- c2cgeoportal/views/entry.py
- c2cgeoportal/views/layers.py
- doc/developer/server_side.rst
- doc/developer/webservices.rst
- doc/integrator/cluster.rst
> Rename UIMetadata to Metadata

- .travis.yml
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- travis/no-make-error.sh
Should fix: https://github.com/camptocamp/c2cgeoportal/issues/2472
(Merge on 2.0)
> Set url for Closure Linter

- .gitignore
- Makefile
- c2cgeoportal/scripts/import_ngeo_apps.py
> Add the missing contextualdata.html template

- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
> Remove dupplicated queryLayers

- c2cgeoportal/views/entry.py
@gberaudo it should fix the editing interface
> Be able to use the CGXP interface without external server

- c2cgeoportal/scripts/themev1tov2.py
fix https://github.com/camptocamp/c2cgeoportal/issues/2499
> OGCServer url can not be null, OGCServer name must be unique

- c2cgeoportal/scaffolds/update/CONST_print_url
> Update the print from 3.3 to 3.6

- c2cgeoportal/lib/__init__.py
- c2cgeoportal/tests/functional/test_themes_metadata.py
- doc/integrator/customise.rst
> Be able to have json in metadata

- Makefile
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_optional-requirements.txt
> Put the fixed versions in a separate file

- .travis.yml
- c2cgeoportal/pyramid_.py
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/ee25d267bf46_main_interface_desktop.py
- c2cgeoportal/scripts/create_demo_theme.py
- c2cgeoportal/scripts/import_ngeo_apps.py
- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/tests/functional/test_looptheme.py
- c2cgeoportal/tests/functional/test_themes.py
- c2cgeoportal/tests/functional/test_themes_layermultinameerror.py
- c2cgeoportal/tests/functional/test_themes_nameerror.py
- c2cgeoportal/tests/functional/test_themes_scale.py
- c2cgeoportal/tests/functional/test_themes_time.py
- c2cgeoportal/views/entry.py
- doc/integrator/create_application.rst
- doc/integrator/interface.rst
- setup.py
- travis/create-new-project.sh
> Clarify the interface documentation an migration.

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_dev-fixversions.txt
- c2cgeoportal/scaffolds/update/CONST_dev-requirements.txt
> Move flake8 to a fixed version file

- .gitignore
- Makefile
> Fix images folder name

- c2cgeoportal/views/layers.py
> Remove cache on layer metadata

- c2cgeoportal/scripts/c2ctool.py
> Remove CONST_ and package.json from the create package diff

- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- c2cgeoportal/scripts/themev1tov2.py
Related to https://github.com/camptocamp/ngeo/pull/1929
> Solve some metadata issues

- c2cgeoportal/scripts/themev1tov2.py
fix https://github.com/camptocamp/c2cgeoportal/issues/2578#issuecomment-252190597
> Don't create OGC server for WMTS layers

- doc/administrator/administrate.rst.mako
Follow up of https://github.com/camptocamp/c2cgeoportal/pull/2566.
> Fix the fix

- c2cgeoportal/scaffolds/create/+package+.mk_tmpl
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
> Better messages around the visible host name

- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
> Add some notes about keeping the CGXP interface

- c2cgeoportal/scaffolds/update/CONST_versions_requirements.txt
> Fix pykwalify version, used PyYAML version required by pykwalify

- doc/index.rst.mako
> Update the main documentation page links

- c2cgeoportal/views/layers.py
Probably introduce by merge from 2.0
> Fix layer exclude

- c2cgeoportal/scaffolds/create/print/print-apps/+package+/A4_Landscape.jrxml
Fix: #2613
Must be reported in 1.6+ branches
> Print template A4L - Don't compare boolean with int

- c2cgeoportal/lib/lingua_extractor.py
> Interpret the mako template to avoid the lingua warning messages

- c2cgeoportal/models.py
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/32b21aa1d0ed_merge_e004f76e951a_and_e004f76e951a_.py
- c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/7d271f4527cd_add_layer_column_in_layerv1_table.py
- c2cgeoportal/scripts/create_demo_theme.py
- c2cgeoportal/scripts/manage_users.py
- c2cgeoportal/scripts/treeitem_uniquename.py
- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/views/entry.py
- doc/developer/server_side.rst
- setup.py
> Add layer column for V1 layers

- c2cgeoportal/pyramid_.py
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- c2cgeoportal/views/checker.py
- c2cgeoportal/views/printproxy.py
- doc/integrator/make.rst
- doc/integrator/requirements.rst
This reverts commit a50785fdbed902387ad972e1ba36a1115190b3aa.
fix #2611
> Revert "Remove print v2 support"

- c2cgeoportal/lib/lingua_extractor.py
> Get i18n from the full-text search layer_name

- c2cgeoportal/views/shortener.py
fix https://github.com/camptocamp/ngeo/issues/1986
> Limit the length of the URL

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- travis/create-new-project.sh
> Fix c2c.template dependencies, the -print hide some results

- c2cgeoportal/lib/lingua_extractor.py
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- c2cgeoportal/scripts/import_ngeo_apps.py
- c2cgeoportal/views/checker.py
fix https://github.com/camptocamp/ngeo/issues/1968
> Add mobile redirect

- doc/administrator/administrate.rst.mako
I do not know if it is clearer now... But in the current state, it was quite obscure for me...
Feel free to merge or close if not ok...
> Clarify the layer stuff

- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
> Fix missing rename of app.js into desktop.js

- c2cgeoportal/scripts/themev1tov2.py
> This block will try to commit the no more valid new layer

- c2cgeoportal/scaffolds/update/CONST_versions_requirements.txt
> Remove the dupplicated psycopg2 version fix

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
Fix: https://github.com/camptocamp/c2cgeoportal/issues/2670
> Set src for external ngeo component

- c2cgeoportal/lib/__init__.py
- c2cgeoportal/lib/authentication.py
- c2cgeoportal/lib/filter_capabilities.py
- c2cgeoportal/lib/raster/shputils.py
- c2cgeoportal/pyramid_.py
- c2cgeoportal/scripts/themev1tov2.py
- c2cgeoportal/stats.py
- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/tests/functional/test_fulltextsearch.py
- c2cgeoportal/tests/functional/test_mobile_desktop.py
- c2cgeoportal/tests/functional/test_themes.py
- c2cgeoportal/tests/functional/test_themes_dimensions.py
- c2cgeoportal/views/entry.py
- c2cgeoportal/views/export.py
- c2cgeoportal/views/layers.py
- c2cgeoportal/views/mapserverproxy.py
- c2cgeoportal/views/resourceproxy.py
- c2cgeoportal/views/version.py
see: https://www.quantifiedcode.com/app/project/gh:camptocamp:c2cgeoportal
> Quantifiedcode 

- c2cgeoportal/lib/dbreflection.py
- c2cgeoportal/models.py
- c2cgeoportal/tests/__init__.py
- c2cgeoportal/tests/functional/__init__.py
- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/tests/functional/test_mapserverproxy.py
- c2cgeoportal/tests/functional/test_mobile_desktop.py
- c2cgeoportal/tests/functional/test_themes.py
- c2cgeoportal/tests/functional/test_themes_dimensions.py
- c2cgeoportal/tests/functional/test_themes_editing.py
- c2cgeoportal/tests/functional/test_themes_layermultinameerror.py
- c2cgeoportal/tests/functional/test_themes_mixed.py
- c2cgeoportal/tests/functional/test_themes_nameerror.py
- c2cgeoportal/tests/functional/test_themes_scale.py
- c2cgeoportal/tests/functional/test_themes_time.py
- c2cgeoportal/tests/test_entry.py
- c2cgeoportal/views/entry.py
- c2cgeoportal/views/proxy.py
This pull request automatically fixes all occurrences of the following issue:
Issue type: [Avoid mutable default arguments](https://www.quantifiedcode.com/app/issue_class/3P0qV6OB)
Issue details: [https://www.quantifiedcode.com/app/project/gh:camptocamp:c2cgeoportal?groups=code_patterns/%3A3P0qV6OB](https://www.quantifiedcode.com/app/project/gh:camptocamp:c2cgeoportal?groups=code_patterns/%3A3P0qV6OB)
To adjust the commit message or the actual code changes, just [rebase](https://git-scm.com/docs/git-rebase) or [cherry-pick](https://git-scm.com/docs/git-cherry-pick) the commits.
For questions or feedback reach out to cody@quantifiedcode.com.
Legal note: We won't claim any copyrights on the code changes.
Cheers,
[Cody - Your code quality bot](https://www.quantifiedcode.com/cody)
> Fix "Avoid mutable default arguments" issue

- c2cgeoportal/views/printproxy.py
> The get_functionality don't use anymore the config

- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
> Add the missing components

- c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/e004f76e951a_add_missing_not_null.py
> Fill null value with default values to avoid errors

- c2cgeoportal/lib/lingua_extractor.py
> Fix the WMTS layer query attribute collection

- .gitignore
- Makefile
- c2cgeoportal/scripts/c2ctool.py
- c2cgeoportal/scripts/import_ngeo_apps.py
> Update the package.json, not overwrite it

- c2cgeoportal/lib/lingua_extractor.py
> Don't get a fatal error on parsing a wrong document

- c2cgeoportal/lib/caching.py
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_config-schema.yaml
- c2cgeoportal/scaffolds/update/CONST_dev-requirements.txt
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- c2cgeoportal/scaffolds/update/CONST_versions_requirements.txt
- c2cgeoportal/tests/functional/test_layers.py
- c2cgeoportal/tests/functional/test_mapserverproxy.py
- c2cgeoportal/views/entry.py
- c2cgeoportal/views/geometry_processing.py
- c2cgeoportal/views/layers.py
- c2cgeoportal/views/pdfreport.py
- doc/integrator/legacy_querier.rst
- doc/integrator/pdfreport.rst
- doc/integrator/security.rst
Use YAML capabilities instance of manual defaults
> Validate that the `.build/config.yaml` file is valid 

- c2cgeoportal/scripts/l10nv1tov2.py
Fix #2717
@sbrunner I'm 100% sure, with this, the wrote string will be `thème` and not `th\xc3\xa8me` ? right ?
> Unicode string before encoding it

- c2cgeoportal/forms.py
- c2cgeoportal/models.py
- c2cgeoportal/scripts/import_ngeo_apps.py
- c2cgeoportal/tests/functional/__init__.py
> Admin dimension

- Makefile
- c2cgeoportal/scaffolds/update/CONST_requirements.txt
- c2cgeoportal/scaffolds/update/CONST_requirements_windows.txt
- c2cgeoportal/scaffolds/update/CONST_versions_requirements.txt
- docker/test-mapserver/mapserver.map.mako
- travis/doc.sh
- travis/test-new-project.sh
Waiting for pyramid-closure 1.1.0
> Build the doc in Docker

- c2cgeoportal/scripts/c2ctool.py
> Better upgrade prompt

- c2cgeoportal/scaffolds/update/CONST_alembic/main/script.py.mako
- c2cgeoportal/scaffolds/update/CONST_alembic/static/versions/9268a1dffac0_add_trigger_to_be_able_to_coorectly_.py
> Add trigger to be able to correctly change the role name

- .travis.yml
- c2cgeoportal/tests/functional/__init__.py
- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/tests/functional/test_themes_edit_columns.py
- c2cgeoportal/tests/functional/test_themes_editing.py
- c2cgeoportal/views/entry.py
- c2cgeoportal/views/layers.py
- doc/developer/server_side.rst
- doc/developer/webservices.rst
- docker/test-db/20_init.sql
- docker/test-db/Dockerfile
- travis/vars.yaml
- vars.yaml
It is possible to test under: https://gmf-test.sig.cloud.camptocamp.net/marionb20/ under `edit_columns`
> GR Objectediting

- c2cgeoportal/scripts/themev1tov2.py
> Set a default image type for WMTS layers

- c2cgeoportal/scripts/c2ctool.py
Partially fix: #2756 
Fix: *4-A) Error when checkers don't pass*
> Use bracket in format function

- c2cgeoportal/scaffolds/create/development.ini.mako_tmpl
- c2cgeoportal/scaffolds/create/production.ini.mako_tmpl
- c2cgeoportal/scripts/create_demo_theme.py
- c2cgeoportal/scripts/manage_users.py
- c2cgeoportal/scripts/theme2fts.py
- c2cgeoportal/scripts/themev1tov2.py
- c2cgeoportal/scripts/treeitem_uniquename.py
> Some logging fixies

- c2cgeoportal/lib/lingua_extractor.py
- c2cgeoportal/scaffolds/create/deploy/hooks/post-create
- c2cgeoportal/scaffolds/create/deploy/hooks/post-restore-code
- c2cgeoportal/scaffolds/create/deploy/hooks/pre-restore-database.mako
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
Actually the code deploy depends on the database, and the inverse also...
> Be able to deploy the application the first time

- c2cgeoportal/scripts/themev1tov2.py
> Fix unicode warnings

- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
Just some changes in CONST_CHANGELOG.txt_tmpl (in order for me not to waste everybody's time...)
> Use scripts instead of bin for Windows

- c2cgeoportal/scripts/themev1tov2.py
> Fill the URL before setting the restrictionareas

- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
> Add metadata and functionnalities for filters

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
Partially fix https://github.com/camptocamp/ngeo/issues/2264
> Add the missing ngeo l10n files

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Add missing escape

- doc/developer/webservices.rst
- doc/integrator/filter.rst
- doc/integrator/index.rst
- doc/integrator/legacy.rst
Fix: #2731 
And related to #2651
> Some doc additions for filters

- doc/integrator/ngeo.rst
> Add doc about directive and mainCtrl

- c2cgeoportal/lib/lingua_extractor.py
- c2cgeoportal/pyramid_.py
- c2cgeoportal/views/layers.py
> Extract enum attributes values for i18n

- c2cgeoportal/scaffolds/update/CONST_versions_requirements.txt
- docker/build/dev-requirements.txt
> Remove unused dogpile.core package

- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/scripts/c2ctool.py
- travis/create-new-project.sh
> Some deploy fixies

- c2cgeoportal/scripts/c2ctool.py
> Get better error message when the subcommand failed

- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
For specs https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%232652-Time-in-Query
> Add timeattribute for query

- c2cgeoportal/lib/lingua_extractor.py
> Add WMS group support in i18n

- c2cgeoportal/forms.py
> Add the missing parent role name

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
To have different environment
fix #2862
> Be able to change the postfix name of the l10n files

- c2cgeoportal/scripts/import_ngeo_apps.py
- doc/integrator/legacy_cgxp.rst.mako
fix https://github.com/camptocamp/ngeo/issues/2407
> Fix the mobile redirect

- c2cgeoportal/scripts/themev1tov2.py
fix https://github.com/camptocamp/ngeo/issues/2358
> Fix the identifierAttributeField case

- c2cgeoportal/scripts/import_ngeo_apps.py
Complement of https://github.com/camptocamp/ngeo/pull/2428
to fix https://github.com/camptocamp/ngeo/issues/2354
> Replace the URL in the tablet redirect

- .gitignore
- doc/integrator/create_application.rst
> [doc] Make build with docker-run

- c2cgeoportal/scripts/import_ngeo_apps.py
For: https://github.com/camptocamp/ngeo/issues/2354
Look also at: https://github.com/camptocamp/ngeo/pull/2457
> No redirect on switch to desktop app from mobile

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Compile lib file-saver

- c2cgeoportal/views/fulltextsearch.py
- doc/integrator/fulltext_search.rst.mako
> Change fts to keep some characters

- c2cgeoportal/lib/lingua_extractor.py
> Use unicode string to avoid encoding issues

- c2cgeoportal/scripts/import_ngeo_apps.py
> Better code and nameing

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Fix #2871 - remove existing pot files (for Windows)

- c2cgeoportal/scripts/themev1tov2.py
Fix https://github.com/camptocamp/ngeo/issues/2364
> Use the right name for the layer icon URL

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Be able to don't have any l10n on server part

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
The version was missing from the generated file.
> Fix build from scratch

- doc/integrator/fulltext_search.rst.mako
fix https://github.com/camptocamp/ngeo/issues/2385#issuecomment-294705730
> Add SQL example to add Fulltext-search element from layer cadastre

- .travis.yml
- c2cgeoportal/lib/__init__.py
- c2cgeoportal/lib/filter_capabilities.py
- c2cgeoportal/models.py
- c2cgeoportal/tests/functional/__init__.py
- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/tests/functional/test_layers.py
- c2cgeoportal/tests/functional/test_mapserverproxy.py
- c2cgeoportal/tests/functional/test_mapserverproxy_group.py
- c2cgeoportal/tests/functional/test_themes.py
- c2cgeoportal/tests/functional/test_themes_dimensions.py
- c2cgeoportal/tests/functional/test_themes_layermultinameerror.py
- c2cgeoportal/tests/functional/test_themes_metadata.py
- c2cgeoportal/tests/functional/test_themes_mixed.py
- c2cgeoportal/tests/functional/test_tinyowsproxy.py
- c2cgeoportal/views/entry.py
- c2cgeoportal/views/layers.py
- c2cgeoportal/views/mapserverproxy.py
- c2cgeoportal/views/ogcproxy.py
- c2cgeoportal/views/tinyowsproxy.py
> Update the OGC layer filter for the GeoMapFish layers V2

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_config-schema.yaml
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- c2cgeoportal/tests/functional/__init__.py
- c2cgeoportal/views/proxy.py
- doc/integrator/docker.rst
Fix https://jira.camptocamp.com/browse/GSTICH-60
> Have a configurable list of server that forvard the Host header

- c2cgeoportal/lib/filter_capabilities.py
> Lowercase layer to filter them

- c2cgeoportal/views/entry.py
This follow https://github.com/camptocamp/tilecloud-chain/pull/276.
We need this for aeroportdelyon_sig.
> Allow + sign in URL_PART_RE

- c2cgeoportal/scaffolds/create/print/print-apps/+package+/A3_Landscape.jrxml
- c2cgeoportal/scaffolds/create/print/print-apps/+package+/config.yaml.mako
It was wrongly using an A4 page format.
> Using correct page format for A3 landscape print template.

- .travis.yml
Then do a 1.6.13dev1 version because of reason
> Fix travis - deploy gettext

- c2cgeoportal/scaffolds/update/testDB/11-schemas.sql.mako
- c2cgeoportal/scaffolds/update/testDB/Dockerfile.mako
- docker/test-db/10_init.sql
- docker/test-db/Dockerfile
- docker/test-external-db/10_init.sql
- docker/test-external-db/Dockerfile
> Use camptocamp/postgis instance of camptocamp/postgresql docker image

- c2cgeoportal/forms.py
- fixversions.txt
- setup.py
LayerGroup, RestrictionArea, Theme edit
> Fix the admin interface

- c2cgeoportal/scripts/themev1tov2.py
> Add missing description

- c2cgeoportal/static/adminapp/js/Admin/checkbox.js
Don't disable the public and the restriction area fields
fix #2943
> Be able to have some external layerv1 only for some users

- .gitignore
- .tx/config.mako
- Makefile
fix https://github.com/camptocamp/ngeo/issues/2359
> Add some localisation in the default localisation file

- c2cgeoportal/scripts/c2ctool.py
> Removes the CONST_create_template folder only if he exists

- c2cgeoportal/scripts/treeitem_uniquename.py
> Accept unicode layer name

- c2cgeoportal/scaffolds/update/CONST_optional-requirements.txt
- c2cgeoportal/scaffolds/update/CONST_versions_requirements.txt
> Use the new version of tilecloud

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
To be able to use https://github.com/camptocamp/ngeo/pull/2667
Fix https://github.com/camptocamp/ngeo/issues/2660
> Be able to add custom externs

- c2cgeoportal/scaffolds/update/CONST_optional-requirements.txt
- c2cgeoportal/scaffolds/update/CONST_versions_requirements.txt
This reverts commit 381ffeb3c8da55f9905fcf6a21e90159ceddc985.
> Revert "Use the new version of tilecloud"

- .dockerignore
- docker/build/Dockerfile
- docker/build/dev-requirements.txt
- docker/build/fixversions.txt
- setup.py
To avoid this kind of unwanted update: https://github.com/camptocamp/c2cgeoportal/pull/2977/files
> Use the fixed version also in the Docker build package

- c2cgeoportal/scaffolds/update/CONST_config-schema.yaml
> Update the configuration check

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Removes the \n on windows

- c2cgeoportal/views/checker.py
Fix https://github.com/camptocamp/cartoriviera_geomapfish/issues/23
> Fix the checker on non Docker project

- c2cgeoportal/scripts/themev1tov2.py
FIX #3001 
Any idea of what that was @sbrunner ?
(must be also reported in 2.2)
> themev1tov2: Adapt to new model of layergroup_treeitem

- doc/integrator/install_application.rst
> Remove the CGXP checkout

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
Fix https://github.com/camptocamp/ngeo/issues/2785
> Add missing dependencies files

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_versions_requirements.txt
- docker/build/dev-requirements.txt
See also: https://github.com/camptocamp/c2c.template/pull/40
> Use a json cache to be faster

- Makefile
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- travis/empty-make.sh
> Fix touchback transifexrc

- c2cgeoportal/scripts/c2ctool.py
> Use localhost to call checkers upgrade step 5

- c2cgeoportal/views/pdfreport.py
> Fix pdf report

- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
> Fix the case of the copy to metadata

- doc/administrator/administrate.rst.mako
Metadata will be easier to use with that
> Precise usage of metadata

- c2cgeoportal/models.py
- c2cgeoportal/scripts/themev1tov2.py
> Be able to set the server type when migrating the theme

- c2cgeoportal/pyramid_.py
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/views/pdfreport.py
- doc/integrator/pdfreport.rst
Fix: https://github.com/camptocamp/baselstadt_mapbs/issues/104
> Be able to have multiple id values for PDF reports

- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
Part of: https://github.com/camptocamp/ngeo/pull/2871
(must be also reported in 2.2 and upper)
> geometry_validation metadata is a boolean

- Makefile
- c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/6d87fdad275a_convert_metadata_to_the_right_case.py
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- c2cgeoportal/tests/functional/test_layers.py
- c2cgeoportal/views/layers.py
- doc/administrator/editing.rst
linked to https://github.com/camptocamp/cgxp/pull/1121
> Convert the metadata to the right case

- c2cgeoportal/scripts/import_ngeo_apps.py
- doc/integrator/legacy_cgxp.rst.mako
See http://caniuse.com/#feat=matchmedia
fixes #3033
> Redirect to mobile if the screen is no more than 1024px wide

- c2cgeoportal/models.py
- c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/d8ef99bc227e_be_able_to_delete_a_linked_functionality.py
- c2cgeoportal/tests/functional/alembic_static.ini.mako
> Be able to delete a linked functionality

- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
> Add missing excludeProperties metadata

- c2cgeoportal/tests/functional/test_themes_dimensions.py
- c2cgeoportal/views/entry.py
> Be able to put special chars in WMS dimensions

- commons/acceptance_tests/conftest.py
- commons/acceptance_tests/test_roles.py
- commons/acceptance_tests/test_users.py
- commons/c2cgeoportal_commons/tests/__init__.py
- commons/pytest.ini
remove pydevd import
using pytest exclude using pyunit
> make make test work in common

- .travis.yml
- dev-requirements.txt
> Set travis dist to precise

- admin/Makefile
- admin/acceptance_tests/__init__.py
- admin/acceptance_tests/conftest.py
- admin/acceptance_tests/learn_test.jinja2
- admin/acceptance_tests/learn_test.py
- admin/acceptance_tests/role_test.py
- admin/acceptance_tests/user_test.py
- admin/c2cgeoportal_admin/__init__.py
- admin/c2cgeoportal_admin/routes.py
- admin/c2cgeoportal_admin/views/roles.py
- admin/c2cgeoportal_admin/views/users.py
- admin/development.ini
- admin/pytest.ini
- admin/requirements.txt
- admin/setup.py
- commons/Makefile
- commons/c2cgeoportal_commons/locale/en/LC_MESSAGES/c2cgeoportal_commons.po
- commons/c2cgeoportal_commons/locale/fr/LC_MESSAGES/c2cgeoportal_commons.po
- commons/c2cgeoportal_commons/models/main.py
- commons/requirements.txt
- commons/setup.py
> User and role, grid and detail

- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
> Add changelog steps for vars file

- Dockerfile
- c2cgeoportal/scaffolds/nondockerupdate/+dot+upgrade.yaml_tmpl
- c2cgeoportal/scaffolds/update/+dot+upgrade.yaml_tmpl
- c2cgeoportal/scripts/c2cupgrade.py
- docker/build/Dockerfile
- travis/test-upgrade-convert.sh
- travis/v22-project.yaml
Better move message
No unneeded message
Use the unmanaged_files in the upgrade tests
Some fix
> c2cupgrade improvements

- .travis.yml
Should fix https://github.com/camptocamp/c2cgeoportal/issues/3164#issuecomment-336828496
> Simplify and fix publish

- c2cgeoportal/scripts/theme2fts.py
Fix: #3178
(Must also be reported on 2.2, master)
> Fix unicode issues in theme2fts script

- doc/integrator/filter.rst
- doc/integrator/internationalization.rst
Fixes https://github.com/camptocamp/c2cgeoportal/issues/3185
> fix syntax of code display

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
> Fix xapi build

- c2cgeoportal/scaffolds/update/CONST_print_url
- c2cgeoportal/scaffolds/update/print/Dockerfile
> Upgrade the print to version 3.10.4

- doc/administrator/administrate.rst
- doc/integrator/configuration.rst
- doc/integrator/features.rst
- doc/integrator/legacy_advanced.rst
- doc/integrator/legacy_cgxp.rst
- doc/integrator/ngeo.rst
- doc/integrator/ngeo_new_interface.rst
adding additional infos from GEO-306
> [doc] complete the information on adding a new user interface

- doc/builddoc.rst
- doc/integrator/intranet.rst
- doc/integrator/upgrade_application.rst.mako
> [doc, 2.2] doc build instructions and add note for upgrade

- c2cgeoportal/scaffolds/update/CONST_dev-requirements.txt
- docker/build/dev-requirements.txt
for issue https://github.com/camptocamp/c2cgeoportal/issues/2723
(when using 2.2 - master branch has already updated)
> update transifex version in 2.2

- admin/tests.ini
> Fix travis build on master

- c2cgeoportal/tests/functional/test_themes_private.py
- c2cgeoportal/views/entry.py
fix  https://github.com/camptocamp/ngeo/issues/3028
> Fix private WMTS layer

- admin/requirements.txt
- commons/requirements.txt
> target latest c2cgeoform 'tag'

- admin/requirements.txt
- commons/requirements.txt
c2cgeoform adaption into account. (cf. roles_nn)
> model have to be modified in order to take last

- admin/acceptance_tests/left_menu_test.py
- admin/acceptance_tests/role_test.py
- admin/acceptance_tests/user_test.py
- admin/c2cgeoportal_admin/views/roles.py
- admin/c2cgeoportal_admin/views/users.py
- admin/requirements.txt
activate delete.
relates to https://github.com/camptocamp/c2cgeoform/pull/123.
> use http verbs instead of action

- doc/administrator/editing.rst
- doc/integrator/configuration.rst
- doc/integrator/filter.rst
- doc/integrator/multiple_databases.rst
for issue #3163 
(same PR as previously, retrying for CI technical reasons)
> Doc multiple db

- admin/acceptance_tests/role_test.py
- admin/acceptance_tests/user_test.py
- admin/c2cgeoportal_admin/views/roles.py
- admin/c2cgeoportal_admin/views/users.py
- admin/requirements.txt
await test datas from anaother pr
used c2cgeoform version miss column name translation as probably
of no use, disable test targetting this functionnality
> add description, functionnalities, restrictionareas column

- admin/Makefile
- admin/acceptance_tests/conftest.py
- admin/acceptance_tests/learn_test.py
- admin/acceptance_tests/left_menu_test.py
- admin/acceptance_tests/role_test.py
- admin/acceptance_tests/user_test.py
- admin/c2cgeoportal_admin/views/roles.py
- admin/c2cgeoportal_admin/views/users.py
- admin/requirements-dev.txt
- admin/requirements.txt
- admin/setup.py
- admin/tests.ini
- commons/c2cgeoportal_commons/models/main.py
- commons/requirements.txt
- docker/build/requirements.txt
Note that this also refactor requirements between commons and admin to avoid having two different references to c2cgeoform.
> [admin] Add CheckboxLists in role form

- c2cgeoportal/lib/lingua_extractor.py
> Add foreign key into lingua extractor

- admin/acceptance_tests/user_test.py
- admin/c2cgeoportal_admin/views/users.py
- commons/c2cgeoportal_commons/models/static.py
We also remove the redundant `test_view_index` test for User
> [admin] Add role column to user grid

- geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl
Also, merge OL_JS_FILES and NGEO_JS_FILES together.
> Add OL-Cesium files to build.js dependencies

- c2cgeoportal/tests/functional/test_layers.py
- c2cgeoportal/views/layers.py
- doc/developer/webservices.rst
> [WIP] Postgresql errors

- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
For... #3265 ?
That's for 2.1, and my issue is for 2.2 (because there is more occurrence in 2.2).
@sbrunner do you want another issue for this PR ?
> Better dobble-points in vars_tmpl

- c2cgeoportal/tests/functional/test_layers.py
- c2cgeoportal/views/layers.py
- doc/developer/webservices.rst
Fix coverage
Remove not required database error,
add logs to file.
> [WIP] Add test for coverage tests

- doc/integrator/ngeo_new_interface.rst
Corrections as found by @marionb when doing https://jira.camptocamp.com/browse/GSSZ2-4
> [doc] improve description of how to add new interface

- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
For #3265 
Need also PR 2.1 #3267 
And both should applied on the master
> Better dobble-points in vars_tmpl (2.2)

- c2cgeoportal/lib/lingua_extractor.py
> Add WMS layer names to i18n strings

- admin/acceptance_tests/layers_wms_test.py
- admin/c2cgeoportal_admin/views/layers_wms.py
- admin/c2cgeoportal_admin/views/roles.py
Use subqueryload to reduce the number of requests to database
> Admin subqueryload

- c2cgeoportal/views/entry.py
Fix: #3287
Tested (one week only) within https://jira.camptocamp.com/projects/GEO/queues/custom/51/GEO-269
> Fix caching issues with editable layers

- admin/acceptance_tests/layer_groups_test.py
- admin/c2cgeoportal_admin/routes.py
- admin/c2cgeoportal_admin/views/layer_groups.py
- commons/c2cgeoportal_commons/models/main.py
> grid and edit for layergroup

- geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl
see: https://github.com/camptocamp/ngeo/pull/3233
> Fix master for ngeo#3233 Pull Request

- admin/Makefile
- admin/docker-compose.yml
- admin/docker/demo-dump.sql
- admin/docker/docker-entrypoint.d/00-init-model
> docker db bootstrapped with demo data

- admin/Makefile
Avoid running npm install on each make serve
> [admin] Add make clean and add timestamp to node_modules

- c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/d8ef99bc227e_be_able_to_delete_a_linked_functionality.py
> Ignore unexisting constraint error

- c2cgeoportal/pyramid_.py
- c2cgeoportal/scripts/import_ngeo_apps.py
> Add the missing theme in the mobile redirect

- c2cgeoportal/lib/lingua_extractor.py
> Fix layer name encode

- c2cgeoportal/lib/__init__.py
- c2cgeoportal/lib/caching.py
- c2cgeoportal/models.py
- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/views/entry.py
- doc/developer/server_side.rst
Test case:
```
curl 'https://preprod.cartoriviera.ch/sbrunner/wsgi/themes?interface=mobile&version=2&background=background' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache'
curl 'https://preprod.cartoriviera.ch/sbrunner/wsgi/themes?interface=mobile&version=2&background=background&role=15' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' With the related cookie
```
Before (server time):
* first request: 21-23 s.
* second request: 25-26 s.
After (server time):
* first request: 10 s.
* second request: 4.5 s.
> Improve the layer cache 

- docker/build/dev-requirements.txt
related to camptocamp/ngeo#3241
> Upgrade Papyrus to fix the time in editing

- admin/acceptance_tests/__init__.py
- admin/acceptance_tests/layer_groups_test.py
- admin/acceptance_tests/layers_v1_test.py
- admin/acceptance_tests/layers_wms_test.py
- admin/acceptance_tests/layers_wmts_test.py
- admin/acceptance_tests/learn_test.py
- admin/acceptance_tests/themes_test.py
- admin/acceptance_tests/user_test.py
- admin/c2cgeoportal_admin/__init__.py
- admin/c2cgeoportal_admin/routes.py
- admin/c2cgeoportal_admin/views/layers.py
- admin/c2cgeoportal_admin/views/layers_wms.py
- admin/c2cgeoportal_admin/views/layers_wmts.py
- admin/c2cgeoportal_admin/views/themes.py
- admin/c2cgeoportal_admin/views/treeitems.py
- commons/c2cgeoportal_commons/models/main.py
- commons/requirements.txt
- docker/build/requirements.txt
require https://github.com/camptocamp/c2cgeoform/pull/149
default values and translations not taken into account
> Admin convert wms

- admin/c2cgeoportal_admin/__init__.py
- admin/config.yaml
- admin/development.ini
- admin/package.json
- admin/production.ini
- admin/requirements.txt
- admin/tests.ini.mako
We need a settings file for admin map settings and admin metadata settings, so I've created a first PR only creating the settings file.
> [admin] Add temporary settings file for dev purpose

- Jenkinsfile
- docker-compose-run
- docker-compose.yaml.mako
- docker/build/bin/wait-for-db
- geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose-build.yaml.mako
- geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose-run
- travis/docker-compose-build.yaml.mako
Check another technique than #3363
> Wait for db in compose build cmd

- admin/c2cgeoportal_admin/schemas/map.py
- admin/c2cgeoportal_admin/views/roles.py
- admin/config.yaml
- commons/c2cgeoportal_commons/models/main.py
- commons/requirements.txt
- geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_config-schema.yaml
Missing c2cgeoform upgrade for now
> [admin] Add map settings

- admin/acceptance_tests/__init__.py
- admin/acceptance_tests/layer_groups_test.py
- admin/acceptance_tests/layers_v1_test.py
- admin/acceptance_tests/layers_wms_test.py
- admin/acceptance_tests/layers_wmts_test.py
- admin/acceptance_tests/ogc_servers_test.py
- admin/acceptance_tests/role_test.py
- admin/acceptance_tests/themes_test.py
- admin/acceptance_tests/user_test.py
- admin/c2cgeoportal_admin/schemas/dimension.py
- admin/c2cgeoportal_admin/views/functionalities.py
- admin/c2cgeoportal_admin/views/layer_groups.py
- admin/c2cgeoportal_admin/views/layers_v1.py
- admin/c2cgeoportal_admin/views/layers_wms.py
- admin/c2cgeoportal_admin/views/layers_wmts.py
- admin/c2cgeoportal_admin/views/ogc_servers.py
- admin/c2cgeoportal_admin/views/restrictionareas.py
- admin/c2cgeoportal_admin/views/roles.py
- admin/c2cgeoportal_admin/views/themes.py
- admin/c2cgeoportal_admin/views/users.py
- commons/requirements.txt
- docker/build/requirements.txt
relates to https://github.com/camptocamp/c2cgeoform/pull/156
> Admin unicity constraints2

- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
match closure library path with module name in package json to fix debug mode
> fix debug mode

- admin/acceptance_tests/layers_wms_test.py
- admin/acceptance_tests/layertree_test.py
[WIP] Add single selenium test for the layertree delete button
> Add selenium test for delete in tree

- geoportal/c2cgeoportal_geoportal/scaffolds/create/tools/extract-messages.js
- geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl
Related to https://github.com/camptocamp/ngeo/pull/3558
> Add the new arguments name

- admin/Makefile
- admin/README.md
- admin/acceptance_tests/layers_wms_test.py
- admin/c2cgeoportal_admin/views/layers_wms.py
- admin/c2cgeoportal_admin/views/layers_wmts.py
- commons/requirements.txt
- docker/build/requirements.txt
depends on https://github.com/camptocamp/c2cgeoform/pull/162
> [admin], use and test dblclick on row from c2cgeoform

- travis/v22-project.yaml
Neded for https://github.com/camptocamp/ngeo/pull/3050
> Add new non project file

- admin/acceptance_tests/layertree_test.py
- admin/c2cgeoportal_admin/schemas/treegroup.py
- admin/c2cgeoportal_admin/schemas/treeitem.py
- admin/c2cgeoportal_admin/templates/layertree.jinja2
- admin/c2cgeoportal_admin/views/layer_groups.py
- admin/c2cgeoportal_admin/views/layers_wms.py
- admin/c2cgeoportal_admin/views/layers_wmts.py
- admin/c2cgeoportal_admin/views/treeitems.py
see https://github.com/camptocamp/c2cgeoform/pull/159
> Admin add new layertree

- admin/acceptance_tests/metadatas_test.py
- admin/c2cgeoportal_admin/schemas/metadata.py
- admin/c2cgeoportal_admin/templates/widgets/metadata.pt
- admin/c2cgeoportal_admin/templates/widgets/metadatas.pt
- admin/config.yaml
- geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_config-schema.yaml
- travis/vars.yaml
> [admin] Add metadata regex type

- admin/acceptance_tests/conftest.py
- admin/acceptance_tests/edit_url_test.py
- admin/acceptance_tests/functionalities_test.py
- admin/acceptance_tests/interface_test.py
- admin/acceptance_tests/layer_groups_test.py
- admin/acceptance_tests/layers_v1_test.py
- admin/acceptance_tests/layers_wms_test.py
- admin/acceptance_tests/layers_wmts_test.py
- admin/acceptance_tests/layertree_test.py
- admin/acceptance_tests/left_menu_test.py
- admin/acceptance_tests/metadatas_test.py
- admin/acceptance_tests/ogc_servers_test.py
- admin/acceptance_tests/role_test.py
- admin/acceptance_tests/themes_ordering.py
- admin/acceptance_tests/themes_test.py
- admin/acceptance_tests/user_test.py
- admin/c2cgeoportal_admin/schemas/metadata.py
This avoid any problem with session instances expiration in admin tests.
> Improve session hanling in admin tests

- admin/c2cgeoportal_admin/templates/widgets/children.pt
Fix https://jira.camptocamp.com/browse/GSGMF-285
> Do not allow free entries in children selection

- admin/acceptance_tests/layertree_test.py
- admin/acceptance_tests/selenium/page.py
- admin/c2cgeoportal_admin/routes.py
- admin/c2cgeoportal_admin/static/theme.css
- admin/c2cgeoportal_admin/templates/index.jinja2
- admin/c2cgeoportal_admin/templates/layertree.jinja2
- admin/c2cgeoportal_admin/templates/layout.jinja2
- admin/c2cgeoportal_admin/views/layertree.py
- admin/package.json
- admin/tests.ini.mako
- commons/requirements.txt
- docker/build/requirements.txt
Use bootstrap-table from source because of issue fixed but not yet released: https://github.com/wenzhixin/bootstrap-table/issues/3294
Note that jquery-treegrid plugin is no more yet released.
TODO: update tests
> [admin] Use bootstrap-table in layertree

- admin/development.ini
- admin/docker.ini
- admin/production.ini
- admin/requirements.txt
- admin/tests.ini.mako
- commons/c2cgeoportal_commons/__init__.py
> Remove pyramid_retry

- admin/acceptance_tests/ogc_servers_test.py
- commons/c2cgeoportal_commons/models/main.py
Complete https://github.com/camptocamp/c2cgeoportal/blob/98879de6877ca123ae3571519dafa310590866f8/commons/c2cgeoportal_commons/alembic/main/e004f76e951a_add_missing_not_null.py
Fix GSGMF-309
> Synchonize model's not null with alembic

- .travis.yml
- Jenkinsfile
- Makefile
- admin/config.yaml
- admin/docker-compose.yaml
- doc/administrator/tinyows.rst
- doc/builddoc.rst
- doc/developer/ngeo.rst
- doc/developer/server_side.rst.mako
- doc/developer/transifex.rst
- doc/integrator/install_application.rst
- doc/integrator/ngeo_new_interface.rst
- doc/integrator/tilegeneration.rst
- docker/build/requirements.txt
- geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl
- vars.yaml
Better lint call from CI
Fix the  previously not catched lint errors
> Some fix in the documentations

- .gitignore
- doc/integrator/upgrade_application.rst.mako
Put the section 'Upgrade a version 2.2' first
> Update the upgrade documentation

- c2cgeoportal/views/entry.py
Before an authenticated query on the theme after an unauthenticated query on the theme takes more than 1 minutes on BS-ref
Now it takes less than 10s.
> Better performances on 2.2

- doc/administrator/mapfile.rst
- doc/integrator/filter.rst
Bound to https://github.com/camptocamp/ngeo/pull/3650
> Improve doc for filters

- Makefile
- docker-compose-run
- docker-compose.yaml.mako
- docker-run
- docker/build/run
- geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose-build.yaml.mako
- geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose-run
- geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/docker-compose-build.yaml.mako
- geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl
- travis/docker-compose-build.yaml.mako
> Fix usage of HOME_DIR

- admin/acceptance_tests/metadatas_test.py
- admin/requirements.txt
(ci skip selenium tests, docker version need c2cgeoform 20-03-2018 version at least)
> test no side effect with leave alert when metadata disabled

- geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl
> Add missing requirement

- admin/config.yaml
- commons/c2cgeoportal_commons/lib/email_.py
- geoportal/c2cgeoportal_geoportal/scaffolds/create/vars.yaml_tmpl
- geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl
- geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_config-schema.yaml
- geoportal/c2cgeoportal_geoportal/views/entry.py
- geoportal/c2cgeoportal_geoportal/views/shortener.py
Prepare to use for welcome message with:
```
send_email_config(
self.request.registry.settings, "welcome_email", user.email,
user=user.username, password=password
)
```
> Move email function to common, simplify
