- c2cgeoportal/__init__.py
- c2cgeoportal/lib/filter_capabilities.py
- c2cgeoportal/views/pdfreport.py
- doc/integrator/features.rst
- doc/integrator/pdfreport.rst
This webservice allows the users to get a full PDF report concerning a given feature (layername+id), using  MapFish Print 3 and some jasper reports.
WIP, still TODO:
* handling mapserver groups
> Add pdfreport webservice

- c2cgeoportal/scaffolds/create/+package+/static/mobile/config.js_tmpl
- c2cgeoportal/scaffolds/update/+package+/static/mobile/app/controller/Main.js
- c2cgeoportal/scaffolds/update/+package+/static/mobile/app/plugin/StatefulMap.js
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- doc/integrator/mobile.rst
This PR adds the possibility to display a crosshair (`map_crosshair`) when calling the mobile app.
Currently it only implements the `map_crosshair` URL variable for the mobile app.
Please review
> Mobile crosshair

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
When we change the head of CGXP the GCXP submodules shouldn't be fetch
> Fix make dependencies date issue between submobules

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
Because of this typo the js code is not linted on make checks.
> Fix typo in CONST_Makefile

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
This is to prevent 404s on source map files in non-debug mode.
> Remove sourceMappingURL from build.js

- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
This changes the `pyramid_closure` config in `CONST_vars.yaml` to camptocamp/pyramid_closure#50 in the pyramid_closure package. This makes the debug mode work again, with and with the cache buster enabled.
> Change pyramid_closure config for camptocamp/pyramid_closure#50

- doc/administrator/mapfile.rst
Documentation for legend text. It includes the explanation about how to get a legend image without text, and how to integrate it as well into the admin interface.
> Legend text doc

- c2cgeoportal/__init__.py
- c2cgeoportal/lib/__init__.py
- c2cgeoportal/lib/filter_capabilities.py
- c2cgeoportal/scaffolds/create/+dot+gitignore_tmpl
- c2cgeoportal/scaffolds/create/apache/tinyows.conf.mako
- c2cgeoportal/scaffolds/create/mapserver/tinyows.xml.mako
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- c2cgeoportal/tests/__init__.py
- c2cgeoportal/tests/data/tinyows_describefeaturetype_request.xml
- c2cgeoportal/tests/data/tinyows_describefeaturetype_request_multiple.xml
- c2cgeoportal/tests/data/tinyows_getcapabilities.xml
- c2cgeoportal/tests/data/tinyows_getcapabilities_layer.xml
- c2cgeoportal/tests/data/tinyows_getcapabilities_layer_filtered_user1.xml
- c2cgeoportal/tests/data/tinyows_getcapabilities_layer_filtered_user2.xml
- c2cgeoportal/tests/data/tinyows_getcapabilities_request.xml
- c2cgeoportal/tests/data/tinyows_getfeature_request.xml
- c2cgeoportal/tests/data/tinyows_lockfeature_request.xml
- c2cgeoportal/tests/data/tinyows_transaction_delete_request.xml
- c2cgeoportal/tests/data/tinyows_transaction_insert_request.xml
- c2cgeoportal/tests/data/tinyows_transaction_update_request.xml
- c2cgeoportal/tests/functional/test_filter_capabilities.py
- c2cgeoportal/tests/functional/test_tinyowsproxy.py
- c2cgeoportal/views/mapserverproxy.py
- c2cgeoportal/views/proxy.py
- c2cgeoportal/views/tinyowsproxy.py
- doc/administrator/editing.rst
- doc/administrator/index.rst
- doc/administrator/tinyows.rst
This PR adds a proxy for TinyOWS which checks if a user has the rights to access a layer. A user has the right to read or write a layer, if the layer belongs to one of the user's restrictions areas and the `readwrite` flag of that restriction area is set to `True`.
It is important to note that the proxy does not take into account the area of a restriction area, contrary to the MapServer proxy which makes sure that only the features inside the defined area are returned. This is because the restriction extent would have to be hard-coded in the TinyOWS configuration file (see attribute [geobbox](http://mapserver.org/tinyows/configfile.html#layer-element)). So, if the access should restricted to a certain area, this area would have to be set in the configuration file.
This PR is not yet …
> Add proxy for TinyOWS

- c2cgeoportal/forms.py
- c2cgeoportal/lib/wmstparsing.py
- c2cgeoportal/models.py
- c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/5109242131ce_add_column_time_widget.py
- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/tests/functional/test_themes_time.py
- c2cgeoportal/tests/test_wmstparsing.py
- c2cgeoportal/views/entry.py
- doc/integrator/wmstime.rst
Adds a field `time_widget` to the layer models to specify the time widget to use (slider or datepicker). See https://github.com/camptocamp/cgxp/pull/938
> Add support for datepicker widget

- c2cgeoportal/scaffolds/update/CONST_requirements.txt
- c2cgeoportal/scaffolds/update/CONST_requirements_windows.txt
- c2cgeoportal/scaffolds/update/CONST_versions.txt
- doc/integrator/install_application.rst
I have the same problem with Pillow as we had with Psycopg2 and Shapely.
It has to be installed using a wheel containing the already compiled dll and binaries.
Furthermore, we cannot keep these `http://www.lfd.uci.edu/~gohlke/pythonlibs/sjdmq9dh/Shapely-1.5.7-cp27-none-win32.whl` kind of URLs, because they are only valid a day... (the `sjdmq9dh` code changes each day...)
I also tried to explain that in the doc...
Please review
> Pillow and other wheels in Windows

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- doc/integrator/requirements.rst
If using Mapfish print v3, then there are some commands which are run to start/stop the Tomcat service.
On Windows, the syntax of these ones is not the same then on Linux.
This PR:
* Defines a new print variable in `CONST_Makefile_tmpl` which is null by default (thus not altering the current build process).
* Adds some doc in the Windows specific section
If anybody has a better idea, then it is welcomed...
Please review
> Backport print and Tomcat service on Windows

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- doc/integrator/requirements.rst
This PR does implement two things:
* Print section for Windows: this is needed because Cygwin handles the existing bash commands in the Windows drive definition, thus it is "not" working. I opted for a specific Windows section, because the behavior differs quite a lot between Linux and Windows systems.
* directory variable: if this variable is defined through bash (in Windows...), then `${directory}` is substituted by `/cygdrive/c/...` everywhere. This does not work when calling the app through Apache (or even pserve) as this one expects to get values like `C:/...` on Windows. Defining `directory` using Python resolves this issue
Please review
> Makefile print section & yaml directory variable

- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
I do not think that `:` is the good relational equal operator in SQL. In my opinion, it should be `=` (and this is working in my project...)
Or did I miss something concerning new SQL syntax ?
> Replace : by = in SQL query

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
add missing touch on .build/node_modules.timestamp
Back-port of https://github.com/Geoportail-Luxembourg/geoportailv3/pull/642
> Rebuild libs after an update

- c2cgeoportal/scaffolds/create/build.json
Needed to use the `@export` jsdoc annotation
> Use export_local_property_definitions Closure Compiler flag

- c2cgeoportal/lib/filter_capabilities.py
- c2cgeoportal/tests/functional/c2cgeoportal_test.map.in
- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/tests/functional/test_mapserverproxy_group.py
As for now, the filter_capabilities tool removes not allowed layers from the WMS getcapabilities response. On the other hand if the removed layers are contained in a mapserver group, the group remains even though no embedded layers are shown.
This PR makes sure the group is removed as well if all contained layers have been removed.
Most of the code is from @sbrunner
> Remove groups when all child layers have been stripped out of getcap

- doc/integrator/upgrade_application.rst
Titles says it all.
It only applies to the specific Windows instructions.
@sbrunner, I created a PR to update the 1.6 branch. I just hope that this is right...
> Add a missing instruction for Windows upgrades in the docs

- c2cgeoportal/scaffolds/create/mapserver/c2cgeoportal.map.mako
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
Change "wms_srs" "epsg:..." to "wms_srs" "EPSG:..." in c2cgeoportal.map.mako.
Tell to do the same in all mapfiles in the changelog.
> Convert METADATA wms_srs to uppercase

- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- doc/administrator/editing.rst
This comes with camptocamp/cgxp#1002.
Adds the copy_to metadata key in CONST_vars.yaml template.
Document the change in changelog and administrator documentation.
> Add the copy_to metadata key on server side

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
Useful for projects with an intermediate "main/" folder. Such projects must have in their ``<project>.mk``:
```
GIT_MODULES_FOLDER ?= ../.git/modules/main/
```
Ported from a @sbrunner patch.
> Make git modules folder overridable in Makefile

- c2cgeoportal/scaffolds/create/+package+/templates/edit.html_tmpl
- c2cgeoportal/scaffolds/create/+package+/templates/index.html_tmpl
- c2cgeoportal/scaffolds/create/+package+/templates/routing.html_tmpl
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
~~Use IE11 document mode when available (currently IE11 uses IE10 document mode to render the geoportal).~~
~~After discussion with Stephane, we won't use the notation: ``<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7; IE=EmulateIE9; IE=edge">`` because this is less understandable.~~
Use IE11 document mode instead of IE10 document mode to avoid some bugs with ext. IE10 will use IE9 document mode.
> Use IE11 document mode

- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- c2cgeoportal/views/pdfreport.py
- doc/integrator/pdfreport.rst
* Update the doc doc make migration.
* Replace the `show_map` by a `map` config level.
* Use the Proxy class.
* Add the ability to use the non map attributes in the custom `spec`.
* Add the ability to have report with multiple maps with different
background layers (can be combine with single map).
> Update the PDF report

- doc/integrator/upgrade_application.rst
postgres complain otherwise
morges_migrate=# ALTER INDEX main.layer_pkey RENAME TO main.layertmp_pkey;
ERROR:  syntax error at or near "."
> dont use schema name in renamed values

- c2cgeoportal/scaffolds/create/+package+/static/mobile/config.js_tmpl
- c2cgeoportal/scaffolds/update/+package+/static/mobile/app/view/Main.js
Fix #1201
The in the `<package>/static/mobile/config.js` file `App.queryMode` should be set to "click" or "both".
> Set click pixel tolerance to 5px, be able to accept click and longpress

- c2cgeoportal/scaffolds/create/+package+/templates/ngeo.html_tmpl
- c2cgeoportal/scaffolds/create/build.json_tmpl
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
This is a backport of https://github.com/Geoportail-Luxembourg/geoportailv3/pull/848, where we decided to use the Angular template cache in non-debug mode as well as in debug mode.
> Use Angular templatecache also in debug mode

- c2cgeoportal/scaffolds/create/build.json_tmpl
- c2cgeoportal/scaffolds/create/package.json
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
This PR targets the 1.6 branch. It basically includes three changes:
* `build.json` is now a template (`build.json_tmpl`), and `{{package}}` is used instead of `geoportailv3` in the file.
* https://github.com/elemoine/c2cgeoportal/commit/6b6769a9641b3d88924ab6dad5327995daaab17a is backported to use the Angular template cache in debug mode.
* Switch from Angular v1.3 to Angular v1.4, v1.4 being what ngeo relies on (although ngeo also works with 1.3), and v1.4 being what the Luxembourg project already uses.
> ngeo-related changes for the 1.6 branch

- c2cgeoportal/scaffolds/create/package.json_tmpl
We don't need to use the 1.x branch because we don't support IE < 9
> Use jquery v2.1.4

- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- doc/integrator/make.rst
The files `apache/mapcache.xml` and `apache/tiles.conf` will be generated
automatically.
> Better TileCloud chain integration

- c2cgeoportal/views/pdfreport.py
The vector layer was requested in GML2, which caused problems with MFP (polygons were parsed as empty geometry). This PR proposes to use GML3 which is parsed correctly.
> Use GML3 for vector layer in PDF report service

- c2cgeoportal/views/entry.py
- doc/integrator/backend.rst
- doc/integrator/backend_geoserver.rst
Geoserver uses namespaces for representing the different workspaces.
Because of that, one cannot remove it.
I took the opportunity to start the GeoServer backend documentation.
Now based on 1.6, as requested.
> Fixed box query for GeoServer

- travis/build-new-project.sh
The new project Travis was creating was not using the current c2cgeoportal
version, but an older one. This is because c2cgeoportal as been removed from
CONST_versions.txt.
> Fix Travis when building a new project.

- c2cgeoportal/scaffolds/create/templatecache.mako.js
This is a backport of Geoportail-Luxembourg/geoportailv3#929.
This requires #1762, which targets the 1.6 branch. So when #1762 is merged, the 1.6 branch should be merged into the master branch before merging that PR.
Closes #1755.
> Use htmlmin in templatecache.js.mako

- c2cgeoportal/scaffolds/update/CONST_requirements_windows.txt
This PR updates the version of the Shapely wheel for instances running on Windows (I think SITN might be the only one on Windows...).
I need that because we have some troubles running our instances on Shapely 1.5.7 (some DLL mix up... don't ask... Windows...)
This PR is meant to be merged into the 1.6 branch.
Thanks !
> Update Shapely version for Windows

- c2cgeoportal/__init__.py
- c2cgeoportal/scaffolds/create/+package+/templates/edit.js_tmpl
- c2cgeoportal/scaffolds/create/+package+/templates/viewer.js_tmpl
- c2cgeoportal/scaffolds/create/jsbuild/app.cfg.mako_tmpl
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- c2cgeoportal/tests/functional/__init__.py
- c2cgeoportal/tests/functional/test_groups_finder.py
- c2cgeoportal/tests/functional/test_request_property.py
- c2cgeoportal/tests/test_init.py
- c2cgeoportal/views/entry.py
- doc/integrator/security.rst
Added a protection against CSRF attacks.
Validate the query referer against a list of authorized referers.
The best solution would be to add a token only the main page
knows when the user logs in (via a cookie). Adding a header to all the requests
would mean a lot of changes:
* Extjs: ``Ext.Ajax.setDefaultHeaders``
* OL: ``OpenLayers.Request.DEFAULT_CONFIG.headers``
* JQuery: ``$.ajaxSetup({headers: {...}})``
* Angular: ``$httpProvider.defaults.headers``
Fixed details in edit.js and view.js    
The edit page was failing because:
* EVENTS was undefined
* WMS and WMTS where undefined
The view page was always showing the restricted warning even after
logging in because:
* view.js was cached
* non existant default theme
> Security fixes

- doc/integrator/make.rst
CONFIG_VARS is already described here http://docs.camptocamp.net/c2cgeoportal/1.6/integrator/make.html#makefile-config-variables but I think we could make it even more obvious, because making config vars available in the templates or python code is a recurrent question.
> Add doc about CONFIG_VARS

- c2cgeoportal/scaffolds/create/deploy/deploy.cfg.mako_tmpl
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
because we need the latest alembic upgrade script to be able to do that.
this will only work with a new delpoy package, but will not cause any problem in the meantime.
cf https://github.com/camptocamp/deploy/commit/7af8edb9aaa6043e288215e90719ecf4d2c6d752
> To update the static schema, we need to deploy the code first

- c2cgeoportal/views/proxy.py
reported from https://github.com/camptocamp/jura_c2cgeoportal/issues/40
> Fix encoding issue in httplib when doing print request from IE11.

- c2cgeoportal/scaffolds/create/print/WEB-INF/classes/logback.xml.mako
We use to have this error message:
WARN in ch.qos.logback.core.ConsoleAppender[standardOut] -
This appender no longer admits a layout as a sub-component, set an encoder instead.
Upgraded the print to 3ff8727.
> Stop using deprecated configuration for print logging

- c2cgeoportal/__init__.py
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- c2cgeoportal/views/resourceproxy.py
- doc/integrator/https.rst
Useful when the project is configured with https and you want to include non-https content. The resources url host must be specifically added in the project configuration to be allowed to be loaded.
Needed in the Morges project.
> Add a new resourceproxy service, allowing to load external resources.

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
Same as #1915 :-) but in the 1.6 branch
> Ignore the node_modules folder in the template generation

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_print_url
- c2cgeoportal/scaffolds/update/print/Dockerfile
Took the opportinity to fix a few things:
* The Jasper version changed.
* The lib jasperreports-fonts is already included in the print.
* DRY in the makefile for the cleaning of print libs.
* Moved the print Dockerfile from create to update (no reason for the user
to change it).
> Upgrade print to 3.3.0.

- c2cgeoportal/views/pdfreport.py
Otherwise, the print won't have the correct hostname.
> Forward headers for pdfReport's proxy

- doc/integrator/querier.rst
This PR precises where ``dbsession`` parameter comes from in the querier doc: http://docs.camptocamp.net/c2cgeoportal/1.6/integrator/querier.html
> Add doc for DB sessions usage in querier config

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
The places we download from are often returning HTML files instead of the
JARs we request. The leads to very obscure and hard to debug errors in the
print. So checks will serve as early detection of those problems.
> Add check for the downloaded JARs

- c2cgeoportal/tests/test_raster.py
- c2cgeoportal/views/profile.py
The problem comes when there is a small distance between most of the vertices of the linestring.
A linestring composed of 800 vertices could return only result for the first vertex.
> Add the coordinate even if computed number of point is 1

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
because pip version 8.* is currently not compatible
> set version of pip not causing error when installing PasteScript

- doc/integrator/create_application.rst
git submodule add -b <version> <repository> <path> is working.
> Best place for b flag in git submodule add command

- c2cgeoportal/__init__.py
- c2cgeoportal/tests/test_locale_negociator.py
This function was relying on Piramid to use default_locale_name if no locale
is found. But fulltextsearch is using this function directly and was returing
status=500 if the browser's languages were not matching the list of available
languages.
> Fix locale_negotiator for fulltextsearch

- .travis.yml
- travis/doc.sh
Because it breaks the build
Don't failed on redo Travis (noting to commit)
[#1937]
> Do the documentation deploy at the end

- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- c2cgeoportal/tests/test_checker.py
- c2cgeoportal/views/checker.py
- doc/integrator/checker.rst
When we apply ACL on views, we need cookie to be forwarded by the checker.
I need this for lyon airport where only login and logout views are public.
> Forward cookie header in checker and check_collector

- Makefile
- c2cgeoportal/stats.py
Fix a small bug where invalid statsd packet where sent when the key
was containing weird chars.
Fix build when there is no c2cgeoportal installed on the machine
> Add more stats (rendering time).

- doc/administrator/administrate.rst
fixes https://github.com/camptocamp/c2cgeoportal/issues/2013
> Small typo and new name for exclute properties

- c2cgeoportal/scaffolds/create/print/print-apps/+package+/config.yaml.mako
- c2cgeoportal/scaffolds/update/CONST_packages.yaml
Mine reports that:
openjdk version "1.8.0_66-internal"
Remove useless dnsMatch for the mapUri rule.
> Support openjdk 8 in java version checking

- c2cgeoportal/__init__.py
- c2cgeoportal/lib/lingua_extractor.py
- c2cgeoportal/scaffolds/update/CONST_dev-requirements.txt
- c2cgeoportal/scaffolds/update/CONST_versions_requirements.txt
- c2cgeoportal/tests/config.yaml
- setup.py
> Use new version of c2c.template

- c2cgeoportal/scaffolds/create/deploy/hooks/pre-restore-database.mako
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
> Go to the project directory before running alembic upgrade

- doc/integrator/ngeo.rst
Fix https://github.com/camptocamp/ngeo/issues/960
> Add documentation about the ngeo map configuration

- Makefile
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scripts/import_ngeo_apps.py
- setup.py
That's respect the semantic versioning on npm https://docs.npmjs.com/misc/semver
> Be able to create dev and RC releases with npm

- doc/administrator/mapfile.rst
Because WFS GetFeature doesn't work else.
> Doc - Mapfile TEMPLATE value must be in quotes.

- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/tests/functional/test_themes.py
- c2cgeoportal/views/entry.py
- doc/developer/webservices.rst
- doc/integrator/ngeo.rst
Related to https://github.com/camptocamp/ngeo/issues/1238
> UI metadata and server needed to query the background

- c2cgeoportal/__init__.py
- c2cgeoportal/models.py
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- doc/integrator/cluster.rst
Basically, this guy switches the DB connection to a replica (readonly) DB if the HTTP method is GET or OPTIONS.
> Allow to have a master/replica DB configuration

- c2cgeoportal/views/fulltextsearch.py
Fulltextsearch was not using variable binding for searched terms. This was
leading to a lot of different statistics for those queries, leading to
memory leak if the MemoryBackend was enabled and a lot of data in statsd.
> Fixed tsearch query to use bindings

- .gitignore
- Makefile
- c2cgeoportal/scaffolds/__init__.py
- travis/create-new-project.sh
> Add the create template in the update template to track the changes

- c2cgeoportal/scripts/import_ngeo_apps.py
See: https://github.com/camptocamp/ngeo/pull/1401
> Removes graceful-fs, no more needed

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
No need to remove from `.build/externs`; `.build` is already removed (`rm -rf .build` 2 lines above).
> Simplify CONST_Makefile

- c2cgeoportal/__init__.py
The previous pattern was matching all the end of the URL, which was too much. If an Angular partial was erronously using a prefix with 'theme' it bugged the browser in an infinite loop.
> Match theme with a simple pattern

- c2cgeoportal/scaffolds/create/+dot+dockerignore_tmpl
- c2cgeoportal/scaffolds/create/alembic.ini.mako_tmpl
- c2cgeoportal/scaffolds/create/alembic_static.ini.mako_tmpl
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_alembic/main/env.py
- c2cgeoportal/scaffolds/update/CONST_alembic/static/env.py
- c2cgeoportal/scaffolds/update/run_alembic.sh
- doc/integrator/docker.rst
Now, the WSGI can be used as an Alembic container to upgrade the DB schema.
Fix the Makefile dependencies for Alembic generated SQL files.
> Docker: add alembic to the WSGI image

- c2cgeoportal/scaffolds/create/apache/application.wsgi.mako
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- doc/integrator/docker.rst
Add a way to configure the logging from the composition.
Fixed the production.ini file loading. I have a feeling it
was silently not working before.
> Docker: better logging configurability

- c2cgeoportal/lib/__init__.py
- c2cgeoportal/tests/test_init.py
- c2cgeoportal/views/entry.py
Parameters like 'Détecteur de feu' need to be encoded before url escape.
> Fix unicode theme error when logged in

- c2cgeoportal/scaffolds/update/CONST_dev-requirements.txt
flake8 3.x don't works on Travis with pip >= 6.x
> Back to flake8 2.6.2

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
See https://github.com/camptocamp/c2cgeoportal/issues/2188#issuecomment-216537865
This is actually also working via https on Windows....
But I think it is OK to keep the `TX_HOST` variable in `CONST_Makefile` so that the URL is only hard coded once (by defining the variable), thus not to completely revert https://github.com/camptocamp/c2cgeoportal/pull/2196
Please review and (eventually) merge
> Remove http URL for tx host on Windows

- c2cgeoportal/views/entry.py
- setup.py
fix https://github.com/camptocamp/schwyz_geoportal/issues/232
fix #1549
> Be able to have a query layer without any scale bounds

- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- c2cgeoportal/tests/functional/test_layers.py
- c2cgeoportal/views/layers.py
Fix #2583
Added the `geometry_validation` UIMetadata to disable the check ST_IsValid and ST_IsSimple. Simply set it to False to disable it. Added tests and there's only one commit.
> Disable geometry check per layer in 1.6

- c2cgeoportal/forms.py
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
Fix : https://github.com/camptocamp/c2cgeoportal/issues/2725
> Use unicode to format the returned page

- .gitmodules
Openlayers v2 github repository has be renamed.
This update the submodule url.
> Fix openlayers submodule url

- c2cgeoportal/scaffolds/update/CONST_alembic/static/versions/1da396a88908_move_user_table_to_static_schema.py
Actually when we create a new project it will:
* Apply the main scripts who will create the user table in the main schema.
* Apply the static scripts who will move the user table from the main to the static schema.
And when we deploy the application on an empty database it will:
* Dump restore the main schema to the destination schema (that's don't have a user table)
* Apply the static scripts who will try to move the user table from the main to the static schema... => :-/
> Be able to deploy the database the first time

- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
Avoid "NoneType is not iterable" error in : 
```
def _get_layers_enum(self):
layers_enum = {}
if "enum" in self.settings.get("layers", {}):
```
> Set const vars layers to empty dict

- c2cgeoportal/scaffolds/create/deploy/hooks/pre-restore-database.mako
Because that's not the directory to deploy the code
> Don't use 'directory' on deploy

- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
For: https://github.com/camptocamp/c2cgeoportal/wiki/Spec-%232804-Pre-defined-opacity-for-WMS-WMTS
(I'l do it manually in the demo)
We should add documentation about that... but where ?
(I add it this question in specs)
> Add metadata 'opacity'

- c2cgeoportal/scaffolds/update/CONST_requirements.txt
- c2cgeoportal/scaffolds/update/CONST_requirements_windows.txt
- c2cgeoportal/scaffolds/update/CONST_versions_requirements.txt
- doc/integrator/requirements.rst
Starting with pip >= 9, binary dependencies can now be installed through pip (as long as the wheel enables it...).
I removed the potential dependencies from the specific Linux/Windows requirement files and added their current "Linux" version to the common version file.
I tested all these packages in an independent virtual environment. I did not have any problem running the following commands:
```
Scripts\pip.exe --no-cache-dir install pillow==3.4.2
Scripts\pip.exe --no-cache-dir install psycopg2==2.6.2
Scripts\pip.exe --no-cache-dir install pyproj==1.9.5.1
```
I also updated the documentation.
only Shapely remains problematic...
> Less Windows requirements

- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
This is needed because in Windows only double backslash might be used.
This is mainly a backport of what we have done with @sbrunner this morning in the SITN project.
> Generate a on-the-fly path separator

- c2cgeoportal/pyramid_.py
- c2cgeoportal/tests/test_init.py
Fix #2904
* Allow no referer for GET requests
* Do not check referer multiple times in the same request
> [CRSF protection] Allow no referer even outside admin interface

- doc/integrator/backend_qgis.rst
.pg_service.conf file allow the use of a service name instead of parameters for
to set up a PostGIS connection. So for the same QGIs project, you can easily
change the connection parameters switching the .pg_service.conf file.
In a client <-> server process, you can use the same QGIs project file with
different PostGIS connection.
> Explain PostGIS connexion using pg_service.conf

- c2cgeoportal/scaffolds/update/CONST_versions_requirements.txt
backport #2838 to 2.1 branch
fixes #2927
> Remove unused dogpile.core package

- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/tests/functional/test_mapserverproxy.py
- docker/test-mapserver/mapserver.map.mako
When MAPSERVER=FALSE, we should not depend on mapserver.timestamp
to build the translations.
Pass the list of languages when creating the TX configuration so that
it is not hardcoded to fr and de anymore.
> Fix multi-language mapserverless projects

- c2cgeoportal/lib/__init__.py
- c2cgeoportal/lib/cacheversion.py
- c2cgeoportal/lib/filter_capabilities.py
- c2cgeoportal/lib/functionality.py
- c2cgeoportal/tests/functional/__init__.py
- c2cgeoportal/tests/functional/c2cgeoportal_test.map.mako
- c2cgeoportal/tests/functional/test_entry.py
- c2cgeoportal/tests/functional/test_layers.py
- c2cgeoportal/tests/functional/test_mapserverproxy.py
- c2cgeoportal/tests/functional/test_mapserverproxy_capabilities.py
- c2cgeoportal/tests/functional/test_tinyowsproxy.py
- c2cgeoportal/views/entry.py
- c2cgeoportal/views/mapserverproxy.py
- c2cgeoportal/views/ogcproxy.py
- c2cgeoportal/views/tinyowsproxy.py
- doc/developer/server_side.rst
Part of #2929 
TODO:
(I've not tested the things about doing a curl to get capabilities with basic auth.)
> Filter WMS capabilities with correct OGC server

- doc/integrator/install_application.rst
Remove comments about a `git submodule` invocation that was removed in PR #1814.
See https://github.com/camptocamp/c2cgeoportal/pull/1814/files#diff-4b823d11f6d824081a897715d515cf86L137
> Remove obsolete comments

- c2cgeoportal/scaffolds/update/CONST_dev-requirements.txt
Previous transifex-client version (0.11.x) may cause timeout errors when downloading i18n files. Upgrading to 0.12.x solves this issue.
0.12.4 is the version already used at https://github.com/camptocamp/c2cgeoportal/blob/2.2/docker/build/dev-requirements.txt#L89
> Upgrade transifex-client to 0.12.4

- .travis.yml
- c2cgeoportal/views/pdfreport.py
FIX: #3041
I think the variable `self.default_ogc_server.id` always exists, no ? 
(Otherwise, an error is already throw)
> Use default ogc_server to print private layer's pdfreport

- c2cgeoportal/lib/filter_capabilities.py
This code already exist in 1.6, was existing in master but was overriden by a 2.1 merge :-(
It's required to keep privacy on private layers in capabilities
It's okay to merge it in 2.1 ? It's also required in 2.0, 2.2, master (1.6 contains already this commit)
> Lowercase layer to filter them

- c2cgeoportal/forms.py
As layer dimension config value take precedence over global dimensions values,
it needed to be able set NULL values in dimensions.
Replace #3042
> Remove required on dimension.value

- c2cgeoportal/lib/filter_capabilities.py
For #3041 again
To fix pdf_report and (almost) any other use of "get_protected_layers".
Fix also possible errors with "get_writable_layers"
(already done in 2.2 with: #3031 )
> Get_protected_layer - clear connection to the db instance

- c2cgeoportal/lib/filter_capabilities.py
- c2cgeoportal/views/mapserverproxy.py
- c2cgeoportal/views/ogcproxy.py
- c2cgeoportal/views/proxy.py
- c2cgeoportal/views/tinyowsproxy.py
This was discovered when trying to get TinyOWS to work in GEO-368. Changed the function "get_ogc_server_wfs_url_ids" to use the input as key (instead of using the looked up url), the goal being to look up the layer ids for these keys, not for the urls: this is how the caller filter_wfst_capabilities() expects the dictionary.
> fix function get_ogc_server_wfs_url_ids

- c2cgeoportal/scaffolds/update/CONST_config-schema.yaml
To be consistent with views.checker.build_url.
Fix #3127
> Move checkers forward_headers key checker in CONST_config-schema.yaml

- c2cgeoportal/lib/authentication.py
Principals was not returned in case of basic auth.
Regarding BasicAuthAuthenticationPolicy documentation for check:
A callback function passed a username, password and request, in that order as positional arguments. Expected to return None if the userid doesn't exist or a sequence of principal identifiers (possibly empty) if the user does exist.
So we should return the role name here, works for me in aeroportdelyon_sig.
> Fix basic auth group finder

- .travis.yml
- c2cgeoportal/lib/email_.py
- c2cgeoportal/scaffolds/create/vars_+package+.yaml_tmpl
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/views/entry.py
- c2cgeoportal/views/shortener.py
- doc/integrator/reset_password.rst
- doc/integrator/shortener.rst
More and more smtp service needs authentication to use a SMTP service (SSL,
auth, stattls). So we need to support authenticated smtp, smtps, etc.
> Allows use of smtps

- .travis.yml
- Jenkinsfile
- Makefile
- docker-compose.yaml.mako
- docker/build/requirements.txt
- geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+travis.yml
- geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose-build.yaml.mako
- geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose.yaml.mako
- geoportal/c2cgeoportal_geoportal/scaffolds/create/print/print-apps/+package+/config.yaml.mako
- geoportal/c2cgeoportal_geoportal/scaffolds/create/project.yaml.mako_tmpl
- geoportal/c2cgeoportal_geoportal/scaffolds/create/vars.yaml_tmpl
- geoportal/c2cgeoportal_geoportal/scaffolds/create/yamllint.yaml
- geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/docker-compose-build.yaml.mako
- geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/print/print-apps/+package+/config.yaml.mako
- geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/project.yaml.mako_tmpl
- geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/vars_nondocker.yaml_tmpl
- geoportal/c2cgeoportal_geoportal/scaffolds/nondockerupdate/+dot+upgrade.yaml_tmpl
- geoportal/c2cgeoportal_geoportal/scaffolds/update/+dot+upgrade.yaml_tmpl
- geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl
- geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_config-schema.yaml
- geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_vars.yaml_tmpl
- geoportal/tests/config.yaml
- travis/docker-compose.yaml
- travis/v22-project.yaml
- travis/vars-nondocker.yaml
- travis/vars.yaml
- vars.yaml
- yamllint.yaml
> Add YAML lint

- doc/builddoc.rst
- doc/conf.py
- doc/integrator/intranet.rst
- doc/integrator/upgrade_application.rst.mako
Add infos to c2cgeoportal 2.1 docu, as obtained when updating gmf 1.6 to gmf 2.1 in SZ project (as preliminary step to upgrade to gmf 2.2.), handled in ticket GSSZ2-22.
> [doc, 2.1] add update infos from GSSZ2-22

- admin/acceptance_tests/conftest.py
- admin/acceptance_tests/layertree_test.py
- admin/c2cgeoportal_admin/routes.py
- admin/c2cgeoportal_admin/static/theme.css
- admin/c2cgeoportal_admin/templates/layertree.jinja2
- admin/c2cgeoportal_admin/templates/layout.jinja2
- admin/c2cgeoportal_admin/templates/navigation.jinja2
- admin/c2cgeoportal_admin/views/layertree.py
- admin/package.json
- commons/c2cgeoportal_commons/models/main.py
Note that I use dbsession identity map to load all treeitems and relations in 2 SQL requests.
Complete tree get loaded in 100ms.
For that I've added some "polymorphic_identity" on abstract classes.
For now we do not have a real context menu but a dropdown menu.
TODO : Test delete, but this was not part of this print in facts.
> Add layertree view

- doc/integrator/ngeo.rst
This is a [new feature](https://github.com/camptocamp/c2cgeoportal/pull/2971) (with 2.2.1), which is not documented (I found nothing).
My instructions describe how I used the MAKO_BUILD_ARGS in a project. Whether this us actually the intended way is up for discussion.
> Adding documentation for ngeo externs

- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
To fix 
- site not accessible after upgrade to 2.1
- CORS login warnings
(Retrofitted from 2.2 branch into 2.1)
> Fix scaffold for authorized_referers and login headers

- Makefile
In admin, this allow us to run ./docker-run make flake8 locally without removing our build files.
> Ignore .build and node_modules in flake8

- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
For issue https://github.com/camptocamp/c2cgeoportal/issues/3400
Origin host name comes (example from Nyon) like this: https://map-demo.nyon.ch
So the default vars should be "{web_protocol}://{host}, not "{web_protocol}://{host}/
> Fix standard login access control

- admin/acceptance_tests/edit_url_test.py
- admin/c2cgeoportal_admin/views/interfaces.py
- admin/c2cgeoportal_admin/views/restrictionareas.py
- admin/c2cgeoportal_admin/views/roles.py
- admin/c2cgeoportal_admin/views/themes.py
- commons/requirements.txt
List of checkboxes have a new pen icon to allow users to edit an element (for instance, a
role). Clicking on this icon will first check if changes were made in the current form. If the
user switches to another form, there's no way back – only one form is open at a time
Requires:
Adapt templates : 
https://github.com/camptocamp/c2cgeoform/pull/153
Check before leaving page if form has changed:
https://github.com/camptocamp/c2cgeoform/pull/155
> add edit url to tables

- c2cgeoportal/scaffolds/update/CONST_packages.yaml
Accept updated openjdk version output format. Will still work on older version outputs.
> Accept updated openjdk version output format. 

- c2cgeoportal/scaffolds/create/CONST_print_url
- c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_print_url
- c2cgeoportal/scaffolds/update/print/Dockerfile
update mfp version; needs an update to Makefile, too, because mfp starting 3.11 no longer contains a print-apps directory.
Note that mfp 3.11 and older require a Java 8 runtime on the system. A Debian 8 backport for Java 8 is available, and installed on c2c's test and demo servers.
> update mfp version

- geoportal/c2cgeoportal_geoportal/scaffolds/create/print/print-apps/+package+/config.yaml.mako
- geoportal/c2cgeoportal_geoportal/views/proxy.py
- geoportal/tests/functional/__init__.py
This will allow to follow the logs belonging to a single request coming from
the user.
> Forward the request tracking ID to the other service

- doc/integrator/filter.rst
As discussed with @ger-benjamin, there was some missing information about configuring enumerated attributes as the final step is to be done in admin. This PR add documentation about that.
> Add administration configuration documentation for filters

- travis/short-make
Actually the limit is at 10 s. and the rebuild time takes 9-10s. => increase to 15s.
> Incrase the accepted time to do the rebuild

- geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/+package+_geoportal/__init__.py_tmpl
Without that I have this:
```
[Mon Mar 19 16:37:49.986154 2018] [wsgi:error] [pid 9879] [remote 128.179.66.4:59338] error: no commands supplied
[Mon Mar 19 16:37:54.911802 2018] [wsgi:error] [pid 9879] Warning: The key 'arguments' is not present in: ['backend']
[Mon Mar 19 16:37:54.984687 2018] [wsgi:error] [pid 9879] [remote 128.179.66.4:59346] mod_wsgi (pid=9879): Target WSGI script '/home/sbrunner/demo_geomapfish/apache/application.wsgi' cannot be loaded as Python module.
[Mon Mar 19 16:37:54.984798 2018] [wsgi:error] [pid 9879] [remote 128.179.66.4:59346] mod_wsgi (pid=9879): SystemExit exception raised by WSGI script '/home/sbrunner/demo_geomapfish/apache/application.wsgi' ignored.
[Mon Mar 19 16:37:54.985240 2018] [wsgi:error] [pid 9879] [remote 128.179.66.4:59346] Traceback (most …
```
> Fix distutils.errors.DistutilsArgError: no commands supplied error

- doc/integrator/fulltext_search.rst
- doc/integrator/install_application.rst
- geoportal/c2cgeoportal_geoportal/views/fulltextsearch.py
- geoportal/tests/functional/test_fulltextsearch.py
For GEO-908
In 2.3, we want to use "similarity" by default.
As "similarity" is now used by default, should I add a "CREATE EXTENSION pg_trgm;" in an alembic script ?
> FTS: Use similarity by default

- admin/c2cgeoportal_admin/views/users.py
- commons/c2cgeoportal_commons/alembic/static/1857owc78a07_add_last_login_and_expiration_date.py
- commons/c2cgeoportal_commons/models/static.py
- geoportal/c2cgeoportal_geoportal/__init__.py
- geoportal/c2cgeoportal_geoportal/scripts/deactivate_olds_accounts.py
- geoportal/c2cgeoportal_geoportal/views/entry.py
Note that this is based on @ger-benjamin branch, could be squashed before merge to master.
Not sure it make sense to set last_login = now during migration. This could be left to administrator.
Note that in mosts systems we use last_connection instead of last_login, as login is not required in all cases (remember using cookie, kerberos authentication, and maybe others).
> Add user.last_login, expire_on and deactivated

- commons/c2cgeoportal_commons/models/main.py
- commons/c2cgeoportal_commons/models/static.py
- geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/+package+_geoportal/resources.py
Wonder where to declare acl in order them to be taken into account when scaffold update, in scaffold create resources or in c2cgeoportal ?
As authentification policy is set in constructor, authorization policy default to acl, cf. lib/python3.5/site-packages/pyramid/config/__init__.py line 427.
> admin, set acl for admin views: 'role_admin' can all

- commons/requirements.txt
Used at least here: https://github.com/camptocamp/c2cgeoportal/blob/master/commons/c2cgeoportal_commons/models/main.py#L45
> Add zope.event in commons requirements

- admin/acceptance_tests/layers_wms_test.py
- admin/acceptance_tests/layers_wmts_test.py
- admin/c2cgeoportal_admin/views/layers_wms.py
- admin/c2cgeoportal_admin/views/layers_wmts.py
This is a workaround for the case the defaults layers does not exist.
In case we convert a WMS to WMTS without default WMTS layer the converted WMTS layer has this values:
* url: ""
* matrix_set: ""
=> already committed, but when user click on submit in the resulting WMTS form the empty fields are refused by the validation (interpreted as NULL).
This seems acceptable.
On the other side (WMTS => WMS), I take the first OGCServer id.
Note that it should also be possible to create the default layers by an alembic script, but we will have the same choices to do concerning the missing default values.
Better handling could be to propose the values to the user before committing, but this may be a little more complex to change now.
> [admin] Fix convert without defaults. GSGMF429

- docker/build/requirements.txt
The two packages are already in the requirements of tilecloud and tilecloud-chain.
> Require boto3 instead of boto

- admin/c2cgeoportal_admin/static/layertree.css
Because when transparent, rows are visible behing the header when scrolling
> [admin] Set layertree header background to white

- c2cgeoportal/scaffolds/create/+package+/templates/edit.html_tmpl
- c2cgeoportal/scaffolds/create/+package+/templates/index.html_tmpl
- c2cgeoportal/scaffolds/create/+package+/templates/routing.html_tmpl
According to the doc here: https://github.com/camptocamp/c2cgeoportal/commit/2d32486d15bd681293fd9fe0160e7325cfcee9a4#diff-c8f9eab6b316727f9bd103c613a3f8edR126 (that is a doc for migration I guess)
This field is missing and break the app if I try to just point CGXP on a recent 1.6 commit (commits after 1.6.13 release). Adding this form field to the project fixed the issue, but should be reported here in the templates as well.
> [1.6] Add missing oldpassword field in html templates

- c2cgeoportal/views/shortener.py
Fix https://github.com/camptocamp/c2cgeoportal/issues/3701, and https://github.com/camptocamp/c2cgeoportal/issues/3406
> Don't send an email to the creator of the short URL

- docker/build/Dockerfile
It was frozen because 1.8.0 was requiring graphviz-dev to be installed
on the machine. This requirement was lifted in a later version.
> Unfreeze c2cwsgiutils

- Jenkinsfile
- geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose-build.yaml.mako
- geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST.mako_inc
- geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_vars.yaml_tmpl
- geoportal/c2cgeoportal_geoportal/scripts/create_demo_theme.py
- geoportal/c2cgeoportal_geoportal/views/entry.py
- travis/create-new-nondocker-project.sh
- travis/create-new-project.sh
- travis/docker-compose-build.yaml.mako
One time per process and OGC server,
Not one time per layers.
fix: https://jira.camptocamp.com/browse/GEO-1246
> Parse the WMS capabilities less times.

- geoportal/c2cgeoportal_geoportal/views/profile.py
- geoportal/c2cgeoportal_geoportal/views/raster.py
Now, we can have something like that in the config:
```yaml
raster:
srtm:
file: /vsicurl/http://url-of-some-http-service/SRTM21781/srtm.shp
round: 1
```
That http service could be S3.
> Make the raster files (profile) work over http(s)

- geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/nondocker-finalise.mk_tmpl
because pip == 10 is much better integrated for installing (& compiling) wheels
Thanks for any review (and eventually merging this if Travis & co. are happy)
Replaces #3852
(sorry about that @sbrunner)
> Windows cannot run get-pip-dependencies without shell & update pip

- c2cgeoportal/lib/lingua_extractor.py
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- c2cgeoportal/scaffolds/update/CONST_config-schema.yaml
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
Addresses https://github.com/camptocamp/c2cgeoportal/issues/1826 (so far, only for lingua_extractor functionality, because currently only needed there).
> configurable http

- c2cgeoportal/lib/__init__.py
- c2cgeoportal/lib/filter_capabilities.py
- c2cgeoportal/lib/lingua_extractor.py
- c2cgeoportal/scaffolds/create/project.yaml.mako_tmpl
- c2cgeoportal/scaffolds/update/CONST_config-schema.yaml
- c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl
- c2cgeoportal/scripts/c2ctool.py
- c2cgeoportal/views/check_collector.py
- c2cgeoportal/views/checker.py
- c2cgeoportal/views/entry.py
- c2cgeoportal/views/proxy.py
use http options throughout c2cgeoportal and use config parameter to decide whether to force to localhost on checker
> make checker work on non-standard environments (via parameterization)

- c2cgeoportal/lib/dbreflection.py
- c2cgeoportal/lib/lingua_extractor.py
- c2cgeoportal/views/layers.py
In addition, this should ensure all created classes for a layer are consistent.
> Centralize the get_layer_class code in a unique place

- Makefile
- c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl
- dev-requirements.txt
- requirements.txt
remove index-url to pypi.camptocamp.net, as server is no longer maintained
> [1.6] remove index-url to pypi.camptocamp.net

- doc/integrator/database.rst
- doc/integrator/index.rst
- geoportal/c2cgeoportal_geoportal/scaffolds/create/Makefile_tmpl
- geoportal/c2cgeoportal_geoportal/scaffolds/update/scripts/CONST_clone_schema.sql
https://jira.camptocamp.com/browse/GSGMF-347
> Add a script to be able to clone a schema

- geoportal/c2cgeoportal_geoportal/scaffolds/create/mapserver/tinyows.xml.tmpl.mako
Put the logs where the Docker images is expecting them.
> Improve tinyows logs on Docker

- geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/nondocker-finalise.mk_tmpl
because these ones cannot be installed straight from pypi using pip, but I think that they are "dev" packages and they are not blocking any "simple" production instance (behind a simple Apache "mod_wsgi" server and in an non-Docker environment).
Please review and eventually merge (if Travis let me through for once...)
> Add some wheel installation exception when using Windows

- doc/integrator/upgrade_application.rst.mako
As it is not anymore at the root of the project path, but inside the `geoportal` folder.
I do not know it there is another way to do this, but this is currently working in the sitn project.
> Specify alembic config file in documentation

- doc/integrator/internationalization.rst
- geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
Add i18n behaviour changes of gmf 2.3
Replaces https://github.com/camptocamp/c2cgeoportal/pull/3932.
> [Doc] Fix and add target to use to update po files (not automatic)

- c2cgeoportal/lib/dbreflection.py
- c2cgeoportal/tests/functional/test_dbreflection.py
Related with https://github.com/camptocamp/aeroportdelyon_sig/issues/425
> Correctly return nillable for relations in md.xsd

- geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_vars.yaml_tmpl
Since Gunicorn has no request timeout, this is needed to avoid having
workers busy for too long if a query goes crazy.
> Introduce a PG statement_timeout of 30s

- c2cgeoportal/scaffolds/update/CONST_alembic/main/versions/7530011a66a7_trigger_on_role_updates_user_in_static.py
As this is an alembic migration backport, it will needs an alembic merge when merging commit in 2.3.
No need to empty migration as it can be executed twice without error (CREATE OR REPLACE).
> Backport fix trigger on_role_name_change through alembic.

- docker/build/bin/run
Could seems weird, but on a server I've sigdev with id 999, so I've need docker to be deleted before creating creating geomapfish.
> Avoid group collision between user group and docker

- doc/developer/debugging.rst
docker-compose.override.yaml (yaml instead of yml) is not loaded automatically.
> Fix typo in docker-compose.override.yml

- commons/c2cgeoportal_commons/alembic/main/7530011a66a7_trigger_on_role_updates_user_in_static.py
- commons/c2cgeoportal_commons/alembic/main/dba87f2647f9_merge_2_2_on_2_3.py
- docker/test-mapserver/mapserver.map.mako
- geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/mapserver/mapserver.map.mako_tmpl
- geoportal/c2cgeoportal_geoportal/views/entry.py
I had a conflict with this file:
2.2: https://github.com/camptocamp/c2cgeoportal/commit/1d28b290cc5ef106fd972e5fb58ebee3188f3489
2.3: https://github.com/camptocamp/c2cgeoportal/blob/2.3/commons/c2cgeoportal_commons/alembic/main/21f11066f8ec_trigger_on_role_updates_user_in_static.py
It's not in this merge, I think we had to move it / adapt it manually. That's why it's already on 2.3
> Merge 2.2 into 2.3

- doc/integrator/routing.rst
- geoportal/c2cgeoportal_geoportal/scaffolds/create/vars.yaml_tmpl
- geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/vars.yaml_tmpl
Tested this with @yjacolin. The previous syntax resulted in data structures that did not match the expectations of the angular code.
To explain the unusual syntax:
```
- profiles:
-
label: Car
profile: routed-car
-
label: Bike (City)
profile: routed-bike
```
This results in:
`
[{label: "Car", profile: "routed-car"}, {label: "Bike (City)", profile: "routed-bike"}]`
The `ngeoNominatimSearchDefaultParams` just don't want an array. It is supposed to be just an object.
> Fix yaml syntax to match expected data format

- geoportal/c2cgeoportal_geoportal/lib/authentication.py
Never see this "authtk" string, without the final `t`. I guess it was a typo.
Also, accept `false, False, No, no, 0` as "false value, and not only `False`.
Still `True` by default.
> Correct typo 'authtkt' for secure and http_only

- docker/build/requirements.txt
This fixes the generation of the mapcache config file.
> Upgrade tilecloud-chain to 1.8.2

- doc/integrator/upgrade_application.rst.mako
- geoportal/c2cgeoportal_geoportal/scripts/l10nv1tov2.py
- geoportal/c2cgeoportal_geoportal/scripts/themev1tov2.py
* Fix themev1tov2 and l10nv1tov2 in docker/python3 context.
* Use production.ini path from docker context by default.
* Update the documentation for docker context.
> Fix scripts themev1tov2 and l10nv1tov2 with docker

- c2cgeoportal/lib/lingua_extractor.py
- c2cgeoportal/views/layers.py
Fix regression introduced by https://github.com/camptocamp/c2cgeoportal/commit/496e2bb23194c23b99c72ed377714fc3610369dc
Mainly we shouldn't exclude the lastUpdateDateColumn and lastUpdateUserColumn on insert or update operation otherwise we can't set them.
> Don't exclude properties everywhere

- geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose.yaml.mako
It's on the entrypoint the stuff needed to bind it on port 8080
Fix: https://jira.camptocamp.com/projects/GSGMF/issues/GSGMF-731
> Fix tinyows binding on port 80

- doc/integrator/internationalization.rst
Add docker project command for update-po target.
> Add doc for translation in docker projects

- commons/acceptance_tests/test_roles.py
- commons/acceptance_tests/test_users.py
- commons/c2cgeoportal_commons/models/static.py
- geoportal/tests/functional/__init__.py
SQLAlchemy automatically delete manytomany relationtions when related entity is marked for deletion.
But this only occurs when the relationships exists on considered entity side.
Here I had the backref in User.roles so relations are also deleted when a role is marked for deletion.
As user_role records are deleted with roles, in tests we can safely delete all the users after all roles have been maked for deletion.
> [multi_role] cascade delete to user_role

- doc/integrator/raster.rst
- geoportal/c2cgeoportal_geoportal/__init__.py
- geoportal/c2cgeoportal_geoportal/views/entry.py
- geoportal/c2cgeoportal_geoportal/views/memory.py
- geoportal/c2cgeoportal_geoportal/views/profile.py
- geoportal/c2cgeoportal_geoportal/views/raster.py
- geoportal/tests/data/dem4.vrt
- geoportal/tests/test_raster.py
Remove LRU cache
Store only the first level read
Support all GDAL types (especially VRT)
Fix get point position
Add memory view
Time to get the profile throw all the riviera go from more the 70s. to less than 1s. :-)
> Fix raster profile performances

- c2cgeoportal/scaffolds/update/CONST_config-schema.yaml
- c2cgeoportal/views/pdfreport.py
In our documentation for pdfreport, we say to use for srs a string like EPSG:21781 (see https://camptocamp.github.io/c2cgeoportal/2.2/integrator/pdfreport.html).
But this is currently not possible in the code, because the srs is defined as a number. So right now, projects can only define a number here, like 2056.
And when using the number only, there is an error while printing:
```
Caused by: org.opengis.referencing.NoSuchAuthorityCodeException: No authority was defined for code "2056". Did you forget "AUTHORITY:NUMBER"?
at org.geotools.referencing.factory.ManyAuthoritiesFactory.noSuchAuthority(ManyAuthoritiesFactory.java:489)
at org.geotools.referencing.factory.ManyAuthoritiesFactory.getAuthorityFactory(ManyAuthoritiesFactory.java:467)
at …
```
> pdfreport: srs should be fully specified in configuration

- geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/nondocker-finalise.mk_tmpl
On Windows we cannot install Pyproj through pip anymore. I added this dependency as a binary wheel. Moreover, as it is a dependency of OWSlib, we have to install it first (before OWSlib).
@sbrunner, I do not know if anybody else is using `nondocker-finalise.mk`, but I would be grateful if this PR could be merged (if Travis is happy, as always...)
> Install binary wheels first on Windows

- geoportal/tests/functional/test_layers.py
- geoportal/tests/functional/test_themes_dimensions.py
- geoportal/tests/functional/test_themes_private.py
`assertEquals` is deprecated, the following warning is raised in the tests:
```
/src/geoportal/tests/functional/test_layers.py:457: DeprecationWarning: Please use assertEqual instead.
self.assertEquals(request.response.status_int, 400)
```
> Use assertEqual instead of assertEquals

- admin/MANIFEST.in
With these files, it becomes possible to install the correct version of the npm dependencies.
> Add admin npm package files to the egg

- geoportal/c2cgeoportal_geoportal/views/entry.py
I've custom wms tables (`lu_ext_wms` and `lu_int_wms`) that extend the standard `l_wms` tables. Without this (kind of) change, I can't receive them in the theme object. (Or do you have a better idea ?)
> Geoportal: Can have custom wms table delivred by the theme view

- geoportal/c2cgeoportal_geoportal/scaffolds/create/print/print-apps/+package+/config.yaml.tmpl
This was missing in the print config and the consequences was that some private layers weren't printed.
> Fix hostnameMatch in print config

- doc/developer/debugging.rst
Note that I change:
```
GUNICORN_PARAMS="-b :80 --worker-class gthread --threads 1 --workers 1 --reload"
```
By:
```
GUNICORN_CMD_ARGS=--reload
```
As I found it really less intrusive.
Note that for now demo 2.4 use:
```
--bind=:8080 --worker-class=gthread --threads=10 --workers=1 --timeout=60 --max-requests=1000 --max-requests-jitter=100
```
And we should not change the port or I miss something.
> Improve "Developing in Python" in developper doc

- Makefile
Fix warning:
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your diff.renameLimit variable to at least 633 and retry the command.
> Use the current master last commit instead of first commit

- geoportal/c2cgeoportal_geoportal/lib/lingua_extractor.py
- geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_config-schema.yaml
This PR was made for two purposes and should solve issues that we have with the layer enumeration configuration (YAML config file):
* It happens that we have None values or columns containing numbers (and defined as having to). This makes the lingua_extractor crash, thus I check for these exceptions and avoid to translate them (https://github.com/camptocamp/c2cgeoportal/compare/master...kalbermattenm:enum_translate?expand=1#diff-88967e2bdedfa9e803c46b29cd0a2e76R260)
* It happens that a DB column already contains the right translated strings, thus it is not useful to translate them. Moreover, for the SITN project and its filters, the translation process added more the 400 lines to the po file, because of that and all these translation additions are useless, we will not translate them …
> Create a variable to skip translation process in enum config

- admin/c2cgeoportal_admin/schemas/metadata.py
- admin/tests/test_metadatas.py
- commons/c2cgeoportal_commons/lib/validators.py
- commons/tests/validators_test.py
I've put the validator in commons and allowed config://
There is no validators on url fields in schema main, I've not added such validators to propose a harmless fix.
> Allow static urls in url metadatas

- c2cgeoportal/tests/functional/test_mapserverproxy.py
- c2cgeoportal/views/mapserverproxy.py
- doc/integrator/security.rst
See https://jira.camptocamp.com/browse/GEO-1749
> add an authentication_required option

- geoportal/c2cgeoportal_geoportal/views/tinyowsproxy.py
Layer with uppercase characters in the name where always returning error
403.
> Fix the tinyows proxy auth to work with uppercases

- geoportal/c2cgeoportal_geoportal/lib/wmstparsing.py
In python 2, we have `max(None, None) == None`. In python 3, we have
`max(None, None) => raise TypeError`.
> Fix WMST enumerated time extent with only one limit

- doc/developer/build_release.rst.mako
- doc/developer/debugging.rst
- doc/integrator/fulltext_search.rst
- doc/integrator/ngeo_new_interface.rst
- doc/integrator/objectstorage.rst
- doc/integrator/upgrade_application.rst.mako
> Use predefined shp2img commond for debugging

- geoportal/c2cgeoportal_geoportal/views/dynamic.py
that come from the Const_vars.yaml, without changing the update_paths.
Fix https://jira.camptocamp.com/browse/GSGMF-949
> Be able to cancel a dynamic_constants

- admin/package.json
- admin/requirements.txt
- doc/requirements.txt
- docker/qgisserver/requirements.txt
- requirements-dev.txt
- requirements.txt
Fix: https://jira.camptocamp.com/browse/GSGMF-981
> Use compatible version

- doc/integrator/filter.rst
@sbrunner I target branch 2.2, but there is no more milestone. Is my PR okay ?
Also is this notes correct to you (I wanted to clarify that it's a current limitation of ngeo)
> Doc - Ngeo support filter on single layers only

- ci/test-app
- ci/test-new-project
- ci/vars.yaml
- geoportal/c2cgeoportal_geoportal/__init__.py
- geoportal/c2cgeoportal_geoportal/lib/checker.py
- geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/vars.yaml_tmpl
The working part of https://github.com/camptocamp/c2cgeoportal/pull/5144
> Fix phantom js checks

- requirements.txt
See https://github.com/andymccurdy/redis-py/issues/1200 for the reason.
> Rollback to redis 3.3.4

- doc/developer/webservices.rst
Target 2.2.
I also can remove the difference by adding or removing the header:
- https://github.com/elemoine/papyrus/blob/master/papyrus/__init__.py#L34-L38
- https://github.com/camptocamp/c2cgeoportal/blob/2.2/c2cgeoportal/pyramid_.py#L679-L684
> Doc - Update doc for create/update feature on webservice layers

- geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+travis.yml_tmpl
- geoportal/c2cgeoportal_geoportal/scaffolds/create/scripts/deploy-docker
The OPENSHIFT_TOKEN environment variable is automatically added by the
`get_ci_tokens` script in private-geo-charts.
> Switch to a token for OpenShift Auth in Travis

- doc/integrator/database.rst
- geoportal/c2cgeoportal_geoportal/views/layers.py
https://jira.camptocamp.com/browse/GSGMF-1101
> Be able to have dynamic geo_table

- docker/qgisserver/geomapfish_qgisserver/accesscontrol.py
- docker/qgisserver/tests/functional/accesscontrol_test.py
* Support layer short names and WMSUseLayerIDs
* Support roles == "ROOT" in get_area
> Support layer short names and WMSUseLayerIDs

- geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl
Example:
DOCKER_BUILD_ARGS += --build-arg http_proxy=http://proxy:9090
DOCKER_BUILD_ARGS += --build-arg https_proxy=http://proxy:9090
> Allow build behind proxy

- ci/publish
- geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/Dockerfile_tmpl
For the run and default geoportal images to be able to rebuild them daily to get all the security upgrades
> Use only the major version tag

- geoportal/c2cgeoportal_geoportal/views/entry.py
Fallback for the strand type when we use
the METADATA gml_types" "auto"
Needed for https://jira.camptocamp.com/browse/GSGMF-1133
> Fix attrubutes for MapServer

- geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose-lib.yaml_tmpl
* Was: allkeys-lru -> Evict any key using approximated LRU.
* Now: volatile-lru -> Evict using approximated LRU among the keys with an expire set.
That supresses the risk of having tilecloud-chain and broadcast queues deleted.
See also: https://github.com/camptocamp/private-geo-charts/pull/26
> Switch redis to volatile-lru

- geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_vars.yaml_tmpl
- geoportal/c2cgeoportal_geoportal/views/dynamic.py
- geoportal/tests/functional/test_dynamicview.py
Currently
```
constants:
gmfSearchActions: []
```
don't override
```
dynamic_constants:
gmfSearchGroups: fulltextsearch_groups
```
> Fix interface override defaults

- doc/integrator/create_application.rst.tmpl
The master doc indicates that one can list the existing scaffolds typing:
```
docker run --rm --volume=$(pwd):/src \
camptocamp/geomapfish-tools:<release|version> \
pcreate -l
```
See https://camptocamp.github.io/c2cgeoportal/master/integrator/create_application.html#list-existing-scaffolds
On the other hand the scaffolding commands omit the ``--volume`` parameter:
```
docker run --rm -ti \
camptocamp/geomapfish-tools:<release|version> \
run $(id -u) $(id -g) /src \
pcreate -s c2cgeoportal_create <project>
```
See https://camptocamp.github.io/c2cgeoportal/master/integrator/create_application.html#create-the-new-application
I think this prevents from making the project available in the local file system.
> Add missing volume arg in scaffolding commands

- geoportal/c2cgeoportal_geoportal/views/fulltextsearch.py
Fix: https://sentry.io/organizations/camptocamp/issues/1396111348/
> The character <> are not allowed in a fulltext search request

- doc/administrator/editing.rst
- geoportal/c2cgeoportal_geoportal/views/layers.py
variables as a gigantic string and the code fail wonderfully.
export TOTO=foobar
python
>>> import os
>>> print('{TOTO}'.format(**os.environ))
foobar
> without the double star, the formating inject all the environment

- geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl
Spell check by default in CI is really boring.
> Remove spell check from CI in scaffold

- docker/qgisserver/geomapfish_qgisserver/accesscontrol.py
- docker/qgisserver/tests/functional/accesscontrol_test.py
Fix https://jira.camptocamp.com/browse/GSGMF-1209
The main issue is that the anonymous users should be linked to the anonymous group, and the intranet users should be linked to the intranet group.
> Fix QGIS server on intranet and annonymous

- doc/administrator/editing.rst
- doc/integrator/docker.rst
This PR adds instructions to remove "ghost" volumes, as described at https://techan.fr/docker-chasse-a-lespace-perdu-gare-aux-volumes.html > "Les volumes “fantômes”", pointed by @yjacolin 
By the way I have dropped a reference to ExtJS in the documentation opening page :P 
(Doc successfully built on my laptop)
> Add tip about unused docker volumes cleaning

- commons/c2cgeoportal_commons/lib/email_.py
And do not send not encrypted credentials over network
Backport #5557
> Start TLS before login on SMTP server

- commons/c2cgeoportal_commons/alembic/main/87f8330ed64e_add_missing_delete_cascades.py
- commons/c2cgeoportal_commons/alembic/static/107b81f5b9fe_add_missing_delete_cascades.py
- commons/c2cgeoportal_commons/models/main.py
- commons/c2cgeoportal_commons/models/static.py
Add missing delete cascades.
In case of n-n relationship, we can safely cascade deletes to relationships (to avoid having to delete manually all relationships before to delete related entities).
Superseed https://github.com/camptocamp/c2cgeoportal/pull/5778
Note that this PR also fix some other differences between Alembic migrations and SQLAlchemy model like `nullable=False` or `unique=False` (detected by alembic revision --autogenerate).
> Add missing delete cascades

- geoportal/c2cgeoportal_geoportal/scaffolds/create/Dockerfile_tmpl
- geoportal/c2cgeoportal_geoportal/scaffolds/create/qgisserver/geomapfish.yaml.tmpl_tmpl
- geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_config-schema.yaml
- geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl
sqlalchemy.exc.SADeprecationWarning: The psycopg2 use_batch_mode flag is superseded by executemany_mode='batch'
Fix GSGMF-1248
> Removes SQLalchemy warning

- geoportal/c2cgeoportal_geoportal/lib/lingua_extractor.py
Currently, I get on `update-po`:
```
Traceback (most recent call last):
File "/usr/local/bin/pot-create", line 11, in <module>
sys.exit(main())
File "/usr/local/lib/python3.6/dist-packages/lingua/extract.py", line 336, in main
for message in extractor(real_filename, options):
File "/opt/c2cgeoportal_geoportal/c2cgeoportal_geoportal/lib/lingua_extractor.py", line 218, in __call__
return self._collect_app_config(filename)
File "/opt/c2cgeoportal_geoportal/c2cgeoportal_geoportal/lib/lingua_extractor.py", line 247, in _collect_app_config
init_dbsessions(settings, config_)
File "/opt/c2cgeoportal_geoportal/c2cgeoportal_geoportal/__init__.py", line 689, in init_dbsessions
config, 'sqlalchemy', slave_prefix, force_master=master_paths, force_slave=slave_paths)
File …
```
> Add get_settings used by c2cwsgiutils

- Pipfile
- Pipfile.lock
- geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/alembic.ini
Upgrade GetItFixed for various fixes.
In alembic config, schema name configuration is not really supported at runtime in getitfixed and this setting overlap with GMF main schema config key.
> Upgrade c2cgeoform and getitfixed

- Dockerfile.mako
This is just a hack to invalidate docker intermediate cache on Jenkins servers.
This might be reverted at some time.
> Invalidate Jenkins docker cache

- geoportal/c2cgeoportal_geoportal/scripts/manage_users.py
Replace entrypoint ``manage-users`` by ``manage_users`` as the filename is actually ``manage_users.py`` and as it is the spelling actually used in the doc examples, see https://github.com/camptocamp/c2cgeoportal/blob/2.4/geoportal/c2cgeoportal_geoportal/scripts/manage_users.py#L42-L47
> Fix typo in manage-users script doc

- geoportal/c2cgeoportal_geoportal/views/pdfreport.py
I think in pdfreport the OGCProxy should be initialized the same way as here https://github.com/camptocamp/c2cgeoportal/blob/f2b2c66f2352dd95438089d4d0cfb619c4f070f8/geoportal/c2cgeoportal_geoportal/views/tinyowsproxy.py#L52, otherwise the initialisation will always fail.
> Initialize OGCProxy like it is done for TinyOWSProxy

- geoportal/c2cgeoportal_geoportal/views/theme.py
This is useless for now and we won't request a GetCapabilities by OGC Server and each roles combination in the future.
> Remove roles from capabilities cache key

- geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose-lib.yaml_tmpl
Fix GSGMF-1395
The PGSCHEMA should come from the Docker image for the geoportal service and from the .env for the tools service...
> Fix: update-po doesn't use PGSCHEMA defined in .env file

- doc/developer/server_side.rst.tmpl
`make docker-build ` still correct in 2.4. Is now `make build`
> Fix build command in documentation

- geoportal/c2cgeoportal_geoportal/scaffolds/create/print/print-apps/+package+/A3_Landscape.jrxml
- geoportal/c2cgeoportal_geoportal/scaffolds/create/print/print-apps/+package+/A3_Portrait.jrxml
- geoportal/c2cgeoportal_geoportal/scaffolds/create/print/print-apps/+package+/A4_Landscape.jrxml
- geoportal/c2cgeoportal_geoportal/scaffolds/create/print/print-apps/+package+/A4_Portrait.jrxml
- geoportal/c2cgeoportal_geoportal/scaffolds/create/print/print-apps/+package+/config.yaml.tmpl
DateTimeFormatter is more flexible than SimpleDateFormat for print templates
as we can chain setting pattern, timezone and locale in a textFieldExpression.
> Use DateTimeFormatter in print templates

- .github/workflows/main.yaml
It's not so good, but the c2cgeoportal build creates an image named `camptocamp/geomapfish-config` and the `create-new-project` with his build creates an image with the same name...
> Push the right image

- geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+env.mako_tmpl
Adapt Gunicorn tmpdir setting for Docker environment, to avoid locks (see https://pythonspeed.com/articles/gunicorn-in-docker/ )
> Gunicorn: adapt tmpdir setting for Docker environment

- geoportal/c2cgeoportal_geoportal/lib/dbreflection.py
- geoportal/c2cgeoportal_geoportal/lib/xsd.py
- geoportal/tests/functional/test_dbreflection.py
- geoportal/tests/functional/test_xsd.py
_AssociationProxy.value_attr need to be a str not a InstrumentedAttribute.
See getattr(target, self.value_attr) in _AssociationProxy.__get__ and _AssociationProxy.__set__.
Note it is the same in sqlalchemy.ext.associationproxy.AssociationProxy.
For consistency, do the same for _AssociationProxy.order_by (not InstrumentedAttribute but str).
> Fix editingEnumerations

- geoportal/c2cgeoportal_geoportal/scaffolds/create/print/print-apps/+package+/legend.jrxml
- geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
For GSGMF-1367
Ngeo part for hierarchical groups: https://github.com/camptocamp/ngeo/pull/6692
Ngeo part to keep current flat legend: https://github.com/camptocamp/ngeo/pull/6725/files 
@jwkaltz can you review the Changelog please ?
I've added a [level-1 * 10px] indentation for level 2-5. Then more levels will have the same indentation as the 5th.
I've not found any better solution for indentation than these `if levels == x` and repeated statements. We can't have variable in attributes, nor loops in xml, nor spaces before element (as we use sub-report for images).
Also, we don't have a lot of possibilities for the design as we can't know if we have only a title or a title and a image for a specific level. (The print generate two different reports for title and image, and in a jrxml we are …
> Indent print legend per groups

- geoportal/c2cgeoportal_geoportal/scripts/urllogin.py
config.yaml is now in /etc/geomapfish
For consistency use the same arguments as in other scripts.
> Fix config.yaml path in urllogin script

- docker/build/requirements.txt
+============================+===========+==========================+==========+
| package                    | installed | affected                 | ID       |
+============================+===========+==========================+==========+
| bottle                     | 0.12.16   | <0.12.19                 | 39461    |
+==============================================================================+
| The package bottle from 0 and before 0.12.19 are vulnerable to Web Cache     |
| Poisoning by using a vector called parameter cloaking. When the attacker can |
| separate query parameters using a semicolon (;), they can cause a difference |
| in the interpretation of the request between the proxy (running with default |
| configuration) and the server. This can result in malicious requests …
> Fix security issue

- geoportal/c2cgeoportal_geoportal/lib/__init__.py
- geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
- geoportal/c2cgeoportal_geoportal/views/theme.py
- geoportal/tests/functional/test_themes_mixed.py
This is to use the parameters that are given in the OGC server URL instead of overwriting with default values (-> use a specific WMS version)
> Use WMS version from OGC server URL to GetCapabilities 

- geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_config-schema.yaml
Required to set its value using an environment variable and avoid build error such as
```
Value '{ENABLE_ADMIN_INTERFACE}' is not of type 'bool'.
```
Thanks @sbrunner for your help!
Example of related changes in a project: https://github.com/camptocamp/lausanne_mapfish/pull/29/files
I have tested that the default behaviour still works with the change proposed in the current PR.
> Make config enable_admin_interface scalar

- doc/administrator/mapfile.rst
- doc/developer/cache.rst
- doc/developer/custom_alembic.rst
- doc/developer/debugging.rst
- doc/developer/index.rst
- doc/developer/server_side.rst.tmpl
- doc/integrator/backend_qgis.rst
- doc/integrator/create_application.rst.tmpl
- doc/integrator/functionality.rst
- doc/integrator/requirements.rst
Add instruction to run alembic on a custom schema or on custom tables (GMF 2.5).
I don't have seen better solution. The setup is a little bit long, but it works well then.
Fix also some typo.
(I've added some reviewers only to inform them that this page exist now.)
> Doc - Add custom alembic

- geoportal/c2cgeoportal_geoportal/scaffolds/create/env.default_tmpl
We had several users reporting GMF crashes with long URLs (GMF has often permalink with a lot of params) such as:
```
Request Line is too large (5722 > 4094)
```
This is related to Gunicorn limiting by default URLs to 4094 chars: https://docs.gunicorn.org/en/stable/settings.html#limit-request-line
The PR suggests to get rid of the Gunicorn default limit.
> Remove default URL length limit in Gunicorn

- doc/administrator/administrate.rst.tmpl
- doc/administrator/editing.rst
This PR adds a section to https://camptocamp.github.io/c2cgeoportal/master/administrator/editing.html giving tips about excluded or readonly attributes while editing.
Excluded properties are already mentioned at https://camptocamp.github.io/c2cgeoportal/master/administrator/administrate.html#common-attributes but that's worth mentioning it in the Editing chapter as well.
> Add doc about excluded or readonly attributes while editing

- geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
For GSGMF-1526
I've tried to improve the explanation of the relocation of the config to the vars.yaml file.
I'm a little bit less concise, with some repetitions but if think that's more logical for a less experimented user.
Questions:
- I use `geoportal/<project_package>_geoportal/` syntaxe, can we do better ? (like `geoportal/${project_package}_geoportal/` ?)
- Could we add a link to a doc that explain yaml section template`&mysection`, `*mysection`
The only section I've removed is this one, thinking it's too technical and not necessary in the changelog:
```
Then configure the `vars/srid`, `vars/alternate_projections`, `vars/resolutions` and `vars/extent` they will
be dispatched using `c2ctemplate` or YAML link.
```
> Improve changelog about the relocation of the config to the vars.yaml

- geoportal/c2cgeoportal_geoportal/views/dynamic.py
Fix GSGMF-1589
```python                                                                                                               
>>> import json                                                                                                
>>> import ujson                                                                                               
>>> json.dumps(float('inf'))                                                                                   
'Infinity'                                                                                                     
>>> ujson.dumps(float('inf'))                                                                                  
'Inf' 
```
> Ujson used by fast_json didn't handle correctly the value infinity

- geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/vars.yaml_tmpl
It seems this is not used in c2cgeoportal, therefore it should be removed from the template.
> Remove unused vars section

- Pipfile
- Pipfile.lock
Fix: tx ERROR: No module named 'chardet'
> Add missing dependency for Transifex since requests 2.26

- geoportal/c2cgeoportal_geoportal/scaffolds/create/ci/trigger
e.g. we can have a branch named 'int-2-6', currently the image stream should be names `int-2-6-c2cgeoportal-config:int-2-6` and the real names are: `int-org1-2-6-c2cgeoportal-config:int-2-6` and `int-org2-2-6-c2cgeoportal-config:int-2-6` we can call:
```
ci/trigger --image-stream-name={env}-org1-{version_only}-c2cgeoportal-{image}:{version} --image-stream-name={env}-org2-{version_only}-c2cgeoportal-{image}:{version}
```
> Be able to have multiple instance of an application

- admin/c2cgeoportal_admin/lib/ogcserver_synchronizer.py
- admin/c2cgeoportal_admin/templates/ogcserver_synchronize.jinja2
- admin/c2cgeoportal_admin/views/ogc_servers.py
- admin/tests/lib/test_ogcserver_synchronizer.py
In OGCServer synchronize, add checkbox to remove layers which does not exist in WMS capabilities and all empty groups.
> Add clean option in OGCServerSynchronizer

- geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+github/workflows/rebuild.yaml_tmpl
- geoportal/c2cgeoportal_geoportal/scaffolds/create/ci/trigger
Currently, the demo 2.6 rebuild pushes on the tag prod-2-7 :-/
=> will fix: https://sentry.io/organizations/camptocamp/issues/2570578340/?environment=prod-2-7&project=1851011&referrer=alert_email
> Fix the rebuild

- doc/integrator/headers.rst
- geoportal/c2cgeoportal_geoportal/scaffolds/create/Dockerfile_tmpl
- geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_config-schema.yaml
- geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl
- geoportal/c2cgeoportal_geoportal/views/proxy.py
- geoportal/tests/functional/__init__.py
- geoportal/tests/functional/test_themes_mixed.py
For GEO-4639
Add blacklist/whitelist system for headers.
Add docs.
@sbrunner Are you sure you don't want to add this feature per url like the global_header system ? 
```
vars:
global_headers:
- pattern: <regex>
headers:
<header>: <value>
```
It looks risky, or possibly problematic to apply these lists on all request going through the proxy.
(@jwkaltz it's for Agrola, but I add you especially to review the documentation)
> Add blacklist whitelist for headers

- geoportal/c2cgeoportal_geoportal/views/proxy.py
Clean fix for GEO-4666.
I'll backport it manually in 2.4 as some previous line interest me too.
I expect having `headers[Forwarded]` string like that:
`'by=0.0.0.0;for=134.12.1.1;host=123.12.1.1;proto=https,for=172.12.1.1'`
And transform them like that:
- `'X-Forwarded-By': '0.0.0.0`
- `'X-Forwarded-For': '134.12.14.2, 989.98.98.8'`
- `'X-Forwarded-Host': '123.12.12.12'`
- `'X-Forwarded-Proto': 'https'`
See also https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded
> Add alternative X-Forward headers in proxy

- Pipfile
- Pipfile.lock
```
+==============================================================================+
|                                                                              |
|                               /$$$$$$            /$$                         |
|                              /$$__  $$          | $$                         |
|           /$$$$$$$  /$$$$$$ | $$  \__//$$$$$$  /$$$$$$   /$$   /$$           |
|          /$$_____/ |____  $$| $$$$   /$$__  $$|_  $$_/  | $$  | $$           |
|         |  $$$$$$   /$$$$$$$| $$_/  | $$$$$$$$  | $$    | $$  | $$           |
|          \____  $$ /$$__  $$| $$    | $$_____/  | $$ /$$| $$  | $$           |
|          /$$$$$$$/|  $$$$$$$| $$    |  $$$$$$$  |  $$$$/|  $$$$$$$           |
|         |_______/  \_______/|__/     \_______/   \___/   \____ …
```
> Bump dependency with security issue

- .tx/config.mako
- ci/test-app
- dependencies.mk
- doc/integrator/internationalization.rst
- geoportal/c2cgeoportal_geoportal/__init__.py
- geoportal/c2cgeoportal_geoportal/scaffolds/create/Dockerfile_tmpl
- geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_config-schema.yaml
- geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl
- geoportal/c2cgeoportal_geoportal/views/dynamic.py
- geoportal/tests/functional/test_dynamicview.py
The idea is to offer the i18next configuration from `dynamic.json`.
With the project, can create a static view on '/static-project' with some locales file in the namespace project.
ngeo part: https://github.com/camptocamp/ngeo/pull/7646
> Add configuration for i18next

- geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
Fix for 2.5.
It was fixed directly in the backports of 2.6/master in the previous PR  #8860.
> Typo changelog

- geoportal/c2cgeoportal_geoportal/lib/oauth2.py
Changes:
- Add some logs
- Change the result of `client_authentication_required`, the consequence is that we use the function `authenticate_client_id` instead of `authenticate_client`.
- `authenticate_client` => unimplemented
> Fix code verification in oauth2

- Dockerfile
- admin/docker-compose.yaml
- bin/import-ngeo-apps
- build.mk
- ci/create-new-project
- ci/docker-compose.override.yaml
- ci/test-app
- ci/vars.yaml
- doc/integrator/extend_application.rst
- doc/integrator/features.rst
- docker-compose.yaml
- docker/qgisserver/docker-compose.yaml
- geoportal/c2cgeoportal_geoportal/__init__.py
- geoportal/c2cgeoportal_geoportal/scaffolds/advance_create/geoportal/+package+_geoportal/__init__.py_tmpl
- geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+dockerignore_tmpl
- geoportal/c2cgeoportal_geoportal/scaffolds/create/Dockerfile_tmpl
- geoportal/c2cgeoportal_geoportal/scaffolds/update/+dot+upgrade.yaml_tmpl
- geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_config-schema.yaml
- geoportal/c2cgeoportal_geoportal/views/entry.py
The goal of this pull request is to be able to have the template of the desktop application base on the canvas (from desktop-alt) in the config container (for simple application).
The js and the css will come from ngeo directly.
> Move the interface based on a canvas to the config Docker image

- bin/run-git
- geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py
Currently on the demo advance we have the following status:
```
M  CONST_create_template/.dockerignore
M  CONST_create_template/Dockerfile
M  CONST_create_template/geoportal/geomapfish_geoportal/__init__.py
M  CONST_create_template/geoportal/geomapfish_geoportal/locale/de/LC_MESSAGES/geomapfish_geoportal-client.po
M  CONST_create_template/geoportal/geomapfish_geoportal/locale/fr/LC_MESSAGES/geomapfish_geoportal-client.po
M  CONST_create_template/geoportal/geomapfish_geoportal/locale/it/LC_MESSAGES/geomapfish_geoportal-client.po
M  CONST_create_template/geoportal/geomapfish_geoportal/static-ngeo/js/apps/Controllerdesktop.js
D  CONST_create_template/geoportal/geomapfish_geoportal/static-ngeo/js/apps/Controllerdesktop_alt.js
M  CONST_create_template/geoportal/geomapfish_geoportal/static-ngeo/ …
```
> Fix for rename

- geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/build
Like:
WARNING: The GIT_HASH variable is not set. Defaulting to a blank string.
WARNING: The SIMPLE variable is not set. Defaulting to a blank string.
> Move the env to the .env file to avoid warning

- geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/geoportal/vars.yaml
- geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_vars.yaml
Current warning:
```
The key 'starttls' in '.smtp' is not present in: ['host', 'password', 'ssl', 'user']
```
> Add default values to avoid warning

- bin/yamlutils
This PR adds a small script that flattens a yaml file. So for example:
```bash
cat << EOF > /tmp/file.yaml
---
a:
aa:
- 1
- 2
ab:
- name: first
value: firstvalue
- name: second
value: secondvalue
b:
baa:
merli:
x: 1
y:
toto:
bip:
- 12
- 24
kiki: 42
ba: 3
df:
xyz: 10
bb: 4
EOF
```
gives the follow output when parsed by the script:
```bash
./yamlutils /tmp/file.yaml 
a.aa=1
a.aa=2
a.ab.name=first
a.ab.value=firstvalue
a.ab.name=second
a.ab.value=secondvalue
b.ba=3
b.bb=4
b.baa.merli.x=1
b.baa.merli.y.kiki=42
b.baa.merli.y.toto.bip=12
b.baa.merli.y.toto.bip=24
b.df.xyz=10
```
the script can be run in both a shell pipe or reading from a file
```bash
./yamlutils /tmp/file.yaml
cat /tmp/file.yaml | ./yamlutils
```
> Add basic yamlutils script

- docker/qgisserver/logging.ini
If we do not manage to set stream as optional, this fix QGIS server logging init.
https://github.com/camptocamp/c2cgeoportal/pull/9400
> Fix QGIS server logging init

- geoportal/c2cgeoportal_geoportal/views/layers.py
The layer.exclude_properties should always be used to don't break the
Dogpile cache, and create tow SQLAlchemy Table on the same database table.
> Fix the editing

- Dockerfile
- geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/build
With that, `./build --no-pull --fast-reload` takes about 23s.
> Faster fast reload

- admin/c2cgeoportal_admin/views/ogc_servers.py
- admin/tests/conftest.py
- commons/c2cgeoportal_commons/models/main.py
- geoportal/c2cgeoportal_geoportal/__init__.py
- geoportal/c2cgeoportal_geoportal/lib/caching.py
- geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/geoportal/vars.yaml
- geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_vars.yaml
- geoportal/c2cgeoportal_geoportal/views/theme.py
- geoportal/tests/__init__.py
- geoportal/tests/config.yaml
- geoportal/tests/functional/__init__.py
- geoportal/tests/functional/test_dbreflection.py
- geoportal/tests/functional/test_dynamicview.py
- geoportal/tests/functional/test_themes_ogc_server_cache_clean.py
Tested on demo, at home throw VPN on my slow new computer
GSLUX-460
Before:
First: 33.6s
Second: 0.7s
After Layer change: 34.6s
After OGC server change: 32.4s
After:
First: 43.6s
Second: 0.9s
After Layer change: 4.1s
After OGC server change: 4.1s (But we should wait that the background task ended, about 20s)
> Have a separate cache for the OGC servers

- .github/workflows/main.yaml
- ci/test-upgrade
This reverts commit 28d3e4f23b835f82250022b22e54401619636907.
> Revert "Remove the upgrade test from 2.6 to fix the CI"

- docker/qgisserver/.snyk
Upgrade wheel@0.34.2 to wheel@0.38.0 to fix
✗ Regular Expression Denial of Service (ReDoS) (new) [Medium Severity][https://security.snyk.io/vuln/SNYK-PYTHON-WHEEL-3092128] in wheel@0.34.2
introduced by wheel@0.34.2
> Ignore CVE

- geoportal/c2cgeoportal_geoportal/views/theme.py
In my case, the `type_namespace` is `'ogc'`
and `child.nsmap.keys()` is `[None]`, 
when I test the XSD with some online validator they return the same kind of error.
> Some fix for server that returns wrong XSD

- geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/.github/workflows/update_l10n.yaml
- scripts/get-version
See: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Upgrade deprecated set-output commands

- geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/build
- better display the command
- exit on error instead of raise an exception
Example in separate example (executing `run(args, ['ls', '-l', 'toto'], exit_on_error=True)`):
Previous result:
```
ls: impossible d'accéder à 'toto': Aucun fichier ou dossier de ce type
Traceback (most recent call last):
File "/home/sbrunner/workspace/c2cgeoportal/test.py", line 61, in <module>
run(args, ['ls', '-l', 'toto'], exit_on_error=True, check=True)
File "/home/sbrunner/workspace/c2cgeoportal/test.py", line 27, in run
process = subprocess.run(command, **kwargs)  # nosec
File "/usr/lib/python3.10/subprocess.py", line 524, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ls', '-l', 'toto']' returned non-zero exit status 2.
```
Current result:
```
ls: impossible …
```
> Avoid exception on subprocess error

- geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose-lib.yaml
Already fixed in 2.8, not relevant in 2.6.
> Fix webpack_dev_server build with buildkit

- admin/c2cgeoportal_admin/views/logs.py
- admin/tests/test_logs.py
Follow testbook review.
I prefer to ask tester to check default sort is date desc instead of asking him to sort by date desc.
> Admin - Set default default sort on logs to date desc

- geoportal/c2cgeoportal_geoportal/views/entry.py
We need to pass through authentication for the urllogin auth parameter to be converted in a cookie when requesting some Ngeo interface.
Note that I openned this PR directly on 2.7 as it seems safe to call request.user in a view.
> Add call to request.user in Entry.get_ngeo_index_vars

- admin/c2cgeoportal_admin/__init__.py
- doc/integrator/authentication.rst
- geoportal/c2cgeoportal_geoportal/__init__.py
- geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/geoportal/vars.yaml
- geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/CONST_CHANGELOG.txt
- geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_config-schema.yaml
- geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_vars.yaml
- geoportal/c2cgeoportal_geoportal/views/login.py
- geoportal/c2cgeoportal_geoportal/views/shortener.py
- geoportal/c2cgeoportal_geoportal/views/theme.py
- geoportal/tests/functional/__init__.py
- geoportal/tests/functional/conftest.py
- geoportal/tests/functional/test_login.py
- geoportal/tests/functional/test_oauth2.py
- geoportal/tests/functional/test_shortener.py
- geoportal/tests/functional/test_themes_ogc_server_cache_clean.py
- geoportal/tests/test_init.py
✗ [Medium] Open Redirect
Path: geoportal/c2cgeoportal_geoportal/views/login.py, line 196
Info: Unsanitized input from an HTTP parameter flows into pyramid.httpexceptions.HTTPFound, where it is used as an URL to redirect the user. This may result in an Open Redirect vulnerability.
✗ [Medium] Open Redirect
Path: geoportal/c2cgeoportal_geoportal/views/login.py, line 240
Info: Unsanitized input from an HTTP parameter flows into pyramid.httpexceptions.HTTPFound, where it is used as an URL to redirect the user. This may result in an Open Redirect vulnerability.
✗ [Medium] Open Redirect
Path: geoportal/c2cgeoportal_geoportal/views/theme.py, line 1206
Info: Unsanitized input from an HTTP parameter flows into pyramid.httpexceptions.HTTPFound, where it is used as an URL to redirect the user. This …
> Fix Open Redirect, simplify and uniformize the checks

- scripts/clone_schema.sql
Add missing space to script. In some versions of PostgreSQL, the missing space is problematic (tested with PostgreSQL 15).
> Add missing space to script

- geoportal/c2cgeoportal_geoportal/scaffolds/advance_create/{{cookiecutter.project}}/geoportal/gunicorn.conf.py
The preload mode don't looks to works with the broadcasting of
c2cwsgiutils.
See: https://docs.gunicorn.org/en/stable/settings.html#preload-app
> Remove wrong preload option 

- geoportal/c2cgeoportal_geoportal/lib/dbreflection.py
- geoportal/c2cgeoportal_geoportal/views/layers.py
Be able to use existing table
Don't do 2 updates per editing:
In papyrus, there is a flush that creates a first INSERT or UPDATE
The idea is to update the fields in the before_* callback to avoid having two REQUESTS
See JIRA issue: [GSSIT-114](https://camptocamp.atlassian.net/browse/GSSIT-114).
[GSSIT-114]: https://camptocamp.atlassian.net/browse/GSSIT-114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Don't do 2 SQL updates per editing

- .github/workflows/main.yaml
- geoportal/c2cgeoportal_geoportal/scripts/__init__.py
- geoportal/c2cgeoportal_geoportal/scripts/urllogin.py
This will avoid using generic arguments instead of `valid`.
> Fix URL login arguments

- doc/integrator/configuration.rst
- doc/integrator/interface.rst
- geoportal/c2cgeoportal_geoportal/__init__.py
- geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/Dockerfile
- geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_config-schema.yaml
- geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_vars.yaml
- geoportal/c2cgeoportal_geoportal/views/entry.py
- poetry.lock
- pyproject.toml
To be able to integrate interface that not be build with the GeoMapGish build chain.
Also be able to configure some static files: `favicon.ico`, `robot.txt`, `api.js`, `api.js.map`, `api.css`, `apihelp.html`.
See JIRA issue: [GSNGEO-9](https://camptocamp.atlassian.net/browse/GSNGEO-9).
TODO in another Pull request:
[GSNGEO-9]: https://camptocamp.atlassian.net/browse/GSNGEO-9?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add custom interface type

- geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.override.sample.yaml
The new version waitress didn't do that correctly
Requires: https://github.com/camptocamp/c2cwsgiutils/pull/2523
> Force to use https in dev mode

- geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.override.sample.yaml
The new version waitress didn't do that correctly
Requires: https://github.com/camptocamp/c2cwsgiutils/pull/2523
> Fix force to use https in dev mode

- geoportal/c2cgeoportal_geoportal/__init__.py
- geoportal/c2cgeoportal_geoportal/lib/common_headers.py
- geoportal/tests/functional/test_login.py
- geoportal/tests/functional/test_oauth2.py
- geoportal/tests/test_caching.py
Also add missing items in the `Vary` header
> Add missing cors view of the themes view

- doc/integrator/raster.rst
- geoportal/c2cgeoportal_geoportal/views/profile.py
- geoportal/c2cgeoportal_geoportal/views/raster.py
Allow to use a profile service to get an elevation profile or a simple elevation.
> Get profile and height from service

- geoportal/c2cgeoportal_geoportal/lib/common_headers.py
- geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/CONST_CHANGELOG.txt
- geoportal/tests/functional/test_mapserverproxy.py
- geoportal/tests/functional/test_oauth2.py
- geoportal/tests/test_caching.py
This is not working with intranet detection
To make it working (with intranet detection and reverse proxy cache) without the possibility of cache pollution, we should:
- Disable it for the loginuser end-point.
- Be sure that we have the user or roles in the query string, And verify them in the Pyramid view.
> Remove cache-control switch from private to public

- geoportal/c2cgeoportal_geoportal/scripts/pcreate.py
Fix #11570
See JIRA issue: [GSGMF-2105](https://camptocamp.atlassian.net/browse/GSGMF-2105).
[GSGMF-2105]: https://camptocamp.atlassian.net/browse/GSGMF-2105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Replace epsg.io by pyproj

- geoportal/c2cgeoportal_geoportal/views/login.py
When we want to access to the admin interface with oidc and with a user that's not allowed to access to the admin interface.
> Don't have an authenticatication loop

- .github/workflows/rebuild-qgis-2-7.yaml
> QGIS 2.7 rebuild: ltr-debug didn't exists

- doc/integrator/shortener.rst
- geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_vars.yaml
The default create_route do the job
and it create an issue for multi-tenant instance.
See JIRA issue: [GSGMG-4](https://camptocamp.atlassian.net/browse/GSGMG-4).
[GSGMG-4]: https://camptocamp.atlassian.net/browse/GSGMG-4?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove the shortner base_url

- .github/workflows/ngeo-2-7.yaml
- .github/workflows/ngeo-2-8.yaml
Avoid error:
Failed to build PyYAML
ERROR: Could not build wheels for PyYAML, which is required to install pyproject.toml-based projects
> Fix workflow ngeo-2-7

- geoportal/c2cgeoportal_geoportal/__init__.py
To be able to fully use OGC API requests via the geoportal proxy, also PUT, POST and DELETE methods must be accepted and forwarded to a QGIS Server instance.
> Accept and POST, PUT, DELETE methods for OGC API Features part 4 (editing)

- doc/integrator/authentication_oidc.rst
- geoportal/c2cgeoportal_geoportal/__init__.py
- geoportal/c2cgeoportal_geoportal/lib/oidc.py
- geoportal/c2cgeoportal_geoportal/views/theme.py
- geoportal/tests/__init__.py
- geoportal/tests/functional/__init__.py
- geoportal/tests/functional/test_themes_ogc_server_cache_clean.py
- Be able to ignore role that's not existing in the GeoMapFish database
- Be able to have a template in match to be able to combine field
- Don't hardcode the 'role_admin' to be able to configure any roles in the default context (Root)
See JIRA issue: [GSEPF-995](https://camptocamp.atlassian.net/browse/GSEPF-995).
[GSEPF-995]: https://camptocamp.atlassian.net/browse/GSEPF-995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OIDC: Be able to ignore role, to have template in match

- geoportal/c2cgeoportal_geoportal/views/theme.py
- geoportal/tests/functional/test_themes_private.py
Forgot the public attribute of themes.
The client app can then combine public attributes of the theme and the layers to determine if data can be considered restricted or not.
> Export the public attribute defined for themes

- geoportal/c2cgeoportal_geoportal/views/login.py
Today a deactivated user can request a password change. After password is changed, the user gets an email with his account infos misleading the user. It's better to raise an unauthorized before.
> Handle deactivated user on password change
