.dockerignore, admin/requirements-dev.txt, admin/requirements.txt, admin/setup.py, commons/requirements.txt, commons/setup.py, commons/tests.ini, docker/build/Dockerfile, docker/build/fixversions.txt, docker/build/requirements.txt, geoportal/c2cgeoportal_geoportal/views/layers.py, geoportal/requirements.txt, geoportal/setup.py
I use pip_missing_reqs to find the missing and extra requirements.
https://pypi.python.org/pypi/pip_missing_reqs
=>  Cleanup requires 

admin/Makefile
=> delete not used initdb

admin/acceptance_tests/user_test.py, admin/c2cgeoportal_admin/views/users.py, admin/requirements.txt, commons/c2cgeoportal_commons/lib/email_.py, docker/build/requirements.txt
can be merged so, call to common mail utilities are blocking calls, but has to work 'nominal', i.e. mail facilities have to work...
=> admin, send mail when creating user

geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/+package+_geoportal/locale/en/LC_MESSAGES/+package+_geoportal-client.po, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl
To have the localization in the admin interface
=> Add the missing mo files

admin/setup.py, commons/setup.py, geoportal/setup.py
Mainly fix the open files path
=> Fix deployment to pypi

Jenkinsfile, Makefile
=> Fix major version

c2cgeoportal/lib/lingua_extractor.py
makes lingua extractor more visible, useful when a config entry is wrong
=> more verbose lingua extractor

geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/nondocker-override.mk, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl
Same as the ngeo update https://github.com/camptocamp/ngeo/pull/3733
=> Update FileSaver.js to version 1.3.8

c2cgeoportal/lib/lingua_extractor.py
For https://github.com/camptocamp/c2cgeoportal/issues/3637
=> more beautiful header print

setup.cfg
Refactor code from https://github.com/camptocamp/c2cgeoportal/pull/3639, to make it less complex (in the logic of flake8)
=> fix for flake8

.travis.yml, geoportal/c2cgeoportal_geoportal/lib/lingua_extractor.py, geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/vars_nondocker.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_config-schema.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_vars.yaml_tmpl, travis/vars-nondocker.yaml
=> Do the query from lingua extractor in https

admin/requirements.txt, docker/build/requirements.txt
Fix the grid "All" ajax request.
=> [admin] Upgrade c2cgeoform. Fix GSGMF-427 (grid / all)

c2cgeoportal/pyramid_.py, c2cgeoportal/tests/test_init.py
=> Fix referrer check with query string

doc/integrator/upgrade_application.rst.mako, geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py
=> C2cupgrade managed files

c2cgeoportal/scripts/manage_users.py
=> Fix the manage_users script

doc/integrator/filter.rst
Just some more doc about filter, specifically directed attributes.
=> Add directed attributes for filters documentation

doc/integrator/features.rst, doc/integrator/routing.rst
Docs for [ngeo routing feature](https://github.com/camptocamp/ngeo/pull/2669).
=> Add routing docs

.gitignore, Makefile, admin/README.md, admin/c2cgeoportal_admin/__init__.py, admin/c2cgeoportal_admin/cache_tween.py
See https://jira.camptocamp.com/browse/GSGMF-468.
=> Prevent caching of admin pages

geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/apache/wsgi.conf.mako
Fix https://sentry.camptocamp.com/geo/geomapfish-demo/issues/9928/
and some missing redired on client side
=> Fix the redirects

.gitignore, Makefile, docker/build/bin/import-ngeo-apps, geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose.yaml.mako, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/+dot+dockerignore_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/webpack.apps.js.mako_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl, travis/v23-project.yaml
=> Fix webpack entry points and raster services

docker/build/requirements.txt
Relate with https://github.com/camptocamp/c2cgeoform/pull/184 and https://jira.camptocamp.com/browse/GSGMF-442
=> Upgrade c2cgeoform to remove All from grid page sizes

geoportal/c2cgeoportal_geoportal/lib/check_collector.py
By default it was trying to access:
http://localhost///c2c/health_check?max_level=1
=> Fix check collector

admin/acceptance_tests/user_test.py, admin/c2cgeoportal_admin/views/users.py, commons/c2cgeoportal_commons/models/static.py, geoportal/tests/functional/test_entry.py
Relate https://jira.camptocamp.com/browse/GEO-712
=> Set is_password_changed to False when log in with temp_password

c2cgeoportal/lib/lingua_extractor.py
=> Fix the foreign key that don't ends with '_id'

Jenkinsfile, doc/developer/webservices.rst, doc/integrator/security.rst, geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/nondocker-override.mk, geoportal/c2cgeoportal_geoportal/scaffolds/nondockerupdate/+dot+upgrade.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/+dot+upgrade.yaml_tmpl, travis/from23-config, travis/old-project.yaml, travis/test-upgrade-convert.sh
=> More upgrade tests

geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose.yaml.mako, travis/docker-compose.yaml.mako
=> Use print version 3.14 in Docker mode

admin/c2cgeoportal_admin/views/functionalities.py, admin/c2cgeoportal_admin/views/interfaces.py, admin/c2cgeoportal_admin/views/layer_groups.py, admin/c2cgeoportal_admin/views/layers_v1.py, admin/c2cgeoportal_admin/views/layers_wms.py, admin/c2cgeoportal_admin/views/layers_wmts.py, admin/c2cgeoportal_admin/views/layertree.py, admin/c2cgeoportal_admin/views/ogc_servers.py, admin/c2cgeoportal_admin/views/restriction_areas.py, admin/c2cgeoportal_admin/views/roles.py, admin/c2cgeoportal_admin/views/themes.py, admin/c2cgeoportal_admin/views/users.py, geoportal/c2cgeoportal_geoportal/__init__.py, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/webpack.apps.js.mako_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/geoportal/webpack.apps.js.mako_tmpl
We were spending the third of our time generating json. Now it's near 0%.
=> Improve perfs by using ujson

doc/developer/debugging.rst, geoportal/c2cgeoportal_geoportal/__init__.py, geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose-dev.yaml.mako, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/webpack.apps.js.mako_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/apache/wsgi.conf.mako, geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/geoportal/webpack.apps.js.mako_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/nondocker-finalise.mk_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/nondocker-override.mk, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_vars.yaml_tmpl, geoportal/c2cgeoportal_geoportal/views/__init__.py, geoportal/c2cgeoportal_geoportal/views/dev.py, geoportal/tests/test_init.py, travis/vars-nondocker.yaml
And also fix admin to admin/ redirect
Tested on Docker and non docker environment
=> Fix dev mode

Makefile, geoportal/c2cgeoportal_geoportal/scaffolds/nondockerupdate/+dot+upgrade.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/+dot+upgrade.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py
=> Don't remove the generated alt applications

geoportal/c2cgeoportal_geoportal/scaffolds/create/Dockerfile, geoportal/c2cgeoportal_geoportal/scaffolds/create/bin/eval-templates, geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose.yaml.mako, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/Dockerfile.mako, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_vars.yaml_tmpl, travis/docker-compose.yaml.mako
Fix for kubernetes (RunAsGroup is not yet available)
=> Be able to run as non-root

docker/qgisserver/Dockerfile, docker/qgisserver/__init__.py, docker/qgisserver/accesscontrol.py, docker/qgisserver/metadata.txt
https://github.com/camptocamp/geomapfish_qgisserver
=> Get the qgisserver plugin from geomapfish_qgisserver repo

geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_config-schema.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_vars.yaml_tmpl
To avoid too many errors when the DB is bounced and to have an optimal
number of connections possible.
https://jira.camptocamp.com/browse/GSGMF-501
=> Tune the sqlalchemy connections

geoportal/c2cgeoportal_geoportal/__init__.py
fix https://jira.camptocamp.com/browse/GSGMF-506
=> Don't creates a route that ends with a slash 

doc/integrator/print.rst
Fix https://jira.camptocamp.com/browse/GSGMF-500
=> Add print scale notice

geoportal/c2cgeoportal_geoportal/__init__.py, geoportal/c2cgeoportal_geoportal/lib/headers.py, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_config-schema.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_vars.yaml_tmpl
See also, before:
https://securityheaders.com/?hide=on&source=chromeplugin&q=https://geomapfish-demo.camptocamp.com/2.3
After:
https://securityheaders.com/?hide=on&source=chromeplugin&q=https://geomapfish-demo.camptocamp.com/docker
=> Add some secure headers

c2cgeoportal/tests/functional/test_dbreflection.py
=> Fix of the tests

.editorconfig, geoportal/c2cgeoportal_geoportal/scaffolds/update/+dot+editorconfig
https://jira.camptocamp.com/browse/GSGMF-458
=> Add editor config file

doc/administrator/administrate.rst
https://jira.camptocamp.com/servicedesk/customer/portal/6/GEO-1280
This might be useful for other integrator as well.
Please review (and eventually, if for once Travis lets me go through, merge...)
=> Add WMTS queryable zoom limits documentation

geoportal/c2cgeoportal_geoportal/lib/authentication.py
TODO: make it working on the dev environment
See: https://github.com/camptocamp/c2cgeoportal/pull/3904#discussion_r200312057
=> Send cookies only on https

geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose-run
https://jira.camptocamp.com/browse/GSGMF-558
=> Makes docker-compose-run compatible with Windows

.dockerignore, Dockerfile.mako, Makefile, geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/nondocker-finalise.mk_tmpl, package.json
fix  #3897
and https://jira.camptocamp.com/browse/GSGMF-558
=> Fix OpenLayers in the admin interface

geoportal/c2cgeoportal_geoportal/scaffolds/create/vars.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/vars.yaml_tmpl
Related to https://jira.camptocamp.com/browse/GSGMF-564
=> Don't have dupplicated fulltextsearchUrl

geoportal/c2cgeoportal_geoportal/views/mapserverproxy.py
Fix: https://jira.camptocamp.com/browse/GSGMF-466
=> Get an error code on error on GetMap

docker/build/Dockerfile, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl
Fix: https://jira.camptocamp.com/browse/GSGMF-505
=> Do an xmllint on the jasper report print templates

geoportal/c2cgeoportal_geoportal/scaffolds/create/vars.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/vars.yaml_tmpl, geoportal/c2cgeoportal_geoportal/templates/dynamic.js
fix https://jira.camptocamp.com/browse/GSGMF-555
=> Be able to automatically get the gmfSearchGroups

.gitignore, Makefile, admin/package.json, geoportal/package.json, greenkeeper.json
And move the geoportal part in geoportal
=> Move the package.json in the admin directory

docker-run
Should fix https://jira.camptocamp.com/browse/GSGMF-569
=> Fix the Git branch on Travis

geoportal/c2cgeoportal_geoportal/lib/dbreflection.py
Fix: https://jira.camptocamp.com/browse/GSGMF-499
=> Add a lock on getting the autoloaded table

docker/build/requirements.txt, geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose.yaml.mako, geoportal/c2cgeoportal_geoportal/scaffolds/create/tilegeneration/config.yaml.tmpl.mako_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_vars.yaml_tmpl
And switch to use Redis by default instead of SQS between the tilecloud-chain
master and slaves.
=> Upgrade tilecloud-chain to 1.7.1

.travis.yml, travis/create-new-project.sh, travis/publish-docker
First step for https://jira.camptocamp.com/browse/GSGMF-352
=> Publish the based GeoMapFish application

geoportal/c2cgeoportal_geoportal/scaffolds/create/vars.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/vars.yaml_tmpl
see also: https://github.com/camptocamp/ngeo/pull/4146
=> Add print legend options

geoportal/c2cgeoportal_geoportal/lib/authentication.py
Fix: https://github.com/camptocamp/c2cgeoportal/commit/82d0989b0184d67e12d2d8cbd9ddf8918f7bd334
=> Fix http/https mix

Makefile
Wait on https://github.com/camptocamp/ngeo/pull/4261
=> Add missing SASS files

geoportal/c2cgeoportal_geoportal/views/entry.py
=> fix if ms:character in describfeaturetype

geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/+package+_geoportal/templates/api/mapconfig.js_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_vars.yaml_tmpl
See https://github.com/camptocamp/demo_geomapfish/pull/89
=> Fix api build and config

commons/c2cgeoportal_commons/alembic/main/809650bd04c3_add_dimension_field.py, commons/c2cgeoportal_commons/models/main.py, doc/developer/webservices.rst, geoportal/c2cgeoportal_geoportal/views/entry.py, geoportal/tests/functional/test_themes_dimensions.py
Add dimension.field for handling dimensions through OGC filters with QGIS server.
Server part of https://github.com/camptocamp/aeroportdelyon_sig/issues/399
Relate with ngeo part: https://github.com/camptocamp/ngeo/pull/4223
Replace https://github.com/camptocamp/c2cgeoportal/pull/4112 because travis is failing, cloning camptocamp/c2cgeoportal instead of arnaud-morvan/c2cgeoportal.
=> Qgis dimensions 2.3

geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl
=> Fix build all the interfaces in one time

geoportal/c2cgeoportal_geoportal/views/raster.py
fix: https://sentry.camptocamp.com/geo/geomapfish-demo/issues/8796/
=> Validate the parameters

geoportal/c2cgeoportal_geoportal/templates/dynamic.js
https://sentry.camptocamp.com/geo/geomapfish-demo/issues/9840/
=> Fallback to 'default_interface' in dynamic.js

doc/integrator/routing.rst
~Sync the example with this change: https://github.com/camptocamp/ngeo/pull/4309~
Document vars.yaml instead.
=> Update routing configuration

geoportal/c2cgeoportal_geoportal/__init__.py, geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/apache/wsgi.conf.mako
=> Fix short URL in Docker mode

geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_vars.yaml_tmpl
https://jira.camptocamp.com/browse/GSGMF-682
=> GSGMF_682_add_missing_metadata

geoportal/c2cgeoportal_geoportal/__init__.py, geoportal/c2cgeoportal_geoportal/lib/dbreflection.py, geoportal/c2cgeoportal_geoportal/lib/xsd.py, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_vars.yaml_tmpl, geoportal/c2cgeoportal_geoportal/views/layers.py, geoportal/tests/functional/test_dbreflection.py, geoportal/tests/functional/test_layers.py, geoportal/tests/functional/test_xsd.py
https://jira.camptocamp.com/browse/GSGMF-616
=> Editing columns order

geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_vars.yaml_tmpl
https://jira.camptocamp.com/browse/GSGMF-523
=> Set http default timeout of 300s (for python requests)

geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose.yaml.mako
To be restarted on Docker service restart
=> Use the unless-stopped restart policy

Dockerfile.mako
=> Remove temp directory after npm install

Makefile
=> Remove unneded things in node_modules

c2cgeoportal/scaffolds/update/CONST_versions_requirements.txt
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-18074
=> Fix CVE-2018-18074

geoportal/c2cgeoportal_geoportal/__init__.py, geoportal/c2cgeoportal_geoportal/views/dynamic.py
The idea is to use the JSON directly in the controller and don't have to
add some script in the HTML file to me proper and be able to remove the
unsafe-inline rule:
https://github.com/camptocamp/c2cgeoportal/blob/4c0fc58afbfe72f4b6a64f6885eceadf177961c9/geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_vars.yaml_tmpl#L456
ngeo prototype to be able to reuse the JSON and inject it as constants:
https://github.com/camptocamp/ngeo/compare/settings-proto
=> Add a dynamic view as JSON

Makefile
We want Dockerfile to be removed on make clean.
=> Clean Dockerfile

docker/build/requirements.txt, docker/qgisserver/requirements.txt, geoportal/c2cgeoportal_geoportal/lib/dbreflection.py, geoportal/c2cgeoportal_geoportal/lib/xsd.py, geoportal/c2cgeoportal_geoportal/views/layers.py, geoportal/tests/functional/test_dbreflection.py, geoportal/tests/functional/test_xsd.py
Support readonlyAttributes metadata on server side (https://jira.camptocamp.com/browse/GSGMF-615).
Client side : https://github.com/camptocamp/ngeo/pull/4320
=> Add readonlyAttributes metadata support

Jenkinsfile
Actually the version in the .config is wrong (2.4)
=> Fix creation of dev release (tag detection)

geoportal/c2cgeoportal_geoportal/scaffolds/create/vars.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/vars.yaml_tmpl, geoportal/c2cgeoportal_geoportal/templates/dynamic.js, geoportal/c2cgeoportal_geoportal/views/dynamic.py, travis/vars.yaml
And that don't return an http error
=> Fix the dynamic view

geoportal/MANIFEST.in
Refactor the geoportal/MANIFEST.in
=> Add the dynamic.js template in the egg

.bandit, commons/acceptance_tests/test_users.py
Add a bandit configuration file
=> Fix codacy issue

docker/build/bin/import-ngeo-apps, geoportal/c2cgeoportal_geoportal/__init__.py, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/webpack.apps.js.mako_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_config-schema.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_vars.yaml_tmpl, geoportal/c2cgeoportal_geoportal/views/dynamic.py, geoportal/package.json
Remove the js view,
Fix come variable hidden
Make angularLocaleScript generic
Remove some unneeded replacement in import-ngeo-apps
Add the version to vendor.js automatically, not manually in all the html files
Update the html file to have the metadata required by new ngeo version
=> Json settings

geoportal/c2cgeoportal_geoportal/scaffolds/create/print/print-apps/+package+/config.yaml.tmpl
Added referer check to the print
=> Change the PDF output to use SVG for vector layers, by default

Jenkinsfile
Actually the documentation is not updated ...
=> Fix abort CI on documentation

geoportal/c2cgeoportal_geoportal/scaffolds/nondockerupdate/+dot+upgrade.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl, geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py, travis/old-project.yaml, travis/test-upgrade-convert.sh
Actually the default_project_file is completely brocken
=> Fix condition in upgrade

doc/integrator/tilegeneration.rst
I guess sbrunner repo is not existing anymore. :-)
=> Use camptocamp repo links for tilegeneration doc

geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl
Priority:
- Project
- gmf
- neo
=> Use the right po order

Jenkinsfile
Add missing docker-compose file
=> [fix-master] Add lock for docker-compose-run 

geoportal/c2cgeoportal_geoportal/lib/__init__.py, geoportal/c2cgeoportal_geoportal/resources.py, geoportal/c2cgeoportal_geoportal/views/entry.py, geoportal/c2cgeoportal_geoportal/views/fulltextsearch.py, geoportal/c2cgeoportal_geoportal/views/layers.py, geoportal/c2cgeoportal_geoportal/views/pdfreport.py, geoportal/tests/functional/__init__.py, geoportal/tests/functional/test_request_property.py, geoportal/tests/functional/test_themes.py, geoportal/tests/functional/test_themes_private.py, geoportal/tests/test_get_url.py
=>  Fix some query for multi-role , Remove layer v1

geoportal/c2cgeoportal_geoportal/lib/__init__.py, geoportal/c2cgeoportal_geoportal/resources.py, geoportal/c2cgeoportal_geoportal/views/entry.py, geoportal/c2cgeoportal_geoportal/views/fulltextsearch.py, geoportal/c2cgeoportal_geoportal/views/layers.py, geoportal/c2cgeoportal_geoportal/views/pdfreport.py, geoportal/tests/test_get_url.py
=> Fix some query for multi-role 

geoportal/c2cgeoportal_geoportal/views/entry.py, geoportal/tests/functional/test_entry.py, geoportal/tests/functional/test_looptheme.py, geoportal/tests/functional/test_themes.py, geoportal/tests/functional/test_themes_dimensions.py, geoportal/tests/functional/test_themes_edit_columns.py, geoportal/tests/functional/test_themes_editing.py, geoportal/tests/functional/test_themes_metadata.py, geoportal/tests/functional/test_themes_mixed.py, geoportal/tests/functional/test_themes_private.py, geoportal/tests/functional/test_themes_scale.py, geoportal/tests/functional/test_themes_time.py
=> Remove version 1 and catalogue option

admin/package.json
=> fix(package): update bootstrap-table to version 1.13.1

geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_vars.yaml_tmpl, geoportal/c2cgeoportal_geoportal/views/mapserverproxy.py, geoportal/tests/functional/test_mapserverproxy.py, geoportal/tests/functional/test_mapserverproxy_capabilities.py, vars.yaml
Fix all tests related to mapservproxy with multi-role.
=> [multi_role] Fix mapserverproxy

geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_vars.yaml_tmpl, geoportal/c2cgeoportal_geoportal/views/printproxy.py
https://jira.camptocamp.com/browse/GSGMF-715
=> Can use a redirect to fetch the print reports directly

c2cgeoportal/scaffolds/update/CONST_dev-requirements.txt, docker/build/dev-requirements.txt
See: https://requires.io/github/camptocamp/c2cgeoportal/requirements/?branch=2.2
=> Fix potential vulnerability

geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/Dockerfile.mako
For example when the profile is stored on S3...
=> Fix SSL access from GDAL

admin/MANIFEST.in
It must include files in https://github.com/camptocamp/c2cgeoportal/tree/2.3/admin/c2cgeoportal_admin/templates/widgets
=> Admin - Include pt files for widgets

geoportal/c2cgeoportal_geoportal/views/memory.py
- Add `wfs_feature_type_cache`
- Other disabled by default
- Other ordered by size
=> Fix the memory view and make a run time acceptable

geoportal/c2cgeoportal_geoportal/scaffolds/create/mapserver/mapserver.map.tmpl.mako_tmpl
See also: https://jira.camptocamp.com/browse/GEO-1811
=> Fix the Mapserver  onlineresource

c2cgeoportal/scaffolds/create/apache/frontend.conf.mako
(See https://jira.camptocamp.com/projects/GEO/queues/custom/52/GEO-1726)
=> Set CORS for mapcache

doc/integrator/docker.rst, geoportal/c2cgeoportal_geoportal/scaffolds/create/project.yaml.mako_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/nondockerupdate/+dot+upgrade.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/+dot+upgrade.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_vars.yaml_tmpl
* Be able to configure the database in one shot.
* Be able to configure the port as an environment variable.
* Use a correct value in the checker_url.
* Add changelog message about pg_trgm.
* Add commands to clean unused Docker artifacts.
* Remove relay old `create_db` script.
=> Some little improvements

doc/integrator/ngeo_new_interface.rst, doc/integrator/upgrade_application.rst.mako, geoportal/c2cgeoportal_geoportal/scripts/themev1tov2.py
Should fix https://jira.camptocamp.com/browse/GSGMF-779
=> Fix themev2tov2 script

geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py
Not supported ad arbument of docker-compose down
=> Remove argument --timeout=0

geoportal/c2cgeoportal_geoportal/lib/dbreflection.py
To use in conjunction with
https://www.postgresql.org/docs/9.6/static/rules-views.html
=> Specify the primary key name to be able to edit a postgres view.

geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+env.mako_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose-lib.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_vars.yaml_tmpl
=> Make port used by docker configurable

docker/qgisserver/requirements.txt
=>  Fix c2cwsgiutils version in Docker QGIS server image 

docker/qgisserver/requirements.txt
=> Fix rq.filter syntax

geoportal/c2cgeoportal_geoportal/__init__.py, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_vars.yaml_tmpl
Current result (before changes): https://geomapfish-demo-dc.camptocamp.com/sbrunner24/c2c
=> Admin index fix

greenkeeper.json
=> Fix greenkeper file syntax

Jenkinsfile, Makefile, geoportal/c2cgeoportal_geoportal/scaffolds/nondockerupdate/+dot+upgrade.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/+dot+upgrade.yaml_tmpl, geoportal/package.json, travis/old-project.yaml
Related to https://github.com/camptocamp/ngeo/pull/4667
Fix #4636
=> Add sass files to non alt interfaces

geoportal/c2cgeoportal_geoportal/lib/functionality.py
See: https://sentry.camptocamp.com/geo/geomapfish-demo/issues/148302/?query=is:unresolved%20environment:demo-2-4
=> Be able to have no settings role

geoportal/c2cgeoportal_geoportal/__init__.py, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
https://jira.camptocamp.com/browse/GSGMF-814
=> Rename full-text search path from fulltextsearch to search

admin/package.json
=> fix(package): update bootstrap-table to version 1.14.1

geoportal/c2cgeoportal_geoportal/__init__.py
https://jira.camptocamp.com/browse/GSGMF-828
=> Fix accepted content type

geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
see: https://github.com/camptocamp/c2cgeoportal/pull/4696#discussion_r263791604
=> Better sentence

admin/acceptance_tests/role_test.py, docker/build/requirements.txt
=> Fix pyproj version

geoportal/c2cgeoportal_geoportal/scaffolds/create/bin/eval-templates
To be able to add a dollar in the templates, see:
https://stackoverflow.com/questions/24963705/is-there-an-escape-character-for-envsubst
=> Add the DOLLAR environment variable in eval-template

geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+gitignore_tmpl
Consider it as developer stuff that shouldn't be committed.
=> Add docker-compose.override.yaml in Git ignore.

doc/integrator/api.rst
See: https://github.com/camptocamp/ngeo/pull/4743
=> Remove supportedProjections

Makefile, docker/build/bin/eval-templates, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/+package+_geoportal/static-ngeo/api/index.js, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl, geoportal/c2cgeoportal_geoportal/views/entry.py
=> Fix API loading

geoportal/c2cgeoportal_geoportal/views/mapserverproxy.py
https://sentry.camptocamp.com/geo/geomapfish-demo/issues/148384
=> Fix 'User' object has no attribute 'name'

geoportal/c2cgeoportal_geoportal/views/mapserverproxy.py
https://jira.camptocamp.com/browse/GSGMF-846
=> Fix for user without any roles

geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py
https://jira.camptocamp.com/browse/GSGMF-855
=> Remove InsecureRequestWarning

doc/administrator/mapfile.rst, geoportal/c2cgeoportal_geoportal/scaffolds/create/mapserver/demo.map.tmpl.mako_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/mapserver/demo.map.mako_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/mapserver/CONST_example_map_mako_tmpl
https://jira.camptocamp.com/browse/GSGMF-840
=> Fix secure layer with no area, remove deprecated doc

doc/integrator/upgrade_application.rst.mako, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl
Shouldn't we add or be able to add the environment variable:
AWS_DEFAULT_REGION: ch-dk-2
AWS_S3_ENDPOINT: sos-ch-dk-2.exo.io
=> Fix edit-qgis-project

doc/integrator/fulltext_search.rst
See also: https://jira.camptocamp.com/browse/GEO-1958
=> Add documentation to the full text search

doc/integrator/fulltext_search.rst
=> Better sentences

doc/integrator/configuration.rst, doc/integrator/headers.rst, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_vars.yaml_tmpl
https://jira.camptocamp.com/browse/GSGMF-863
=> Add Content-Security-Policy for c2c and document them

doc/administrator/administrate.rst
Could anybody confirm me that I have not written wrong stuff... ?
But I think that this is really missing in the documentation.
=> Add some doc regarding user management in the admin interface

doc/integrator/checker.rst, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_config-schema.yaml
Fix: https://jira.camptocamp.com/browse/GSGMF-898
=> Improve the checker documetations

Makefile, geoportal/c2cgeoportal_geoportal/__init__.py, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_vars.yaml_tmpl, geoportal/c2cgeoportal_geoportal/views/__init__.py, travis/test-new-project
https://jira.camptocamp.com/browse/GSGMF-901
=> Fix API help

docker/build/requirements.txt, docker/qgisserver/requirements.txt
See: https://requires.io/github/camptocamp/c2cgeoportal/requirements/?branch=2.3
@arnaud-morvan does it look safe to upgrade colander?
=> Upgrade vulnerable packages

geoportal/c2cgeoportal_geoportal/views/ogcproxy.py
Fix https://jira.camptocamp.com/browse/GSGMF-856
=> Fix for tinyows_proxy

doc/developer/debugging.rst
Follow-up for #4865.
Not sure if I understood the cookie part correctly, @sbrunner .
=> doc for debugging: typos and suggestions for improvements

geoportal/c2cgeoportal_geoportal/views/entry.py, geoportal/tests/functional/test_entry.py
Fix regression introduced by:
https://github.com/camptocamp/c2cgeoportal/pull/4765
=> Fix authentication error message

geoportal/c2cgeoportal_geoportal/views/entry.py, geoportal/tests/functional/__init__.py, geoportal/tests/functional/test_entry.py, geoportal/tests/functional/test_looptheme.py, geoportal/tests/functional/test_mapserverproxy.py, geoportal/tests/functional/test_mapserverproxy_group.py, geoportal/tests/functional/test_themes.py, geoportal/tests/functional/test_themes_dimensions.py, geoportal/tests/functional/test_themes_edit_columns.py, geoportal/tests/functional/test_themes_editing.py, geoportal/tests/functional/test_themes_layermultinameerror.py, geoportal/tests/functional/test_themes_metadata.py, geoportal/tests/functional/test_themes_mixed.py, geoportal/tests/functional/test_themes_nameerror.py, geoportal/tests/functional/test_themes_private.py, geoportal/tests/functional/test_themes_scale.py, geoportal/tests/functional/test_themes_time.py
Fix https://jira.camptocamp.com/browse/GSGMF-932
=> Do DescribeFeatureType query on internal server

docker-run, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl
Don't rename the .js into .js.tmpl
=> Fix the merge from 2.3

geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose-lib.yaml_tmpl
=> Avoid webpack-dev-server errors in browser console

docker/build/bin/eval-templates, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/webpack.apps.js.mako_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl
Second try to fix: https://jira.camptocamp.com/browse/GEO-2009
=> Fix the entrypoint in Docker mode

doc/integrator/raster.rst
See GEO-2052 for more details.
@pvalsecc Feel free to complete my PR if necessary.
=> Add doc for DEM nodata value

geoportal/package.json, travis/test-upgrade-convert.sh
Requires https://github.com/camptocamp/ngeo/pull/4898
=> Use the latest image

geoportal/c2cgeoportal_geoportal/scaffolds/update/+dot+upgrade.yaml_tmpl, travis/test-upgrade-convert.sh
Fix https://jira.camptocamp.com/browse/GSGMF-961
=> Fix the upgrade after mako interpretation

docker/build/requirements.txt, geoportal/requirements.txt
https://docs.pylonsproject.org/projects/pyramid/en/latest/whatsnew-1.10.html
=> Upgrade to pyramid 1.10

geoportal/c2cgeoportal_geoportal/views/entry.py
See https://jira.camptocamp.com/browse/GSLUX-233.
=> More reliable WMS get cap parsing

.circleci/config.yml
=> Add a trivial circleci configuration file to avoid CI error on GitHub

geoportal/c2cgeoportal_geoportal/views/raster.py
They both come with their own version of GDAL and GDAL uses quite a lot
of RSS memory (~15MB) for each copy.
=> Lazy load of rasterio and fiona

geoportal/c2cgeoportal_geoportal/views/entry.py
This considerably reduce the number of requests on database to complete the themes view.
=> Load treeitems and ogcservers in sqlmalchemy session.identity_map

geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+gitignore_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/Dockerfile.mako, geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/+dot+gitignore_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/nondockercreate/nondocker-finalise.mk_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/nondockerupdate/+dot+upgrade.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/+dot+upgrade.yaml_tmpl
Fix: https://jira.camptocamp.com/browse/GSGMF-992
=> Make it working on old Docker version

.dockerignore, Dockerfile.mako, bin/list4vrt, doc/integrator/objectstorage.rst
Fix https://jira.camptocamp.com/browse/GSGMF-996
=> Add list4vrt helper

docker/build/bin/eval-templates, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/webpack.apps.js.mako_tmpl
Fix: https://jira.camptocamp.com/browse/GSGMF-1006
Will have in imparc on this part of code:
https://github.com/camptocamp/ngeo/blob/2.4/buildtools/webpack.plugin.js#L110
=> Fix JQuery UI icon loading

.config, Dockerfile, Makefile, bin/transifex-init, ci/create-new-project, ci/test-upgrade, doc/developer/build_release.rst.tmpl, doc/developer/debugging.rst, doc/developer/server_side.rst.tmpl, doc/developer/transifex.rst, doc/integrator/create_application.rst.tmpl, doc/integrator/install_application.rst, doc/integrator/make.rst, doc/integrator/urllogin.rst, geoportal/c2cgeoportal_geoportal/scaffolds/__init__.py, geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+config_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+travis.yml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/+dot+upgrade.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
Fix https://jira.camptocamp.com/browse/GSGMF-982
=> Update the documentation removes all docker-run

geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl
Fix: https://jira.camptocamp.com/browse/GSGMF-1008
=> Remove unused build arg

Dockerfile
See: https://github.com/awslabs/git-secrets
=> Add git-secrets 1.3.0 in the upgrade image

doc/integrator/object_editing.rst
Esp. for configuring the triangle size.
=> Add configuration info in the oeedit doc

doc/integrator/create_application.rst.mako
Supersedes #5133 (to be able to trigger Jenkins)
=> Doc - Missing package in create template

Dockerfile
Puppetteer already has an internal chromium
=> Remove duplicate chromium

geoportal/c2cgeoportal_geoportal/views/dynamic.py
Requires: https://github.com/camptocamp/ngeo/pull/5076
=> Fix the theme redirect

doc/integrator/internationalization.rst
Follow GEO-1767
Please verify that it's understandable.
=> Doc - Explain i18n (client) limitation and a workaround

commons/c2cgeoportal_commons/alembic/main/78fd093c8393_add_api_s_intrfaces.py, doc/developer/server_side.rst, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/+package+_geoportal/static-ngeo/api/index.js, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl, geoportal/c2cgeoportal_geoportal/scripts/create_demo_theme.py
Fix: https://jira.camptocamp.com/browse/GSGMF-1082
Liked to: https://github.com/camptocamp/ngeo/pull/5099
=> Update the interfaces

geoportal/c2cgeoportal_geoportal/views/tinyowsproxy.py
Fix https://jira.camptocamp.com/browse/GEO-2382
=> Tinyows utf encode

geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
fix: https://github.com/camptocamp/c2cgeoportal/pull/5271#discussion_r322129514
=> Add extra information in the changelog

Dockerfile, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/Dockerfile_tmpl
See also: https://github.com/camptocamp/c2cwsgiutils/pull/391
=> Remove docstrings and asserts from the runtime

Dockerfile, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/Dockerfile_tmpl
See also: https://github.com/camptocamp/c2cwsgiutils/pull/395
=> Remove -OO optimisation

geoportal/c2cgeoportal_geoportal/__init__.py, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/+package+_geoportal/static-ngeo/api/index.js, geoportal/c2cgeoportal_geoportal/views/entry.py, geoportal/c2cgeoportal_geoportal/views/i18n.py
GSGMF-1103
Client part: https://github.com/camptocamp/ngeo/pull/5104
=> Add view to get translations from Simple API after negociation

geoportal/c2cgeoportal_geoportal/scaffolds/update/mapserver/CONST_example_map_tmpl
According https://camptocamp.github.io/c2cgeoportal/master/administrator/mapfile.html?highlight=gml_featureid#wfs-getfeature
=> Complete the example mapfile

commons/c2cgeoportal_commons/models/static.py, geoportal/c2cgeoportal_geoportal/views/entry.py
To store the `consecutive_failed`...
=> Force commit on login failed

geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl
As it is not possible at build and it is lately done at runtime.
=> Do not try to generate WMTS capabilities at build

Dockerfile
Currently, we get an error in loop on Gunicorn start...
=> Don't run the gunicorn application in the tools contaners

geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py
Alternative for  #5324
Fix: https://jira.camptocamp.com/browse/GSGMF-1118
=> Also move and remove the managed files

geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/Dockerfile_tmpl
As this will allow adding requirements in projects without customising Dockerfile.
https://jira.camptocamp.com/browse/GSGMF-1119
=> Add empty requirements in scaffold geoportal

geoportal/c2cgeoportal_geoportal/__init__.py
By adding reference to healcheck object in registry.
=> Allow adding custom checkers

geoportal/c2cgeoportal_geoportal/lib/__init__.py
* Consider it as 10.27.10.0/24
* Typo
=> Accept network like: 10.27.10.102/24

geoportal/c2cgeoportal_geoportal/views/mapserverproxy.py
No error on:
/mapserv_proxy?ogcserver=?&SERVICE=WMS
/mapserv_proxy?ogcserver=?&SERVICE=WFS
=> Less unexpected errors

geoportal/c2cgeoportal_geoportal/views/entry.py
=> Less logs, Log user IP

Dockerfile, internal.mk
Don't download po files from Transifex on rebuild
=> Better layer cache

geoportal/c2cgeoportal_geoportal/views/entry.py
=> Fix theme cache

geoportal/c2cgeoportal_geoportal/views/dynamic.py, geoportal/tests/functional/test_dynamicview.py
_query should be passed to static_url, not to format
=> Fix _query

doc/developer/webservices.rst, geoportal/c2cgeoportal_geoportal/views/entry.py
See also: https://jira.camptocamp.com/browse/GSGMF-1133
=> Add missing attributes imformations, add some info logs

doc/developer/cache.rst, docker/test-db/12-tm-europe-borders.sql, docker/test-mapserver/mapserver.map.tmpl, geoportal/c2cgeoportal_geoportal/lib/__init__.py, geoportal/c2cgeoportal_geoportal/lib/filter_capabilities.py, geoportal/c2cgeoportal_geoportal/lib/layers.py, geoportal/c2cgeoportal_geoportal/scaffolds/create/mapserver/demo.map.tmpl_tmpl, geoportal/c2cgeoportal_geoportal/views/entry.py, geoportal/c2cgeoportal_geoportal/views/layers.py, geoportal/c2cgeoportal_geoportal/views/mapserverproxy.py, geoportal/c2cgeoportal_geoportal/views/tinyowsproxy.py, geoportal/tests/functional/test_mapserverproxy.py, geoportal/tests/functional/test_themes_editing.py
- in the theme
- the mapserv proxy
- the tinyows proxy
- the layers (editing)
=> Add intranet security on restriction area

geoportal/c2cgeoportal_geoportal/templates/login.html, geoportal/c2cgeoportal_geoportal/views/entry.py
Migrate account procedure
Add authentication code to the admin login panel
=> Migrate, admin

Dockerfile, commons/c2cgeoportal_commons/alembic/env.py, geoportal/c2cgeoportal_geoportal/lib/loader.py, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/alembic.ini, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/development.ini_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/production.ini_tmpl
Uniformize development.ini and production.ini
Move default environment variable to Docker images
=>  Removes logstash handler 

geoportal/tests/functional/test_themes_metadata.py
I don't understand this change...
=> Fix master

.circleci/config.yml, ci/publish
The config image from GeoMapFish will be overriden by the config image of the
default poject
=> Fix confusion

docker/test-mapserver/mapserver.map.tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/mapserver/mapserver.map.tmpl_tmpl
Not needed anymore in OpenShift environment
=> Remove SHAPEPATH definition

commons/c2cgeoportal_commons/models/main.py, commons/c2cgeoportal_commons/models/static.py
__unicode__ is no more used in Python 3
=> Replace __unicode__ by __str__

geoportal/c2cgeoportal_geoportal/lib/functionality.py
This function is called about 500 times to build a theme...
=> Less redis cache - Use memory cache to be faster

requirements-dev.txt, requirements.txt
Don't works well with Dependabot
=> New pyproj version can't be installed

geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose-lib.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose.override.sample.yaml_tmpl
=> Less QGIS server logs by default

geoportal/c2cgeoportal_geoportal/scaffolds/create/mapserver/demo.map.tmpl_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/mapserver/tinyows.xml.tmpl
In the .tmpl it's environment variable on capital.
=> Fix some replacement variables

geoportal/c2cgeoportal_geoportal/scaffolds/create/print/print-apps/+package+/config.yaml.tmpl, geoportal/c2cgeoportal_geoportal/views/proxy.py, geoportal/tests/__init__.py
Create or forward
Needed by the intranet detection
=> Manage Forwarded header

geoportal/c2cgeoportal_geoportal/__init__.py
Fix: https://jira.camptocamp.com/browse/GSGMF-1144
=> Delete redis cache on invalidate

commons/c2cgeoportal_commons/lib/email_.py
And do not send not encrypted credentials over network
=> Start TLS before login on SMTP server

geoportal/c2cgeoportal_geoportal/__init__.py, geoportal/c2cgeoportal_geoportal/views/__init__.py
=> Fix the route redirect on non empty entrypoint

geoportal/c2cgeoportal_geoportal/__init__.py, geoportal/c2cgeoportal_geoportal/lib/metrics.py, geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_config-schema.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl, geoportal/c2cgeoportal_geoportal/views/memory.py, geoportal/tests/test_init.py
=> Add some more information in the memory view

geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_Makefile_tmpl
=> Removes unneded extra error

docker/config/haproxy/haproxy.cfg.tmpl
=> Remove one haproxy warning

admin/c2cgeoportal_admin/routes.py, admin/c2cgeoportal_admin/widgets.py, commons/c2cgeoportal_commons/lib/email_.py, commons/c2cgeoportal_commons/models/__init__.py, commons/c2cgeoportal_commons/models/main.py, commons/c2cgeoportal_commons/models/static.py, commons/c2cgeoportal_commons/testing/initializedb.py, docker/qgisserver/geomapfish_qgisserver/accesscontrol.py, geoportal/c2cgeoportal_geoportal/__init__.py, geoportal/c2cgeoportal_geoportal/lib/__init__.py, geoportal/c2cgeoportal_geoportal/lib/caching.py, geoportal/c2cgeoportal_geoportal/lib/checker.py, geoportal/c2cgeoportal_geoportal/lib/dbreflection.py, geoportal/c2cgeoportal_geoportal/lib/filter_capabilities.py, geoportal/c2cgeoportal_geoportal/lib/functionality.py, geoportal/c2cgeoportal_geoportal/lib/layers.py, geoportal/c2cgeoportal_geoportal/lib/lingua_extractor.py, geoportal/c2cgeoportal_geoportal/lib/loader.py, geoportal/c2cgeoportal_geoportal/lib/xsd.py, geoportal/c2cgeoportal_geoportal/scaffolds/__init__.py, geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py, geoportal/c2cgeoportal_geoportal/scripts/create_demo_theme.py, geoportal/c2cgeoportal_geoportal/scripts/manage_users.py, geoportal/c2cgeoportal_geoportal/scripts/theme2fts.py, geoportal/c2cgeoportal_geoportal/scripts/urllogin.py, geoportal/c2cgeoportal_geoportal/views/dynamic.py, geoportal/c2cgeoportal_geoportal/views/layers.py, geoportal/c2cgeoportal_geoportal/views/mapserverproxy.py, geoportal/c2cgeoportal_geoportal/views/raster.py
=> [Fix master] Fix new prospector issues

geoportal/c2cgeoportal_geoportal/views/theme.py
Fix: https://jira.camptocamp.com/browse/GSGMF-1158
=> Fix the filter panel

geoportal/c2cgeoportal_geoportal/__init__.py
fix: https://sentry.io/organizations/camptocamp/issues/1394820454/?environment=prod-2-5&project=1851011&
=> Don't delete the cache with no keys

doc/integrator/authentication.rst
=> Add security note on authentication

.circleci/config.yml, docker/qgisserver/geomapfish_qgisserver/accesscontrol.py, geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose.override.sample.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/qgisserver/geomapfish.yaml_tmpl
- Fix published image build
- Better logger call
- More robust initialization on failure
- More robust disable all layer on initialization failure
- Fix database URI
- Better debugging config
=> Fix access control in QGSI server - no more working

doc/integrator/api.rst
=> Add a precision about the API layers

geoportal/c2cgeoportal_geoportal/lib/checker.py, geoportal/c2cgeoportal_geoportal/scaffolds/update/+dot+upgrade.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_config-schema.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl
Related pull requests:
- https://github.com/camptocamp/ngeo/pull/5377
- https://github.com/camptocamp/ngeo/pull/5406
=> Fix the checker on local environment

.circleci/config.yml
Introduced by a4231af56e5defd9b2a266482d8f1554dedf7c1b
=> Fix publish from master

.circleci/config.yml
=> Fix double publish Docker images

docker/config/bin/eval-templates
Required when we have some restriction area that have an intersection
=> Be able to do a ST_Union instead of ST_Collect

docker/build/requirements.txt, geoportal/c2cgeoportal_geoportal/views/fulltextsearch.py
Fix: https://sentry.io/organizations/camptocamp/issues/1447931269/
=> Ignore startup quote and spaces

ci/create-new-project
Fix: https://jira.camptocamp.com/browse/GSGMF-1191
=> Fix EPSG on the demo server

geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/+package+_geoportal/static-ngeo/api/index.js_tmpl, geoportal/c2cgeoportal_geoportal/scripts/theme2fts.py
To complete: https://github.com/camptocamp/ngeo/pull/5450
=> Don't fill the full-text search table for 'api' interface by default

.dependabot/config.yml, .gitattributes
Put the Dependabot config in a file
=> Add Dependabot config

.github/workflows/pr-title-lint.yaml
To have a nice changelog file https://github.com/camptocamp/c2cgeoportal/blob/2.4/CHANGELOG.md
=> Check pull request title

.github/workflows/dependabot-auto-merge.yaml
* Update the plugin name
* Less interactions
=> Dependabot automerge

docker/qgisserver/geomapfish_qgisserver/accesscontrol.py, docker/qgisserver/tests/functional/accesscontrol_test.py, docker/qgisserver/tests/functional/accesscontrol_test_allowToEdit.py
=> Fix transactions in QGIS plugin

doc/administrator/editing.rst, doc/developer/debugging.rst, doc/index.rst.tmpl, doc/integrator/api.rst, doc/integrator/docker.rst, doc/integrator/routing.rst.tmpl, doc/integrator/security.rst, doc/integrator/tilegeneration.rst.tmpl
Remove documentation related to Docker version that not usable with the version of GeoMapFish
=> Documentation cleanup

geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+env.mako_tmpl
=> Update the mutualized print URL

docker/qgisserver/tests/functional/accesscontrol_allow_to_edit_test.py, docker/qgisserver/tests/functional/accesscontrol_test.py, docker/qgisserver/tests/functional/conftest.py
Rename the file so it is called by tests
=> fix(qgisserver) edit tests are now called

docker/qgisserver/geomapfish_qgisserver/accesscontrol.py, docker/qgisserver/tests/functional/accesscontrol_allow_to_edit_test.py, docker/qgisserver/tests/functional/accesscontrol_test.py, docker/qgisserver/tests/functional/conftest.py
Make the test work on 2.5
Also had to create an extra ADMIN user for tests
=> Backport qgistests from 24

doc/administrator/mapfile.rst, docker/test-mapserver/mapserver.map.tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/mapserver/demo.map.tmpl_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/mapserver/CONST_example_map_tmpl
unique should be lowercase
Upercase USING is cosmetic
=> Be compatible with Mapserver master

geoportal/c2cgeoportal_geoportal/views/proxy.py
Fix: https://jira.camptocamp.com/browse/GSGMF-1224
=> Fix query string from OGC server

geoportal/c2cgeoportal_geoportal/views/login.py
Fix: https://jira.camptocamp.com/browse/GSGMF-1243
=> Be able to request new password when the 2fa is not initialised

doc/administrator/administrate.rst.tmpl, doc/administrator/editing.rst, doc/administrator/mapfile.rst, doc/administrator/tinyows.rst, doc/administrator/wmstime.rst, doc/index.rst.tmpl
* typo and sentence fixes
Backport of #5982
=> Documentation typo and sentence fixes

geoportal/c2cgeoportal_geoportal/views/layers.py
Required for:
https://jira.camptocamp.com/browse/GEO-3047
=> Better errors

geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/vars.yaml_tmpl
=> Fix typo in mail template (#6006)

geoportal/c2cgeoportal_geoportal/__init__.py
=> Also hide capabilities

doc/integrator/tilegeneration.rst
Related to: https://jira.camptocamp.com/browse/GEO-3071
=> Add missing AWS credentials

ci/create-new-project, geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose-lib.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/env.project_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/qgisserver/geomapfish.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl
=> Be able to change the port for the slave database

admin/c2cgeoportal_admin/templates/widgets/dimension.pt
=> Add missing field in dimension form template

geoportal/c2cgeoportal_geoportal/scaffolds/create/qgisserver/geomapfish.yaml.tmpl_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/+dot+upgrade.yaml_tmpl
Fix: https://jira.camptocamp.com/browse/GEO-3078
=> Fix main schema in QGIS config

doc/integrator/backend_qgis.rst
=> Update the QGIS server documentation

geoportal/c2cgeoportal_geoportal/views/layers.py
=> Error message typo

geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_Makefile_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_vars.yaml_tmpl
To be able to use INSTANCE as runtime environment variable
=> Replace INSTANCE by DOCKER_INSTANCE in the vars files

CONTRIBUTING.md, DEVELOPING.md
This is based on the Openlayers one, what do we do with the 'Asking Questions'?
=> Add CONTRIBUTING.md and DEVELOPING.md files

docker/qgisserver/geomapfish_qgisserver/accesscontrol.py, docker/qgisserver/tests/functional/accesscontrol_test.py
=>  No rights if OGC server isn't found instead of error 

.github/workflows/ci.yaml, docker/qgisserver/geomapfish_qgisserver/accesscontrol.py, docker/qgisserver/tests/functional/accesscontrol_test.py
=> No rights if OGC server isn't found instead of error

ci/publish
=> Fix QGIS deploy

Dockerfile, bin/eval-templates, bin/run, bin/run-git, bin/transifex-init, bin/update-po, ci/create-new-project, ci/extract-documentation, ci/publish, ci/publish-documentation, ci/publish-pypi, ci/release-tag, ci/test-app, ci/test-upgrade, doc/build.sh, docker/config/bin/entrypoint, docker/test-mapserver/eval-templates, geoportal/c2cgeoportal_geoportal/scaffolds/create/run_alembic.sh
=> Use bash -u everywhere

.github/workflows/rebuild-25.yaml, .github/workflows/rebuild-qgis-25.yaml
=> Add rebuild bump major version

.github/workflows/backport.yaml
=> Use an other token for backport

geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py, scripts/upgrade
This reverts commit 5eac4b206b7bd12c20dce78fddc1c7e8d6dcc07d.
=> Revert "Fix used version during upgrade"

geoportal/c2cgeoportal_geoportal/views/theme.py
=> Force the background to always be mixed

Pipfile, Pipfile.lock
For https://github.com/camptocamp/getitfixed/pull/49
=> Upgrade getitfixed to 1.0.13

doc/administrator/mapfile.rst
=> Remove, no more valid

.github/workflows/qgis.yaml, docker-compose.yaml, docker/qgisserver/acceptance-tests/acceptance-tests, docker/qgisserver/docker-compose.yaml, docker/qgisserver/geomapfish_qgisserver/accesscontrol.py, docker/qgisserver/tests/functional/accesscontrol_allow_to_edit_test.py, docker/qgisserver/tests/functional/accesscontrol_test.py, docker/qgisserver/tests/functional/conftest.py
Fix: https://sentry.io/organizations/camptocamp/issues/1452169136/?environment=prod-2-5&project=1851011&query=is%3Aunresolved, https://sentry.io/organizations/camptocamp/issues/1384751595/?environment=prod-2-5&project=1851011&query=is%3Aunresolved
=> Fix DB sessions timeouts

geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl
=> Add queryTolerance metadata

geoportal/c2cgeoportal_geoportal/lib/lingua_extractor.py
=> Add missing add_tween

Pipfile, Pipfile.lock, admin/c2cgeoportal_admin/views/layers_wms.py, admin/c2cgeoportal_admin/views/layers_wmts.py
I upgrade c2cgeoform in GMF 2.5 as we will need it soon for GetItFixed upgrade.
But my primary objective now is to fix: https://github.com/camptocamp/c2cgeoportal/pull/6495
=> Upgrade c2cgeoform to 2.1.14

admin/c2cgeoportal_admin/routes.py, admin/config.yaml, admin/tests/tests.yaml, doc/integrator/admin_interface.rst, geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_config-schema.yaml
- More explicit
- Be able to exclude and include an element to change the order
=> Fix include/exclude in admin interface

travis/requirements.txt
See: https://github.com/camptocamp/c2cgeoportal/runs/805792516?check_suite_focus=true
=> [security] Upgrade pyyaml

.github/workflows/ngeo-25.yaml
See: https://github.com/camptocamp/c2cgeoportal/runs/803202760?check_suite_focus=true
=> Fix upgrade ngeo workflow

Pipfile, Pipfile.lock
Fix _item_actions() got an unexpected keyword argument 'readonly'
https://sentry.io/organizations/camptocamp/issues/1744954624/?project=1851011&referrer=AssignedActivityEmail
=> Upgrade getitfixed to version 1.0.14

docker/build/requirements.txt, travis/requirements.txt
See: https://github.com/camptocamp/c2cgeoportal/runs/809709356?check_suite_focus=true
=> [Security] Upgrade twine

geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_vars.yaml_tmpl
=> Add missing geotablePrimaryKey metadata

doc/integrator/create_application.rst.tmpl
=> Doc: fix typos

Pipfile, Pipfile.lock
Fix overlapping routes between admin and getifixed.
=> Fix route conflict with getitfixed

geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_Makefile_tmpl
=> Fix locales theme2fts

ci/create-new-project, ci/test-upgrade, geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py
To have less diff on the upgrade
=> Run eslint befor doing the upgrade

geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+editorconfig, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/vars.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl
=> More ngeo options in the YAML config

.pylintrc, Pipfile, Pipfile.lock, checks.mk, docker/qgisserver/python/3.6/Pipfile, docker/qgisserver/python/3.6/Pipfile.lock, docker/qgisserver/python/3.8/Pipfile, docker/qgisserver/python/3.8/Pipfile.lock, geoportal/c2cgeoportal_geoportal/lib/lingua_extractor.py, setup.cfg
And fix isort from Visual Studio Code
=> Use pylint to check the import order

geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/vars.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl
=> Some fix in the ngeo options

geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/vars.yaml_tmpl
Less duplications
Remove demo values
Fix 2056, => 2056
Fix unsupported .Inf => 9999
=> Config in YAML imporvements

ci/publish
To work with https://github.com/camptocamp/c2cgeoportal/commit/63564b0157e0e989f98ccf09b930638b280ce5d2
=> Fix publish from ngeo change

.github/workflows/ci.yaml
See e.-g.: https://github.com/camptocamp/c2cgeoportal/runs/1056864435?check_suite_focus=true
=> Don't fail on unneeded apt repository fetch

Pipfile, ci/Pipfile, ci/Pipfile.lock, geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+github/workflows/ci.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+prospector.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/create/scripts/publish-docker
=> Publish project Docker images to GitHub Container Registry

ci/test-app, doc/integrator/internationalization.rst, geoportal/c2cgeoportal_geoportal/__init__.py, geoportal/c2cgeoportal_geoportal/lib/i18n.py, geoportal/c2cgeoportal_geoportal/scaffolds/create/Dockerfile_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/Makefile, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/+dot+dockerignore_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/+package+_geoportal/__init__.py_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/+package+_geoportal/models.py_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/Dockerfile_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/vars.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_Makefile_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_config-schema.yaml, geoportal/c2cgeoportal_geoportal/scripts/theme2fts.py, geoportal/tests/test_i18n.py, geoportal/tests/test_init.py
Note that SRC_FILES is empty by default and has to be configured in geoportal/Makefile in GMF projects if needed.
=> Add target update-po and put translations in config

doc/integrator/filter.rst.tmpl
=> Fix typo in the documentation

geoportal/c2cgeoportal_geoportal/views/login.py, geoportal/tests/functional/test_login_2fa.py
=> Don't requires the 2fa on reset password

geoportal/c2cgeoportal_geoportal/views/dynamic.py, geoportal/tests/functional/test_dynamicview.py
=> Fix space in redirect URL

geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/Dockerfile_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_Makefile_tmpl
=> Remove Webpack progress mode

geoportal/c2cgeoportal_geoportal/views/layers.py
=> Fix geo_table with environment variables

geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scripts/theme2fts.py, geoportal/tests/functional/test_theme2fts.py
And base test for the theme2fts script.
=> Add metadata searchAlias

doc/index.rst.tmpl
=> Fix documentation links

doc/developer/debugging.rst, doc/integrator/upgrade_application.rst.tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/build_tmpl, geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py, scripts/upgrade
For now it is a pain to debug the upgrade procedure (or I miss something).
Here is a PR to be able to debug the upgrade procedure easily.
Note sure this is the better way to do it, but it is a good base for discussion.
=> Allow to debug upgrade procedure

.github/workflows/rebuild-qgis-25.yaml, .github/workflows/status.yaml, scripts/create-status-page, scripts/status.yaml
Used to generate the status page:
https://github.com/camptocamp/c2cgeoportal/wiki/Status
=> Add status page generator

ci/changelog
- No more duplicated release
- No more empty release
=> Changelog fix

doc/integrator/ngeo.rst.tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/vars.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_config-schema.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl, geoportal/c2cgeoportal_geoportal/views/dynamic.py, geoportal/tests/functional/test_dynamicview.py
This pull request is the first step for moving the API configuration to the configuration. The 3 steps are:
- Create the new configuration in c2cgeoportal.
- Using this new configuration from ngeo.
- Clean up old settings in c2cgeoportal, fill the CONST_CHANGLOG, ...
=> Add api interface config

geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+gitignore_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/build_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/project.yaml_tmpl
So that we can use a personal env file, that is not committed
=> Use personal env file for local development without breaking the CI

geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose-lib.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/qgisserver/geomapfish.yaml.tmpl_tmpl
=> All database configuration from the config container got the QGIS plugin

geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/+package+_geoportal/__init__.py_tmpl
See https://jira.camptocamp.com/browse/GEO-3834 for details.
=> Give the priority to the translations of the root package

doc/integrator/ngeo.rst.mako
As asked.
Should be the same for 2.5, 2.6
=> Doc - Explain how to extend ngeo

scripts/create-status-page, scripts/status.yaml
To easier follows what is used by version.
=> Add used by column

doc/integrator/api.rst, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/+package+_geoportal/static-ngeo/api/index.js_tmpl
The CHANGELOG modifications will be in a separate pull request...
=> Fix the API configuration

geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+gitignore_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/+dot+upgrade.yaml_tmpl, scripts/status.yaml
For the Makefile actually he is always removed and recreated again see e.-g.:
https://github.com/camptocamp/demo_geomapfish/commit/3cd0ace88faf8ba7d13159bd458c9c863526aa05
=> Some little fix

docker-compose.yaml, docker/test-tilecloudchain/config.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl, geoportal/c2cgeoportal_geoportal/views/theme.py, geoportal/tests/functional/__init__.py, geoportal/tests/functional/test_themes_dimensions.py, geoportal/tests/functional/test_themes_edit_columns.py, geoportal/tests/functional/test_themes_entry.py, geoportal/tests/functional/test_themes_metadata.py, geoportal/tests/functional/test_themes_time.py
New attempt at solving the issue of layers not loading following a WMS GetCapabilties failure
=> Do not add layer to theme if GetCapabilities fails

scripts/create-status-page, scripts/status.yaml
Add repository mutualized print logs
Reorganize(GeoMapFish - GitHub actions - OpenShift and other)
Add some more needed workflows
Display the step name only for QGIS build in c2cgeoportal (The versions are not any more needed, now it's checked by c2cciutils)
=> Some status changes

admin/c2cgeoportal_admin/schemas/treegroup.py, admin/c2cgeoportal_admin/static/theme.css, admin/c2cgeoportal_admin/templates/widgets/child.pt, admin/c2cgeoportal_admin/templates/widgets/children.pt, admin/c2cgeoportal_admin/templates/widgets/restriction_area_fields.pt, admin/c2cgeoportal_admin/templates/widgets/role_fields.pt, admin/c2cgeoportal_admin/views/restriction_areas.py, admin/c2cgeoportal_admin/views/roles.py, admin/c2cgeoportal_admin/views/themes_ordering.py, admin/c2cgeoportal_admin/widgets.py, admin/tests/test_restriction_areas.py, admin/tests/test_role.py, commons/c2cgeoportal_commons/models/main.py, commons/c2cgeoportal_commons/models/static.py
Factorize child widget for use in layers group, theme ordering, restriction area and role forms.
Add layers in restriction area form.
Add users in role form.
Add edit links in child widget.
=> [admin] Add layers in restriction area form

geoportal/c2cgeoportal_geoportal/scaffolds/update/+dot+upgrade.yaml_tmpl
see:
https://github.com/camptocamp/demo_geomapfish/commit/c5f0f20144990e2ea64a6981d805a60fa922f05b
https://github.com/camptocamp/demo_geomapfish/commit/9dc076d92af3eb97cc3d2324c03abbe7ccee16c8
=> No back an forward move

.github/workflows/main.yaml, .github/workflows/rebuild-25.yaml
=> Fix the rebuild and publish

docker-run
Fix home directory setting in docker-run script, necessary for example when using sigdev with npm
=> Script docker-run: fix home directory setting

geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl
see also: https://github.com/camptocamp/ngeo/pull/6652
=> Hide the timezone

geoportal/c2cgeoportal_geoportal/views/fulltextsearch.py, geoportal/tests/functional/test_fulltextsearch.py
=> Ignore startup quote on all the search therm

docker/qgisserver/geomapfish_qgisserver/accesscontrol.py, docker/qgisserver/tests/geomapfish.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/create/qgisserver/geomapfish.yaml.tmpl_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_config-schema.yaml
=> Fix the Session in QGIS

geoportal/c2cgeoportal_geoportal/views/raster.py, geoportal/tests/test_raster.py
=> Fix round on too big value

doc/integrator/urllogin.rst
=> Fix doc for urllogin according to fix #5160 from GMF 2.3

doc/administrator/administrate.rst.tmpl
=> Add documentation about wms-defaults and wmts-defaults

geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl
To work with https://github.com/camptocamp/ngeo/pull/6710
=> Better Sentry preconfiguration

geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl
Use new ASIT URL, source: https://www.asitvd.ch/chercher/actualites-fournisseurs.html
I also renamed:
- `ASIT VD` > `ASIT`
- `Swiss Topo` > `swisstopo`
=> Update demo external OGC servers

geoportal/c2cgeoportal_geoportal/lib/authentication.py, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/+package+_geoportal/__init__.py_tmpl
UrlAuthentication need settings from config.yaml
UrlAuthentication should be checked before cookie.
=> Fix urllogin authentication

doc/conf.py
=> Update doc copyright (#7674)

bin/run, scripts/upgrade
=> Fix upgrade for Windows

doc/integrator/caching.rst
=> Update the documentation to invalidate the cache

geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose-lib.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/tilegeneration/config.yaml.tmpl_tmpl
To be able to generate the WMTS legend
See result
https://geomapfish-demo-2-6.camptocamp.com/tiles/admin/
=> Add some more generation commands

admin/c2cgeoportal_admin/lib/ogcserver_synchronizer.py, admin/tests/lib/test_ogcserver_synchronizer.py, checks.mk, commons/c2cgeoportal_commons/lib/url.py, commons/c2cgeoportal_commons/models/main.py, commons/tests/lib/test_url.py, docker/qgisserver/Dockerfile, docker/test-tilecloudchain/config.yaml, geoportal/c2cgeoportal_geoportal/lib/__init__.py, geoportal/c2cgeoportal_geoportal/lib/dbreflection.py, geoportal/c2cgeoportal_geoportal/lib/filter_capabilities.py, geoportal/c2cgeoportal_geoportal/lib/layers.py, geoportal/c2cgeoportal_geoportal/lib/lingua_extractor.py, geoportal/c2cgeoportal_geoportal/views/mapserverproxy.py, geoportal/c2cgeoportal_geoportal/views/ogcproxy.py, geoportal/c2cgeoportal_geoportal/views/pdfreport.py, geoportal/c2cgeoportal_geoportal/views/proxy.py, geoportal/c2cgeoportal_geoportal/views/theme.py, geoportal/c2cgeoportal_geoportal/views/tinyowsproxy.py, geoportal/tests/__init__.py, geoportal/tests/functional/test_dbreflection.py
Fix: https://jira.camptocamp.com/browse/GSGMF-1474
=> Don't parse the URL many times

build.mk, ci/test-new-project, ci/waitwsgi, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/+dot+eslintrc_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/+dot+prospector.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/vars.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py
Do some other little changes found during the first migration...
=> Update the changelog

geoportal/c2cgeoportal_geoportal/views/shortener.py
Tested in a GMF 2.5 project. I can port it to master if this change is OK.
=> Make shortener not allowed host exception more explicit

scripts/create-status-page, scripts/status.yaml
=> Fix the status page by using the new URL

.hadolint.yaml
https://github.com/hadolint/hadolint
=> Add Haskell Dockerfile Linter config

geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+github/workflows/ci.yaml_tmpl
Fix github CI template (follow up to https://github.com/camptocamp/c2geoportal/commit/8677e88e11dff90a5aa9e2f8988b1c188f8c1ca8)
=> Fix GitHub CI template

geoportal/c2cgeoportal_geoportal/views/theme.py
=> Fix filter on private layers

geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/vars.yaml_tmpl
=> Add measure point to update_path

geoportal/c2cgeoportal_geoportal/scaffolds/create/build_tmpl
=> Pull the base images before building the image

geoportal/c2cgeoportal_geoportal/scaffolds/create/build_tmpl
=> Don't use the --pull in CI

doc/integrator/admin_interface.rst, doc/integrator/create_application.rst.tmpl, doc/integrator/extend_data_model.rst, doc/integrator/index.rst, doc/integrator/internationalization.rst, doc/integrator/make.rst.tmpl, doc/integrator/multiple_databases.rst, doc/integrator/ngeo.rst.tmpl, doc/integrator/ngeo_new_interface.rst, doc/integrator/structure.rst
=> Add documentation for the simple application mode

Dockerfile, bin/build-l10n, geoportal/c2cgeoportal_geoportal/scaffolds/create/Dockerfile_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/build_tmpl
Replace: https://github.com/camptocamp/demo_geomapfish/pull/222/
Fix: GSGMF-1489
=> Fix admin i18n in simple application mode

ci/changelog
=> Fix open pull request in changelog

Dockerfile
=> Have Redis cli in the tool container

scripts/status.yaml
=> Update the versions in status

geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+github/workflows/main.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/build_tmpl
=> Build an CI simple mode auto detection

geoportal/c2cgeoportal_geoportal/lib/authentication.py
Fix: https://sentry.io/organizations/camptocamp/issues/2311106404/?environment=prod-2-6&project=1851011&referrer=alert_email
=> Fix OAuth2 authentication

geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose-lib.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose.override.sample.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/create/env.default_tmpl
=> Move scaffold variable from docker-compose* to the env.default file

geoportal/c2cgeoportal_geoportal/__init__.py, geoportal/c2cgeoportal_geoportal/lib/__init__.py, geoportal/c2cgeoportal_geoportal/lib/functionality.py, geoportal/tests/__init__.py, geoportal/tests/functional/test_login.py, geoportal/tests/functional/test_themes_loop.py
This can be required to have multiple organization in one container
=> Make standard roles customisable

geoportal/c2cgeoportal_geoportal/views/tinyowsproxy.py
=> Tiny OWS didn't support _ in query string

scripts/create-status-page
By the way shouldn't it be moved to https://github.com/camptocamp/geospatial-dashboards?
=> Add Dependabot vulnerabilities and issues in status page

ci/test-app, geoportal/c2cgeoportal_geoportal/__init__.py, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/+package+_geoportal/__init__.py_tmpl, geoportal/tests/test_init.py
The fautive: https://github.com/camptocamp/c2cgeoportal/pull/7690
Fix: GSGMF-1569
=> Fix admin login

doc/integrator/backend_qgis.rst, geoportal/c2cgeoportal_geoportal/views/mapserverproxy.py, geoportal/c2cgeoportal_geoportal/views/ogcproxy.py, geoportal/c2cgeoportal_geoportal/views/proxy.py, geoportal/c2cgeoportal_geoportal/views/tinyowsproxy.py
See also: https://github.com/qgis/QGIS/pull/41333
Fix: GSGMF-1449
=> Use the service URL

Pipfile, Pipfile.lock, admin/c2cgeoportal_admin/views/ogc_servers.py, commons/c2cgeoportal_commons/models/main.py
Require https://github.com/camptocamp/c2cgeoform/pull/233
=> Show message on ogcserver delete if contains layers

geoportal/c2cgeoportal_geoportal/views/login.py, geoportal/tests/functional/test_login.py
=> Fix came_from in the login panel

doc/administrator/mapfile.rst
See also: https://trac.osgeo.org/gdal/wiki/CloudOptimizedGeoTIFF
=> More optimized files

docker/qgisserver/geomapfish_qgisserver/accesscontrol.py
See current behaviour: https://jira.camptocamp.com/browse/GEO-4425?focusedCommentId=208165&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-208165
=> Handle uninitialized plugin on cacheKey

geoportal/c2cgeoportal_geoportal/scaffolds/create/tilegeneration/config.yaml.tmpl_tmpl
See also: https://sentry.io/organizations/camptocamp/issues/2387049193/?project=1851011&referrer=RegressionActivityEmail
=> Fix duplicated -q argument

scripts/updated_version
Fix: GSGMF-1603, See result:  #8271
=> Add a script to get the versions upgrades

docker/build/requirements.txt
```
+==============================================================================+
|                                                                              |
|                               /$$$$$$            /$$                         |
|                              /$$__  $$          | $$                         |
|           /$$$$$$$  /$$$$$$ | $$  \__//$$$$$$  /$$$$$$   /$$   /$$           |
|          /$$_____/ |____  $$| $$$$   /$$__  $$|_  $$_/  | $$  | $$           |
|         |  $$$$$$   /$$$$$$$| $$_/  | $$$$$$$$  | $$    | $$  | $$           |
|          \____  $$ /$$__  $$| $$    | $$_____/  | $$ /$$| $$  | $$           |
|          /$$$$$$$/|  $$$$$$$| $$    |  $$$$$$$  |  $$$$/|  $$$$$$$           |
|         |_______/  \_______/|__/     \_______/   \___/   \____ …
```
=> [Security] Upgrade aws-cli

geoportal/c2cgeoportal_geoportal/views/theme.py
=> Be able to have deep layer structure

geoportal/c2cgeoportal_geoportal/lib/lingua_extractor.py
To avoid:
```
Traceback (most recent call last):
File "/usr/local/bin/pot-create", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/lingua/extract.py", line 453, in main
save_catalog(catalog, output)
File "/usr/local/lib/python3.8/dist-packages/lingua/extract.py", line 249, in save_catalog …
```
=> Add asserts to be sure that the messageid are not None

geoportal/c2cgeoportal_geoportal/scaffolds/create/Dockerfile_tmpl
Avoid thge following errors:
13 0.759 chmod: changing permissions of '/etc/resolv.conf': Read-only file system
13 0.848 chmod: changing permissions of '/etc/hosts': Read-only file system
See also:
https://docs.docker.com/develop/develop-images/build_enhancements/
=> Fix build with BuildKit

bin/build-l10n, doc/integrator/internationalization.rst
Currently, the po files were removed on the first call => do only one call
Convert in Python to have the Python argument parser
=> Fix issue with Different localisation sets

Dockerfile
=> Don't use binaries

geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+dockerignore_tmpl
It will creates an error because it will be considered as a language...
GSGMF-1616
=> Don't copy the pot files in the container

.github/workflows/qgis.yaml, geoportal/c2cgeoportal_geoportal/views/fulltextsearch.py
See also: https://sentry.io/organizations/camptocamp/issues/2461184722/?environment=prod-25&project=1854709
=> Fix error when we introduce a tab

geoportal/c2cgeoportal_geoportal/views/printproxy.py
See: https://sentry.io/organizations/camptocamp/issues/2468059235/?environment=prod-2-7&project=1851011
=> Fix print Capabilities

.github/workflows/qgis.yaml, .github/workflows/rebuild-qgis-26.yaml
Remove master on 2.6
Remove 3.10 on master
Add 3.20 on master
=> Update the included QGIS version

Pipfile, Pipfile.lock, ci/test-app, doc/administrator/mapfile.rst, docker/test-mapserver/mapserver.map.tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/mapserver/demo.map.tmpl_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/mapserver/mapserver.map.tmpl_tmpl
=> Install and test mappyfile

doc/administrator/administrate.rst.tmpl
=> Copy the UI metadata from ngeo, to be able to find them with the search

geoportal/c2cgeoportal_geoportal/views/mapserverproxy.py
Fix some typo
Related to GEO-4467
=> Send MapServer substitution only on MapServer with standard auth

geoportal/c2cgeoportal_geoportal/views/theme.py
=> Fix the child layers on groups

Pipfile, Pipfile.lock, ci/docker-compose.override.yaml, commons/c2cgeoportal_commons/alembic/env.py, geoportal/c2cgeoportal_geoportal/__init__.py, geoportal/c2cgeoportal_geoportal/lib/loader.py, geoportal/c2cgeoportal_geoportal/lib/metrics.py
=> Fix duplicated environment variable with different cass

Pipfile, Pipfile.lock, geoportal/c2cgeoportal_geoportal/__init__.py, geoportal/c2cgeoportal_geoportal/lib/metrics.py
To fix too many logs on OpenShift
=> Bump c2cwsgiutils version to 4.1.3

admin/c2cgeoportal_admin/lib/ogcserver_synchronizer.py, admin/c2cgeoportal_admin/templates/ogcserver_synchronize.jinja2, admin/c2cgeoportal_admin/views/ogc_servers.py, admin/tests/lib/test_ogcserver_synchronizer.py
Related to https://jira.camptocamp.com/browse/GEO-4591
Would like to merge this new feature in 2.6
=> Add option to force parents in OGCServerSynchronizer

ci/config.yaml
Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')
See also: http://cwe.mitre.org/data/definitions/22.html
=> Ignore CWE-22

admin/c2cgeoportal_admin/lib/ogcserver_synchronizer.py, admin/c2cgeoportal_admin/templates/ogcserver_synchronize.jinja2, admin/c2cgeoportal_admin/views/ogc_servers.py, admin/tests/lib/test_ogcserver_synchronizer.py, admin/tests/test_ogc_servers.py, commons/c2cgeoportal_commons/models/main.py
=> OGC server synchronizer force ordering

geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+github/workflows/rebuild.yaml_tmpl
See: https://github.com/camptocamp/demo_geomapfish/runs/3396278846?check_suite_focus=true
=> Fix rebuild: Remove extra $ 

commons/c2cgeoportal_commons/lib/url.py, doc/integrator/backend_qgis.rst, docker/qgisserver/.pylintrc, docker/qgisserver/geomapfish_qgisserver/accesscontrol.py, docker/qgisserver/tests/functional/accesscontrol_test.py, docker/qgisserver/tests/functional/conftest.py, geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose-lib.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
=> Simplify the mapping config for QGIS server

geoportal/c2cgeoportal_geoportal/views/__init__.py, geoportal/c2cgeoportal_geoportal/views/proxy.py, geoportal/c2cgeoportal_geoportal/views/theme.py
Fix GEO-4639 (part two, first part is here #8650 )
=> Filter headers in theme.py too

geoportal/c2cgeoportal_geoportal/scaffolds/create/print/print-apps/+package+/config.yaml.tmpl, geoportal/c2cgeoportal_geoportal/views/proxy.py, geoportal/tests/__init__.py
For GEO-4666
Manual Backport of #8701 (plus some previous PR)
=> Manually [Backport 2.4] Add alternative X-Forward headers in proxy  

geoportal/c2cgeoportal_geoportal/views/theme.py
See also: https://sentry.io/organizations/camptocamp/issues/2633701839/?environment=prod-2-6&project=1851011&query=is%3Aunresolved
=> Don't do WFS query on server that didn't support WFS

ci/test-app, doc/integrator/build.rst.tmpl, doc/integrator/configuration.rst, geoportal/c2cgeoportal_geoportal/scaffolds/__init__.py, geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+github/workflows/main.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/+dot+github/workflows/rebuild.yaml_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/Dockerfile_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/build_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose-lib.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/Dockerfile_tmpl
=> Use docker-compose build to build the project

Dockerfile, Pipfile, Pipfile.lock
See: https://github.com/camptocamp/c2cgeoportal/runs/3773987635?check_suite_focus=true
=> Bump pycryptodome from 3.8.1 to 3.10.3

geoportal/c2cgeoportal_geoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl
=> Add updated package version

doc/administrator/mapfile.rst, doc/integrator/backend_qgis.rst
Also, trigger the CI to get a version `2.4.2.60`
=> Fix typo in doc

Pipfile, Pipfile.lock
```
+==============================================================================+
|                                                                              |
|                               /$$$$$$            /$$                         |
|                              /$$__  $$          | $$                         |
|           /$$$$$$$  /$$$$$$ | $$  \__//$$$$$$  /$$$$$$   /$$   /$$           |
|          /$$_____/ |____  $$| $$$$   /$$__  $$|_  $$_/  | $$  | $$           |
|         |  $$$$$$   /$$$$$$$| $$_/  | $$$$$$$$  | $$    | $$  | $$           |
|          \____  $$ /$$__  $$| $$    | $$_____/  | $$ /$$| $$  | $$           |
|          /$$$$$$$/|  $$$$$$$| $$    |  $$$$$$$  |  $$$$/|  $$$$$$$           |
|         |_______/  \_______/|__/     \_______/   \___/   \____ …
```
=> Update dependency with security issues

admin/c2cgeoportal_admin/schemas/functionalities.py, admin/c2cgeoportal_admin/schemas/metadata.py, admin/c2cgeoportal_admin/views/layer_groups.py, admin/c2cgeoportal_admin/views/layers_vectortiles.py, admin/c2cgeoportal_admin/views/layers_wms.py, admin/c2cgeoportal_admin/views/layers_wmts.py, admin/c2cgeoportal_admin/views/roles.py, admin/c2cgeoportal_admin/views/themes.py, admin/config.yaml, admin/tests/schemas/test_functionalities.py, admin/tests/schemas/test_metadata.py, admin/tests/test_edit_url.py, admin/tests/test_metadatas.py, admin/tests/test_role.py, admin/tests/test_themes.py, admin/tests/tests.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_config-schema.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl
Still some doubt about which functionality is relavant for themes or roles.
TODO: complete CONST_vars with relevant_for in available_functionalities.
=> Filter metadatas in admin forms

doc/integrator/ngeo.rst.tmpl
For GSGMF-1650
See also code poc/test at https://github.com/camptocamp/demo_geomapfish/pull/281/files
=> Update documentation about ngeo

Pipfile, Pipfile.lock
See: https://github.com/redis/redis-py/issues/1714
=> Downgrade redis to 3.5. until 4.0.2 is released

.prospector.yaml, geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py
see also: https://github.com/camptocamp/demo_geomapfish/runs/4314747457?check_suite_focus=true
=> Have a better upgrade error

.github/workflows/main.yaml, bin/update-po, build.mk, ci/test-app, doc/developer/webservices.rst, doc/integrator/internationalization.rst, geoportal/c2cgeoportal_geoportal/__init__.py, geoportal/c2cgeoportal_geoportal/lib/lingua_extractor.py, geoportal/c2cgeoportal_geoportal/scaffolds/advance_update/geoportal/CONST_Makefile_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/env.default_tmpl, geoportal/c2cgeoportal_geoportal/views/i18n.py, geoportal/tests/functional/conftest.py, geoportal/tests/functional/test_lingua_extractor_angular.py, geoportal/tests/functional/test_lingua_extractor_config.py, geoportal/tests/functional/test_lingua_extractor_themes.py, geoportal/tests/functional/test_theme2fts.py
GSGMF-1563 
TODO : Add https://github.com/camptocamp/c2cgeoportal/compare/2.6...gsgmf-1481-test-lingua-extrator
=> Add view to get the localisation keys

Pipfile, ci/config.yaml, commons/setup.py, geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/.editorconfig, geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/.github/workflows/main.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/build, geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/ci/config.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/ci/trigger, geoportal/requirements.txt
=> Better build, ci for custom, use psycopg2 instead of psycopg2-binary

Pipfile, Pipfile.lock
See https://jira.camptocamp.com/browse/GEO-4928
=> Security upgrade for c2cgeoform/getitfixed

ci/docker-compose.override.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/.github/workflows/update_l10n.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/Makefile, geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose-lib.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.override.sample.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.yaml
Fix working directory
Initialize Git
Commit and create a pull request only if there is some changes
Fix GITHUB_REPOSITORY
No error if the pull request already exists
Remove the POT-Creation-Date
Add missing SUFFIX
Tools don't depend on config by default
=> Fix l10n action

docker/qgisserver/geomapfish_qgisserver/__init__.py
The print isn't displayed
Using logging before logging plugin initialization don't works
=> Fix QGIS plugin initialisation logs

Dockerfile, doc/integrator/docker.rst, geoportal/c2cgeoportal_geoportal/scaffolds/create/docker-compose-lib.yaml, geoportal/c2cgeoportal_geoportal/views/theme.py
=> Make the timeout in theme configurable

doc/developer/webservices.rst, docker/qgisserver/README.md, docker/test-tilecloudchain/config.yaml, geoportal/c2cgeoportal_geoportal/lib/wmstparsing.py, geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/mapserver/mapserver.map.tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/tilegeneration/config.yaml.tmpl, geoportal/c2cgeoportal_geoportal/scripts/theme2fts.py
=> Fix 'default to' to 'default is'

geoportal/c2cgeoportal_geoportal/scaffolds/update/geoportal/CONST_vars.yaml_tmpl
https://github.com/camptocamp/ngeo/pull/7881, GSGMF-1694
=> Add timeout for ngeo

ci/test-app, geoportal/c2cgeoportal_geoportal/scaffolds/advance_create/{{cookiecutter.project}}/geoportal/development.ini, geoportal/c2cgeoportal_geoportal/scaffolds/advance_create/{{cookiecutter.project}}/geoportal/production.ini
=> Be able to use pserve, proutes and pviews

geoportal/c2cgeoportal_geoportal/views/theme.py
=> Don't fill OGCServers with unused, Better logs

commons/c2cgeoportal_commons/lib/url.py
See also: https://sentry.io/organizations/camptocamp/issues/2730518900/?project=1851011
=> Add a repr method for Sentry

geoportal/c2cgeoportal_geoportal/views/ogcproxy.py, geoportal/tests/functional/test_ogcproxy.py
See https://jira.camptocamp.com/browse/GEO-5182
=> Support uppercase for OGCSERVER parameter

geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/CONST_CHANGELOG.txt
Fix [GSGMF-1815](https://jira.camptocamp.com/browse/GSGMF-1815)
=> Better documentation for LIDAR profile integration

geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/CONST_CHANGELOG.txt
Doc related to [GSGMF-1810](https://jira.camptocamp.com/browse/GSGMF-1810) issues
=> Doc for low-level migrated web components

admin/config.yaml, admin/tests/tests.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_vars.yaml
=> Fix some typo

geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/CONST_CHANGELOG.txt
Fix [GSGMF-1852](https://jira.camptocamp.com/browse/GSGMF-1852)
=> Add to changelog missing close button for LIDAR

admin/c2cgeoportal_admin/lib/lingua_extractor.py, admin/config.yaml, admin/tests/tests.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_vars.yaml
@arnaud-morvan do you know if the HTML working here?
=> Add documentation to mapserver_substitution functionality

CHANGELOG.md, ci/changelog, commons/c2cgeoportal_commons/models/main.py
Move the URL in the code, change the text of the link
=> Fix the URL

geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.yaml
=> Add missing volume for update-po

geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose.yaml
This reverts commit 8885203bf93f4a37214c90f3a1e0907f6b995a44.
=> Revert "Add missing volume for update-po"

geoportal/c2cgeoportal_geoportal/lib/filter_capabilities.py, geoportal/c2cgeoportal_geoportal/views/tinyowsproxy.py, geoportal/tests/functional/test_tinyowsproxy.py
=> Use the URL on Tinyows, not on MapServer

geoportal/c2cgeoportal_geoportal/views/theme.py, geoportal/tests/functional/test_themes_entry.py, geoportal/tests/functional/test_themes_loop.py
Avoid too many context switch between async and std
Don't run _wms_getcap_cached when not needed
=> Better performances to create the theme when we are logged in

geoportal/c2cgeoportal_geoportal/lib/caching.py
After this pull request https://github.com/sqlalchemy/dogpile.cache/pull/191
Pickle is called on memory cache
Fix: GEO-5611
=> Don't call pickle on memory cache

doc/developer/debugging.rst, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/+package+_geoportal/__init__.py_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/Dockerfile_tmpl, geoportal/c2cgeoportal_geoportal/scaffolds/create/geoportal/requirements.txt
`ptvsd` is deprecated, I updated the doc accordingly.
=> Upgrade to `debugpy`

commons/c2cgeoportal_commons/models/sqlalchemy.py, geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_vars.yaml
Fix [GSGMF-1893](https://jira.camptocamp.com/browse/GSGMF-1893)
=> Remove warnings

geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/CONST_CHANGELOG.txt
https://jira.camptocamp.com/browse/GSGMF-1897
Follow https://github.com/camptocamp/ngeo/pull/8845
=> Add information about URL of external layers in changelog.

docker/build/.snyk
https://security.snyk.io/vuln/SNYK-PYTHON-SETUPTOOLS-3113904
=> Ignore CVE on setuptools

.github/workflows/main.yaml, geoportal/c2cgeoportal_geoportal/__init__.py
From: https://github.com/camptocamp/c2cwsgiutils/blob/release_4/c2cwsgiutils/pretty_json.py
Todo: test it with ticino GMF
=> Remove JSON sort_keys

geoportal/tests/functional/__init__.py, geoportal/tests/functional/test_oauth2.py
- Separate the check
- Test on wrong code or token
- Remove the unused code or token
- Comment the test on wrong code or token that never fail
=> Have better oauth tests, test wrong cases

geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/tests/test_app.py
Removed the un-working loop
Based on demo
=> Update the timeout

geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_vars.yaml
[GSGMF-1935](https://jira.camptocamp.com/browse/GSGMF-1935)
=> Add metadata for search label

geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/geoportal/vars.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/CONST_CHANGELOG.txt, geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_config-schema.yaml, geoportal/c2cgeoportal_geoportal/views/ogcproxy.py
Implements [GSGMF-1931](https://jira.camptocamp.com/browse/GSGMF-1931)
=> Use main_ogc_server from vars.yaml for WMS proxy

geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/.github/workflows/update_l10n.yaml
See also: https://github.com/camptocamp/demo_geomapfish/actions/runs/4050332158/jobs/6967621360
=> Fix the status check

geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/CONST_CHANGELOG.txt
[GSGMF-1959](https://jira.camptocamp.com/browse/GSGMF-1959)
=> Add changelog for WebGL OL rendering

doc/integrator/print.rst, geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_vars.yaml
[GSGMF-1960](https://jira.camptocamp.com/browse/GSGMF-1960)
=> Add doc for print template attributes

geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/build
We get this error on the images that should be build locally
=> No error on pull

geoportal/c2cgeoportal_geoportal/__init__.py, geoportal/c2cgeoportal_geoportal/lib/authentication.py, geoportal/tests/functional/test_login.py
=> Check if user has been deactivated

geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/Makefile
=> Don't start directly the composition

geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose-lib.yaml
=> Add missing AZURE_STORAGE_ACCOUNT_URL for tilecloud-chain

doc/administrator/editing.rst
Add more information to the editing rst file based on https://jira.camptocamp.com/servicedesk/customer/portal/6/GEO-6299
=> GEO-6299: Update editing.rst

docker/config/requirements.txt
Put the pinning only on stabilization branch, keep the master branch clean
=> Remove Snyk pinning

bin/import-ngeo-apps
Regression from https://github.com/camptocamp/c2cgeoportal/pull/10364/files
=> Remove double _alt in appName

doc/integrator/build.rst, doc/integrator/configuration.rst, doc/integrator/runtime.rst
Update build documentation,
add documentation for using runtime variables.
=> Add documentation for using runtime variables

geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/geoportal/vars.yaml, geoportal/c2cgeoportal_geoportal/views/theme.py
Fix wasting time in `pickle.load` and in `gc.collect`...
=> Fix theme loading time

build.mk, ci/test-upgrade, geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/geoportal/vars.yaml
This reverts commit ed3078c5b7814de9c878a40991e21f680b8c2d32.
=> Revert "Fix the package name in the apihelp of the simple app"

geoportal/c2cgeoportal_geoportal/views/mapserverproxy.py, geoportal/tests/functional/test_mapserverproxy.py
The previous condition didn't do anything...
=> Fix code return when basic auth is desabled

geoportal/c2cgeoportal_geoportal/lib/authentication.py, geoportal/c2cgeoportal_geoportal/lib/oauth2.py
The main thing is do not check the state if it's not required
=> Fix OAuth2 with some clients

geoportal/c2cgeoportal_geoportal/lib/filter_capabilities.py, geoportal/c2cgeoportal_geoportal/views/tinyowsproxy.py, geoportal/tests/functional/test_tinyowsproxy.py
=> Fix the get URL of tiny OWS

geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/geoportal/vars.yaml
With:
geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/tilegeneration/config.yaml.tmpl
=> The resolutions should corresponds

geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_vars.yaml
Following the doc here:
https://developers.google.com/tag-platform/tag-manager/csp#google_analytics_4_google_analytics
=> Add content-security-policy for Google Analytics 4

doc/administrator/mapfile.rst
Add a note for layer with no template : label layers with no wms / wfs query needed -> avoid performance loss
=> [Doc Admin] Add a note for layer with no template

.github/renovate.json5, .github/workflows/dependency-update-review.yaml, .pre-commit-config.yaml, ci/config.yaml, ci/project-config.yaml
This is done by the automated script named upgrade-c2cciutils-to-1.6
=> Update to c2cciutils version 1.6 (CI updates)

.pre-commit-config.yaml, .prospector.yaml, poetry.lock, pyproject.toml
See: https://pypi.org/project/prospector-profile-duplicated/
This is done by the automated script named use-prospector-profile
=> Use the new Prospector profile to avoid conflict or duplicated

geoportal/c2cgeoportal_geoportal/scaffolds/advance_create/{{cookiecutter.project}}/geoportal/webpack.api.js, geoportal/c2cgeoportal_geoportal/scaffolds/advance_create/{{cookiecutter.project}}/geoportal/webpack.apps.js, geoportal/c2cgeoportal_geoportal/scaffolds/advance_create/{{cookiecutter.project}}/geoportal/webpack.commons.js
Fix the target according the documentation
=> Use a working babel/preset-env configuration

geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose-lib.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/scripts/db-backup, geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/scripts/db-restore
The PG environment variable can't be set to the database container
=> Fix database initialization

.github/renovate.json5, .github/workflows/audit.yaml, .github/workflows/backport.yaml, .github/workflows/clean.yaml, .github/workflows/delete-old-workflow-run.yaml, .github/workflows/main.yaml, .github/workflows/pr-checks.yaml
This is done by the automated script named upgrade-c2cciutils-to-1.7
=> CI updates

doc/administrator/editing.rst, geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_vars.yaml
=> Improve documentation on snapping

doc/integrator/database.rst, doc/integrator/docker.rst, doc/integrator/tilegeneration_doc.rst
=> Clarify the main/static schema separation, fix some typo

.pre-commit-config.yaml, admin/setup.py, commons/setup.py, geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/.pre-commit-config.yaml, scripts/clone_schema.sql
https://github.com/pre-commit/pre-commit-hooks?tab=readme-ov-file#trailing-whitespace
https://github.com/pre-commit/pre-commit-hooks?tab=readme-ov-file#mixed-line-ending
=> Add some useful options

.github/workflows/qgis.yaml
Followup to https://github.com/camptocamp/docker-qgis-server/pull/918
=> Add debug image to be able to debug QGIS

geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/build
in place of --ignore-pull-failures
=> Use the new --ignore-buildable argument

.github/workflows/main.yaml
=> Publish the Python packages to pypi

ci/config.yaml
See JIRA issue: [GEO-7466](https://jira.camptocamp.com/browse/GEO-7466).
=> Add pypi group

.github/workflows/main.yaml, doc/integrator/requirements.rst
See JIRA issue: [GSGMF-1324](https://jira.camptocamp.com/browse/GSGMF-1324).
=> Fix the build

.github/workflows/ngeo-2-8.yaml, .github/workflows/rebuild-2-8.yaml
See JIRA issue: [GSGMF-1324](https://jira.camptocamp.com/browse/GSGMF-1324).
=> Fix 2.8 rebuild

geoportal/.snyk
[HIGH] nth-check@1.0.2: SNYK-JS-NTHCHECK-1586032 CWE-1333 [Fixed in: 2.0.1].
[HIGH] ws@8.12.1: SNYK-JS-WS-7266574 CWE-400 [Fixed in: 5.2.4, 6.2.3, 7.5.10, 8.17.1].
=> Ignore CVE

.github/workflows/main.yaml, .github/workflows/qgis.yaml, Makefile, ci/create-new-project
See JIRA issue: [BUILD-27](https://camptocamp.atlassian.net/browse/BUILD-27).
=> No more maintain the QGIS version 3.22

Dockerfile, doc/Dockerfile, docker/config/Dockerfile, docker/qgisserver/Dockerfile, geoportal/c2cgeoportal_geoportal/scaffolds/advance_create/{{cookiecutter.project}}/geoportal/Dockerfile, geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/Dockerfile
See: https://docs.docker.com/reference/build-checks/from-as-casing/
=> Fix FromAsCasing

.gitignore
See JIRA issue: [AUDIT-26](https://camptocamp.atlassian.net/browse/AUDIT-26).
=> D'ont commit admin/node_modules/ in audit pull-request

geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/scripts/db-backup, geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/scripts/db-restore
Print the executed command
Don't get a stack trace on error, just forward the code
=> Better output in db-backup/db-restore scripts

geoportal/c2cgeoportal_geoportal/__init__.py, geoportal/c2cgeoportal_geoportal/lib/__init__.py, geoportal/c2cgeoportal_geoportal/lib/filter_capabilities.py, geoportal/c2cgeoportal_geoportal/lib/oidc.py, geoportal/c2cgeoportal_geoportal/views/login.py, geoportal/c2cgeoportal_geoportal/views/mapserverproxy.py, geoportal/c2cgeoportal_geoportal/views/printproxy.py, geoportal/c2cgeoportal_geoportal/views/proxy.py
See JIRA issue: [GSSEC-1](https://camptocamp.atlassian.net/browse/GSSEC-1).
[GSSEC-1]: https://camptocamp.atlassian.net/browse/GSSEC-1?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update the cache key to avoid cache poisoning

admin/c2cgeoportal_admin/schemas/treegroup.py
See https://camptocamp.atlassian.net/browse/GSCAGSUP-199
See JIRA issue: [GSCAGSUP-199](https://camptocamp.atlassian.net/browse/GSCAGSUP-199).
=> Fix missing columns in group by

Makefile, docker/qgisserver/geomapfish_qgisserver/accesscontrol.py, docker/qgisserver/tests/functional/accesscontrol_protected_attributes_test.py, docker/qgisserver/tests/functional/accesscontrol_test.py, geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_vars.yaml
See JIRA issue: [GSBLGEOS-36](https://camptocamp.atlassian.net/browse/GSBLGEOS-36).
[GSBLGEOS-36]: https://camptocamp.atlassian.net/browse/GSBLGEOS-36?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add QGIS server protected attributes

geoportal/c2cgeoportal_geoportal/lib/authentication.py
See also: https://camptocamp.sentry.io/issues/5045146022/events/01ab53cf7be64c278b118a1a8eb2c814/?project=1851011&query=is%3Aunresolved&referrer=previous-event&statsPeriod=14d&stream_index=0
=> Better error message

geoportal/c2cgeoportal_geoportal/__init__.py
Fix: https://camptocamp.sentry.io/issues/5998289889/?project=1851011&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=7
=> Fix apihelp.html redirect

admin/c2cgeoportal_admin/routes.py, admin/c2cgeoportal_admin/views/users.py, admin/tests/test_user.py, commons/c2cgeoportal_commons/models/static.py, doc/integrator/authentication_oidc.rst, geoportal/c2cgeoportal_geoportal/__init__.py, geoportal/c2cgeoportal_geoportal/lib/authentication.py, geoportal/c2cgeoportal_geoportal/lib/oidc.py, geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_config-schema.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_vars.yaml, geoportal/c2cgeoportal_geoportal/views/login.py, geoportal/tests/functional/test_oidc.py
=> OpenID Connect: Add hook to be able to customize role creation

geoportal/c2cgeoportal_geoportal/lib/authentication.py, geoportal/tests/functional/test_authentication.py
Fix: https://camptocamp.sentry.io/issues/5049733617/?notification_uuid=5d246677-3e5c-4b75-a8d3-4bd9fedf04e2&project=1851011&referrer=regression_activity-email
=> Less auth errors

doc/integrator/authentication_oidc.rst
See: https://camptocamp.github.io/c2cgeoportal/master/integrator/authentication_oidc.html
=> Fix OpenID connect documentation rendering

.github/renovate.json5
See JIRA issue: [ADD-2](https://camptocamp.atlassian.net/browse/ADD-2).
=> Add branch 2.9 in Renovate config

.github/workflows/ngeo-2-9.yaml, admin/c2cgeoportal_admin/schemas/dimensions.py, admin/c2cgeoportal_admin/schemas/restriction_areas.py, ci/dpkg-versions.yaml
See JIRA issue: [UPDATE-2](https://camptocamp.atlassian.net/browse/UPDATE-2).
=> The Update ngeo 2.9 workflow shouldn't run on pull request.

doc/integrator/authentication_oidc.rst
See related pull request: https://github.com/qgis/QGIS/pull/54014
=> Add QGIS supported version

admin/c2cgeoportal_admin/views/layertree.py, doc/integrator/authentication_oidc.rst, geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_config-schema.yaml, geoportal/c2cgeoportal_geoportal/views/dev.py, geoportal/c2cgeoportal_geoportal/views/dynamic.py, geoportal/c2cgeoportal_geoportal/views/entry.py, geoportal/c2cgeoportal_geoportal/views/geometry_processing.py, geoportal/c2cgeoportal_geoportal/views/i18n.py, geoportal/c2cgeoportal_geoportal/views/layers.py, geoportal/c2cgeoportal_geoportal/views/login.py, geoportal/c2cgeoportal_geoportal/views/mapserverproxy.py, geoportal/c2cgeoportal_geoportal/views/memory.py, geoportal/c2cgeoportal_geoportal/views/pdfreport.py, geoportal/c2cgeoportal_geoportal/views/printproxy.py, geoportal/c2cgeoportal_geoportal/views/profile.py, geoportal/c2cgeoportal_geoportal/views/raster.py, geoportal/c2cgeoportal_geoportal/views/resourceproxy.py, geoportal/c2cgeoportal_geoportal/views/shortener.py, geoportal/c2cgeoportal_geoportal/views/theme.py, geoportal/c2cgeoportal_geoportal/views/tinyowsproxy.py, geoportal/c2cgeoportal_geoportal/views/vector_tiles.py
See JIRA issue: [GSGGR-214](https://camptocamp.atlassian.net/browse/GSGGR-214).
[GSGGR-214]: https://camptocamp.atlassian.net/browse/GSGGR-214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add possibility to add additional parameters to login end-point

geoportal/c2cgeoportal_geoportal/lib/cacheversion.py
Fix https://camptocamp.sentry.io/issues/5052258158/?project=1851011&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=4
=> Fix call to '/static'

doc/integrator/backend_qgis.rst
Improve documentation as suggested by @michmuel
=> Improve documentation for QGIS backend configuration

geoportal/c2cgeoportal_geoportal/views/dynamic.py
See JIRA issue: [GSGMF-2099](https://camptocamp.atlassian.net/browse/GSGMF-2099).
[GSGMF-2099]: https://camptocamp.atlassian.net/browse/GSGMF-2099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix small cache poisoning

geoportal/c2cgeoportal_geoportal/scaffolds/advance_create/{{cookiecutter.project}}/geoportal/{{cookiecutter.package}}_geoportal/__init__.py, geoportal/c2cgeoportal_geoportal/scaffolds/advance_create/{{cookiecutter.project}}/geoportal/{{cookiecutter.package}}_geoportal/multi_organization.py
=> Remove multi_organization file

geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_vars.yaml
See JIRA issue: [GSBLGEOS-40](https://camptocamp.atlassian.net/browse/GSBLGEOS-40).
[GSBLGEOS-40]: https://camptocamp.atlassian.net/browse/GSBLGEOS-40?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Be more fluent, helped with Claude

geoportal/c2cgeoportal_geoportal/views/theme.py, geoportal/tests/functional/test_themes_ogc_server_cache_clean.py
See JIRA issue: [GSGMF-2141](https://camptocamp.atlassian.net/browse/GSGMF-2141).
[GSGMF-2141]: https://camptocamp.atlassian.net/browse/GSGMF-2141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Don't alter the URL when adding the query

admin/config.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/geoportal/CONST_vars.yaml
See JIRA issue: [GSLIEC-107](https://camptocamp.atlassian.net/browse/GSLIEC-107).
[GSLIEC-107]: https://camptocamp.atlassian.net/browse/GSLIEC-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> The queryLayers metadata is also valid on a WMS layer

ci/dpkg-versions.yaml, commons/c2cgeoportal_commons/alembic/main/2e57710fecfe_update_the_ogc_server_for_ogc_api.py, commons/c2cgeoportal_commons/models/main.py, geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/CONST_CHANGELOG.txt
See JIRA issue: [GSGMF-2147](https://camptocamp.atlassian.net/browse/GSGMF-2147).
[GSGMF-2147]: https://camptocamp.atlassian.net/browse/GSGMF-2147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OGC server metadata update

geoportal/c2cgeoportal_geoportal/views/tinyowsproxy.py
See JIRA issue: [GSGMF-2150](https://camptocamp.atlassian.net/browse/GSGMF-2150).
[GSGMF-2150]: https://camptocamp.atlassian.net/browse/GSGMF-2150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Better error on missing OGC Server

scripts/get-version
Add specific versions for Update ngeo workflows
See JIRA issue: [GSGMF-2154](https://camptocamp.atlassian.net/browse/GSGMF-2154).
[GSGMF-2154]: https://camptocamp.atlassian.net/browse/GSGMF-2154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix publish version from the Update ngeo workflows

doc/integrator/pdfreport.rst, geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/CONST_CHANGELOG.txt
See JIRA issue: [GSGMF-2150](https://camptocamp.atlassian.net/browse/GSGMF-2150).
[GSGMF-2150]: https://camptocamp.atlassian.net/browse/GSGMF-2150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update the changelog for the OGC API renaming

commons/c2cgeoportal_commons/alembic/static/910b4ca53b68_sync_model_database.py, geoportal/c2cgeoportal_geoportal/__init__.py, geoportal/c2cgeoportal_geoportal/lib/authentication.py, geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/CONST_CHANGELOG.txt, geoportal/c2cgeoportal_geoportal/views/login.py
See JIRA issue: [GSGMF-2153](https://camptocamp.atlassian.net/browse/GSGMF-2153).
[GSGMF-2153]: https://camptocamp.atlassian.net/browse/GSGMF-2153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix oauth2 login

geoportal/c2cgeoportal_geoportal/scripts/theme2fts.py
Do preload and bunk insert
See JIRA issue: [GSGMF-2166](https://camptocamp.atlassian.net/browse/GSGMF-2166).
[GSGMF-2166]: https://camptocamp.atlassian.net/browse/GSGMF-2166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix theme2fts performance issues

geoportal/c2cgeoportal_geoportal/scripts/theme2fts.py, geoportal/tests/functional/test_theme2fts.py
Replace  #11923
See JIRA issue: [GSGMF-2166](https://camptocamp.atlassian.net/browse/GSGMF-2166).
[GSGMF-2166]: https://camptocamp.atlassian.net/browse/GSGMF-2166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add stats in theme 2 full text search script

doc/administrator/mapfile.rst
See JIRA issue: [GSGRAUB-141](https://camptocamp.atlassian.net/browse/GSGRAUB-141).
[GSGRAUB-141]: https://camptocamp.atlassian.net/browse/GSGRAUB-141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix query present in the documentation

geoportal/c2cgeoportal_geoportal/views/login.py, geoportal/tests/functional/test_login.py, geoportal/tests/functional/test_login_2fa.py, geoportal/tests/functional/test_oauth2.py
See JIRA issue: [GSGMF-2168](https://camptocamp.atlassian.net/browse/GSGMF-2168).
[GSGMF-2168]: https://camptocamp.atlassian.net/browse/GSGMF-2168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add display_name to user_login

geoportal/c2cgeoportal_geoportal/scaffolds/advance_create/{{cookiecutter.project}}/geoportal/Dockerfile
See JIRA issue: [GSALG-26](https://camptocamp.atlassian.net/browse/GSALG-26).
[GSALG-26]: https://camptocamp.atlassian.net/browse/GSALG-26?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove duplicated js files

.github/workflows/qgis.yaml
See JIRA issue: [GSCAR-154](https://camptocamp.atlassian.net/browse/GSCAR-154).
[GSCAR-154]: https://camptocamp.atlassian.net/browse/GSCAR-154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add QGIS server 3.40

ci/dpkg-versions.yaml, geoportal/c2cgeoportal_geoportal/scaffolds/advance_create/{{cookiecutter.project}}/geoportal/Dockerfile, geoportal/c2cgeoportal_geoportal/scaffolds/advance_create/{{cookiecutter.project}}/geoportal/webpack.apps.js, geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/docker-compose-lib.yaml
I didn't manage to get the hot reload websocket working, I do not understand how this was working berfore, through geoportal or on  webpack_dev_server port 8080 directly ?
=> Fix webpack_dev_server startup

Dockerfile
See JIRA issue: [GSGEOC-445](https://camptocamp.atlassian.net/browse/GSGEOC-445).
[GSGEOC-445]: https://camptocamp.atlassian.net/browse/GSGEOC-445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Don't clean testing from commons
